package model.EO;

import java.math.BigDecimal;

import oracle.jbo.Key;
import oracle.jbo.RowInconsistentException;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 06 12:40:16 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MilestonesHdr_EOImpl extends EntityImpl {
    
    @Override
        public void lock() {
            try {
                super.lock();
            } catch (RowInconsistentException e) {
                refresh(REFRESH_WITH_DB_ONLY_IF_UNCHANGED | REFRESH_CONTAINEES);
                super.lock();
            }
        }
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        MsHdrId {
            public Object get(MilestonesHdr_EOImpl obj) {
                return obj.getMsHdrId();
            }

            public void put(MilestonesHdr_EOImpl obj, Object value) {
                obj.setMsHdrId((Number)value);
            }
        }
        ,
        MilestoneName {
            public Object get(MilestonesHdr_EOImpl obj) {
                return obj.getMilestoneName();
            }

            public void put(MilestonesHdr_EOImpl obj, Object value) {
                obj.setMilestoneName((String)value);
            }
        }
        ,
        MilestoneNameTl {
            public Object get(MilestonesHdr_EOImpl obj) {
                return obj.getMilestoneNameTl();
            }

            public void put(MilestonesHdr_EOImpl obj, Object value) {
                obj.setMilestoneNameTl((String)value);
            }
        }
        ,
        MilestoneNumber {
            public Object get(MilestonesHdr_EOImpl obj) {
                return obj.getMilestoneNumber();
            }

            public void put(MilestonesHdr_EOImpl obj, Object value) {
                obj.setMilestoneNumber((String)value);
            }
        }
        ,
        MilestoneShortcode {
            public Object get(MilestonesHdr_EOImpl obj) {
                return obj.getMilestoneShortcode();
            }

            public void put(MilestonesHdr_EOImpl obj, Object value) {
                obj.setMilestoneShortcode((String)value);
            }
        }
        ,
        OrgId {
            public Object get(MilestonesHdr_EOImpl obj) {
                return obj.getOrgId();
            }

            public void put(MilestonesHdr_EOImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        ProjectId {
            public Object get(MilestonesHdr_EOImpl obj) {
                return obj.getProjectId();
            }

            public void put(MilestonesHdr_EOImpl obj, Object value) {
                obj.setProjectId((Number)value);
            }
        }
        ,
        Revision {
            public Object get(MilestonesHdr_EOImpl obj) {
                return obj.getRevision();
            }

            public void put(MilestonesHdr_EOImpl obj, Object value) {
                obj.setRevision((Number)value);
            }
        }
        ,
        MilestoneDate {
            public Object get(MilestonesHdr_EOImpl obj) {
                return obj.getMilestoneDate();
            }

            public void put(MilestonesHdr_EOImpl obj, Object value) {
                obj.setMilestoneDate((Date)value);
            }
        }
        ,
        Description {
            public Object get(MilestonesHdr_EOImpl obj) {
                return obj.getDescription();
            }

            public void put(MilestonesHdr_EOImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        ActiveYn {
            public Object get(MilestonesHdr_EOImpl obj) {
                return obj.getActiveYn();
            }

            public void put(MilestonesHdr_EOImpl obj, Object value) {
                obj.setActiveYn((String)value);
            }
        }
        ,
        Status {
            public Object get(MilestonesHdr_EOImpl obj) {
                return obj.getStatus();
            }

            public void put(MilestonesHdr_EOImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        AttributeCategory {
            public Object get(MilestonesHdr_EOImpl obj) {
                return obj.getAttributeCategory();
            }

            public void put(MilestonesHdr_EOImpl obj, Object value) {
                obj.setAttributeCategory((String)value);
            }
        }
        ,
        Attribute1 {
            public Object get(MilestonesHdr_EOImpl obj) {
                return obj.getAttribute1();
            }

            public void put(MilestonesHdr_EOImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(MilestonesHdr_EOImpl obj) {
                return obj.getAttribute2();
            }

            public void put(MilestonesHdr_EOImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(MilestonesHdr_EOImpl obj) {
                return obj.getAttribute3();
            }

            public void put(MilestonesHdr_EOImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(MilestonesHdr_EOImpl obj) {
                return obj.getAttribute4();
            }

            public void put(MilestonesHdr_EOImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(MilestonesHdr_EOImpl obj) {
                return obj.getAttribute5();
            }

            public void put(MilestonesHdr_EOImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(MilestonesHdr_EOImpl obj) {
                return obj.getAttribute6();
            }

            public void put(MilestonesHdr_EOImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(MilestonesHdr_EOImpl obj) {
                return obj.getAttribute7();
            }

            public void put(MilestonesHdr_EOImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(MilestonesHdr_EOImpl obj) {
                return obj.getAttribute8();
            }

            public void put(MilestonesHdr_EOImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(MilestonesHdr_EOImpl obj) {
                return obj.getAttribute9();
            }

            public void put(MilestonesHdr_EOImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(MilestonesHdr_EOImpl obj) {
                return obj.getAttribute10();
            }

            public void put(MilestonesHdr_EOImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(MilestonesHdr_EOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(MilestonesHdr_EOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CreationDate {
            public Object get(MilestonesHdr_EOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(MilestonesHdr_EOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(MilestonesHdr_EOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(MilestonesHdr_EOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(MilestonesHdr_EOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(MilestonesHdr_EOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(MilestonesHdr_EOImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(MilestonesHdr_EOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        FlowLevel {
            public Object get(MilestonesHdr_EOImpl obj) {
                return obj.getFlowLevel();
            }

            public void put(MilestonesHdr_EOImpl obj, Object value) {
                obj.setFlowLevel((BigDecimal)value);
            }
        }
        ,
        FlowStatus {
            public Object get(MilestonesHdr_EOImpl obj) {
                return obj.getFlowStatus();
            }

            public void put(MilestonesHdr_EOImpl obj, Object value) {
                obj.setFlowStatus((String)value);
            }
        }
        ,
        FlowWith {
            public Object get(MilestonesHdr_EOImpl obj) {
                return obj.getFlowWith();
            }

            public void put(MilestonesHdr_EOImpl obj, Object value) {
                obj.setFlowWith((BigDecimal)value);
            }
        }
        ,
        FuncId {
            public Object get(MilestonesHdr_EOImpl obj) {
                return obj.getFuncId();
            }

            public void put(MilestonesHdr_EOImpl obj, Object value) {
                obj.setFuncId((BigDecimal)value);
            }
        }
        ,
        UserGrpId {
            public Object get(MilestonesHdr_EOImpl obj) {
                return obj.getUserGrpId();
            }

            public void put(MilestonesHdr_EOImpl obj, Object value) {
                obj.setUserGrpId((BigDecimal)value);
            }
        }
        ,
        orgnameTrans {
            public Object get(MilestonesHdr_EOImpl obj) {
                return obj.getorgnameTrans();
            }

            public void put(MilestonesHdr_EOImpl obj, Object value) {
                obj.setorgnameTrans((String)value);
            }
        }
        ,
        MilestonesDtl_EO {
            public Object get(MilestonesHdr_EOImpl obj) {
                return obj.getMilestonesDtl_EO();
            }

            public void put(MilestonesHdr_EOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(MilestonesHdr_EOImpl object);

        public abstract void put(MilestonesHdr_EOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int MSHDRID = AttributesEnum.MsHdrId.index();
    public static final int MILESTONENAME = AttributesEnum.MilestoneName.index();
    public static final int MILESTONENAMETL = AttributesEnum.MilestoneNameTl.index();
    public static final int MILESTONENUMBER = AttributesEnum.MilestoneNumber.index();
    public static final int MILESTONESHORTCODE = AttributesEnum.MilestoneShortcode.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int PROJECTID = AttributesEnum.ProjectId.index();
    public static final int REVISION = AttributesEnum.Revision.index();
    public static final int MILESTONEDATE = AttributesEnum.MilestoneDate.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int ACTIVEYN = AttributesEnum.ActiveYn.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int ATTRIBUTECATEGORY = AttributesEnum.AttributeCategory.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int FLOWLEVEL = AttributesEnum.FlowLevel.index();
    public static final int FLOWSTATUS = AttributesEnum.FlowStatus.index();
    public static final int FLOWWITH = AttributesEnum.FlowWith.index();
    public static final int FUNCID = AttributesEnum.FuncId.index();
    public static final int USERGRPID = AttributesEnum.UserGrpId.index();
    public static final int ORGNAMETRANS = AttributesEnum.orgnameTrans.index();
    public static final int MILESTONESDTL_EO = AttributesEnum.MilestonesDtl_EO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MilestonesHdr_EOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.EO.MilestonesHdr_EO");
    }

    /**
     * Gets the attribute value for MsHdrId, using the alias name MsHdrId.
     * @return the MsHdrId
     */
    public Number getMsHdrId() {
        return (Number)getAttributeInternal(MSHDRID);
    }

    /**
     * Sets <code>value</code> as the attribute value for MsHdrId.
     * @param value value to set the MsHdrId
     */
    public void setMsHdrId(Number value) {
        setAttributeInternal(MSHDRID, value);
    }

    /**
     * Gets the attribute value for MilestoneName, using the alias name MilestoneName.
     * @return the MilestoneName
     */
    public String getMilestoneName() {
        return (String)getAttributeInternal(MILESTONENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for MilestoneName.
     * @param value value to set the MilestoneName
     */
    public void setMilestoneName(String value) {
        setAttributeInternal(MILESTONENAME, value);
    }

    /**
     * Gets the attribute value for MilestoneNameTl, using the alias name MilestoneNameTl.
     * @return the MilestoneNameTl
     */
    public String getMilestoneNameTl() {
        return (String)getAttributeInternal(MILESTONENAMETL);
    }

    /**
     * Sets <code>value</code> as the attribute value for MilestoneNameTl.
     * @param value value to set the MilestoneNameTl
     */
    public void setMilestoneNameTl(String value) {
        setAttributeInternal(MILESTONENAMETL, value);
    }

    /**
     * Gets the attribute value for MilestoneNumber, using the alias name MilestoneNumber.
     * @return the MilestoneNumber
     */
    public String getMilestoneNumber() {
        return (String)getAttributeInternal(MILESTONENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for MilestoneNumber.
     * @param value value to set the MilestoneNumber
     */
    public void setMilestoneNumber(String value) {
        setAttributeInternal(MILESTONENUMBER, value);
    }

    /**
     * Gets the attribute value for MilestoneShortcode, using the alias name MilestoneShortcode.
     * @return the MilestoneShortcode
     */
    public String getMilestoneShortcode() {
        return (String)getAttributeInternal(MILESTONESHORTCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for MilestoneShortcode.
     * @param value value to set the MilestoneShortcode
     */
    public void setMilestoneShortcode(String value) {
        setAttributeInternal(MILESTONESHORTCODE, value);
    }

    /**
     * Gets the attribute value for OrgId, using the alias name OrgId.
     * @return the OrgId
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgId.
     * @param value value to set the OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for ProjectId, using the alias name ProjectId.
     * @return the ProjectId
     */
    public Number getProjectId() {
        return (Number)getAttributeInternal(PROJECTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProjectId.
     * @param value value to set the ProjectId
     */
    public void setProjectId(Number value) {
        setAttributeInternal(PROJECTID, value);
    }

    /**
     * Gets the attribute value for Revision, using the alias name Revision.
     * @return the Revision
     */
    public Number getRevision() {
        return (Number)getAttributeInternal(REVISION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Revision.
     * @param value value to set the Revision
     */
    public void setRevision(Number value) {
        setAttributeInternal(REVISION, value);
    }

    /**
     * Gets the attribute value for MilestoneDate, using the alias name MilestoneDate.
     * @return the MilestoneDate
     */
    public Date getMilestoneDate() {
        return (Date)getAttributeInternal(MILESTONEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for MilestoneDate.
     * @param value value to set the MilestoneDate
     */
    public void setMilestoneDate(Date value) {
        setAttributeInternal(MILESTONEDATE, value);
    }

    /**
     * Gets the attribute value for Description, using the alias name Description.
     * @return the Description
     */
    public String getDescription() {
        return (String)getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Description.
     * @param value value to set the Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for ActiveYn, using the alias name ActiveYn.
     * @return the ActiveYn
     */
    public String getActiveYn() {
        return (String)getAttributeInternal(ACTIVEYN);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActiveYn.
     * @param value value to set the ActiveYn
     */
    public void setActiveYn(String value) {
        setAttributeInternal(ACTIVEYN, value);
    }

    /**
     * Gets the attribute value for Status, using the alias name Status.
     * @return the Status
     */
    public String getStatus() {
        return (String)getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Status.
     * @param value value to set the Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for AttributeCategory, using the alias name AttributeCategory.
     * @return the AttributeCategory
     */
    public String getAttributeCategory() {
        return (String)getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeCategory.
     * @param value value to set the AttributeCategory
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for Attribute6, using the alias name Attribute6.
     * @return the Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute6.
     * @param value value to set the Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for Attribute7, using the alias name Attribute7.
     * @return the Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute7.
     * @param value value to set the Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for Attribute8, using the alias name Attribute8.
     * @return the Attribute8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute8.
     * @param value value to set the Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for Attribute9, using the alias name Attribute9.
     * @return the Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute9.
     * @param value value to set the Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for Attribute10, using the alias name Attribute10.
     * @return the Attribute10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute10.
     * @param value value to set the Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the LastUpdateLogin
     */
    public String getLastUpdateLogin() {
        return (String)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Gets the attribute value for FlowLevel, using the alias name FlowLevel.
     * @return the FlowLevel
     */
    public BigDecimal getFlowLevel() {
        return (BigDecimal)getAttributeInternal(FLOWLEVEL);
    }

    /**
     * Sets <code>value</code> as the attribute value for FlowLevel.
     * @param value value to set the FlowLevel
     */
    public void setFlowLevel(BigDecimal value) {
        setAttributeInternal(FLOWLEVEL, value);
    }

    /**
     * Gets the attribute value for FlowStatus, using the alias name FlowStatus.
     * @return the FlowStatus
     */
    public String getFlowStatus() {
        return (String)getAttributeInternal(FLOWSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for FlowStatus.
     * @param value value to set the FlowStatus
     */
    public void setFlowStatus(String value) {
        setAttributeInternal(FLOWSTATUS, value);
    }

    /**
     * Gets the attribute value for FlowWith, using the alias name FlowWith.
     * @return the FlowWith
     */
    public BigDecimal getFlowWith() {
        return (BigDecimal)getAttributeInternal(FLOWWITH);
    }

    /**
     * Sets <code>value</code> as the attribute value for FlowWith.
     * @param value value to set the FlowWith
     */
    public void setFlowWith(BigDecimal value) {
        setAttributeInternal(FLOWWITH, value);
    }

    /**
     * Gets the attribute value for FuncId, using the alias name FuncId.
     * @return the FuncId
     */
    public BigDecimal getFuncId() {
        return (BigDecimal)getAttributeInternal(FUNCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for FuncId.
     * @param value value to set the FuncId
     */
    public void setFuncId(BigDecimal value) {
        setAttributeInternal(FUNCID, value);
    }

    /**
     * Gets the attribute value for UserGrpId, using the alias name UserGrpId.
     * @return the UserGrpId
     */
    public BigDecimal getUserGrpId() {
        return (BigDecimal)getAttributeInternal(USERGRPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserGrpId.
     * @param value value to set the UserGrpId
     */
    public void setUserGrpId(BigDecimal value) {
        setAttributeInternal(USERGRPID, value);
    }

    /**
     * Gets the attribute value for orgnameTrans, using the alias name orgnameTrans.
     * @return the orgnameTrans
     */
    public String getorgnameTrans() {
        return (String)getAttributeInternal(ORGNAMETRANS);
    }

    /**
     * Sets <code>value</code> as the attribute value for orgnameTrans.
     * @param value value to set the orgnameTrans
     */
    public void setorgnameTrans(String value) {
        setAttributeInternal(ORGNAMETRANS, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMilestonesDtl_EO() {
        return (RowIterator)getAttributeInternal(MILESTONESDTL_EO);
    }

    /**
     * @param msHdrId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number msHdrId) {
        return new Key(new Object[]{msHdrId});
    }


}
