package model.AM.client;

import model.AM.common.PropertyUnits_AM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 26 11:51:27 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PropertyUnits_AMClient extends ApplicationModuleImpl implements PropertyUnits_AM {
    /**
     * This is the default constructor (do not remove).
     */
    public PropertyUnits_AMClient() {
    }

    public String addArea() {
        Object _ret = this.riInvokeExportedMethod(this,"addArea",null,null);
        return (String)_ret;
    }
}
