package model.AM;

import java.sql.CallableStatement;

import java.sql.SQLException;
import java.sql.Types;


import model.AM.common.ExtensionCancellation_AM;

import model.VO.BookingCustomer_VOImpl;
import model.VO.BookingHeader_VOImpl;
import model.VO.ExtCanVOImpl;
import model.VO.LeaseAgreement_VOImpl;
import model.VO.OfferHrd_VOImpl;
import model.VO.PropertyUnits_VOImpl;

import oracle.jbo.JboException;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jul 15 13:37:10 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ExtensionCancellation_AMImpl extends ApplicationModuleImpl implements ExtensionCancellation_AM {
    /**
     * This is the default constructor (do not remove).
     */
    public ExtensionCancellation_AMImpl() {
    }

    /**
     * Container's getter for ExtCanVO1.
     * @return ExtCanVO1
     */
    public ViewObjectImpl getExtCanVO1() {
        return (ViewObjectImpl)findViewObject("ExtCanVO1");
    }

    /**
     * Container's getter for Booking_Milestone_VO1.
     * @return Booking_Milestone_VO1
     */
    public ViewObjectImpl getBooking_Milestone_VO1() {
        return (ViewObjectImpl)findViewObject("Booking_Milestone_VO1");
    }

    /**
     * Container's getter for Booking_Milestone_VO2.
     * @return Booking_Milestone_VO2
     */
    public ViewObjectImpl getBooking_Milestone_VO2() {
        return (ViewObjectImpl)findViewObject("Booking_Milestone_VO2");
    }

    /**
     * Container's getter for Booking_Milestone_VO3.
     * @return Booking_Milestone_VO3
     */
    public ViewObjectImpl getBooking_Milestone_VO3() {
        return (ViewObjectImpl)findViewObject("Booking_Milestone_VO3");
    }

    /**
     * Container's getter for Booking_Milestone_VO4.
     * @return Booking_Milestone_VO4
     */
    public ViewObjectImpl getBooking_Milestone_VO4() {
        return (ViewObjectImpl)findViewObject("Booking_Milestone_VO4");
    }

    /**
     * Container's getter for getFunctionCodeROVO1.
     * @return getFunctionCodeROVO1
     */
    public ViewObjectImpl getgetFunctionCodeROVO1() {
        return (ViewObjectImpl)findViewObject("getFunctionCodeROVO1");
    }

    /**
     * Container's getter for BookingDetail_VO1.
     * @return BookingDetail_VO1
     */
    public ViewObjectImpl getBookingDetail_VO1() {
        return (ViewObjectImpl)findViewObject("BookingDetail_VO1");
    }

    /**
     * Container's getter for PropertyUnits_VO1.
     * @return PropertyUnits_VO1
     */
    public PropertyUnits_VOImpl getPropertyUnits_VO1() {
        return (PropertyUnits_VOImpl)findViewObject("PropertyUnits_VO1");
    }

    /**
     * Container's getter for BookingHeader_VO1.
     * @return BookingHeader_VO1
     */
    public BookingHeader_VOImpl getBookingHeader_VO1() {
        return (BookingHeader_VOImpl)findViewObject("BookingHeader_VO1");
    }

    /**
     * Container's getter for BookingCustomer_VO1.
     * @return BookingCustomer_VO1
     */
    public BookingCustomer_VOImpl getBookingCustomer_VO1() {
        return (BookingCustomer_VOImpl)findViewObject("BookingCustomer_VO1");
    }

    /**
     * Container's getter for BookingHeader_VO2.
     * @return BookingHeader_VO2
     */
    public BookingHeader_VOImpl getBookingHeader_VO2() {
        return (BookingHeader_VOImpl)findViewObject("BookingHeader_VO2");
    }

    /**
     * Container's getter for OfferHrd_VO1.
     * @return OfferHrd_VO1
     */
    public OfferHrd_VOImpl getOfferHrd_VO1() {
        return (OfferHrd_VOImpl)findViewObject("OfferHrd_VO1");
    }

    /**
     * Container's getter for ExtBookVL1.
     * @return ExtBookVL1
     */
    public ViewLinkImpl getExtBookVL1() {
        return (ViewLinkImpl)findViewLink("ExtBookVL1");
    }

    /**
     * Container's getter for ExtBookVL2.
     * @return ExtBookVL2
     */
    public ViewLinkImpl getExtBookVL2() {
        return (ViewLinkImpl)findViewLink("ExtBookVL2");
    }

    /**
     * Container's getter for ExtBookVL3.
     * @return ExtBookVL3
     */
    public ViewLinkImpl getExtBookVL3() {
        return (ViewLinkImpl)findViewLink("ExtBookVL3");
    }

    /**
     * Container's getter for ExtBookVL4.
     * @return ExtBookVL4
     */
    public ViewLinkImpl getExtBookVL4() {
        return (ViewLinkImpl)findViewLink("ExtBookVL4");
    }


    public String UpdateOfferAndLeaseDate(String bookingid, String extnid,
                                          String userId) {


        oracle.jbo.domain.Number p_func_id = new oracle.jbo.domain.Number();
        oracle.jbo.domain.Number p_extnid =
            new oracle.jbo.domain.Number(); //func_id.toString()


        try {
            p_func_id = new oracle.jbo.domain.Number(bookingid);
            p_extnid = new oracle.jbo.domain.Number(extnid);


        } catch (SQLException e) {
            e.printStackTrace();
        }
        String stmt1 =
            " begin \n" +
            "             xxpl_property_lease_pkg.update_offer_StartDate(:p_bookingid,:p_extnid ,:p_user_id,:p_err_code,:p_err_msg);\n" +
            "             END;";
        CallableStatement cst = null;
        try {
            cst = this.getDBTransaction().createCallableStatement(stmt1, 0);
            cst.setObject("p_bookingid", p_func_id);
            cst.setObject("p_extnid", p_extnid);
            cst.setObject("p_user_id", userId);

            cst.registerOutParameter("p_err_code", Types.VARCHAR);
            cst.registerOutParameter("p_err_msg", Types.VARCHAR);
            cst.executeUpdate();
            System.out.println("CHECK" + cst.getString("p_err_msg"));
            return cst.getString("p_err_msg");
        } catch (SQLException e) {
            System.err.println("ERROR" + e);
            throw new JboException(e.getMessage());
        } finally {
            if (cst != null) {
                try {
                    cst.close();
                } catch (SQLException e) {
                    return e.toString();
                }
            }
        }
    }


    public String invokeLocationName(String b_lease_id) {
        oracle.jbo.domain.Number LeaseId =
            new oracle.jbo.domain.Number(); 
        try {
            LeaseId = new oracle.jbo.domain.Number(b_lease_id.toString());
        } catch (SQLException e) {
            e.printStackTrace();
        }

        String stmt1 =
            " begin \n" +
            "             xxpl_property_lease_pkg.get_location_name(:b_lease_id,:b_location,:p_err_code,:p_err_msg);\n" +
            "             END;";
        CallableStatement cst = null;
        try {
            cst = this.getDBTransaction().createCallableStatement(stmt1, 0);
            cst.setObject("b_lease_id", LeaseId);
            cst.registerOutParameter("b_location", Types.VARCHAR);
            cst.registerOutParameter("p_err_code", Types.VARCHAR);
            cst.registerOutParameter("p_err_msg", Types.VARCHAR);
            cst.executeUpdate();

            return cst.getString("b_location");
        } catch (SQLException e) {
            System.err.println("ERROR" + e);
            throw new JboException(e.getMessage());
        } finally {
            if (cst != null) {
                try {
                    cst.close();
                } catch (SQLException e) {
                    return e.toString();
                }
            }
        }
    }


    /**
     * Container's getter for getApprovalHistoryROVo1.
     * @return getApprovalHistoryROVo1
     */
    public ViewObjectImpl getgetApprovalHistoryROVo1() {
        return (ViewObjectImpl)findViewObject("getApprovalHistoryROVo1");
    }

    /**
     * Container's getter for ExtCanApprovalVL1.
     * @return ExtCanApprovalVL1
     */
    public ViewLinkImpl getExtCanApprovalVL1() {
        return (ViewLinkImpl)findViewLink("ExtCanApprovalVL1");
    }

    /**
     * Container's getter for LeaseAgreement_VO1.
     * @return LeaseAgreement_VO1
     */
    public LeaseAgreement_VOImpl getLeaseAgreement_VO1() {
        return (LeaseAgreement_VOImpl)findViewObject("LeaseAgreement_VO1");
    }

    /**
     * Container's getter for offerDetailsforExtnandCancel_ROVO1.
     * @return offerDetailsforExtnandCancel_ROVO1
     */
    public ViewObjectImpl getofferDetailsforExtnandCancel_ROVO1() {
        return (ViewObjectImpl)findViewObject("offerDetailsforExtnandCancel_ROVO1");
    }

    /**
     * Container's getter for BookingDetail_VO2.
     * @return BookingDetail_VO2
     */
    public ViewObjectImpl getBookingDetail_VO2() {
        return (ViewObjectImpl)findViewObject("BookingDetail_VO2");
    }

    /**
     * Container's getter for ExtCanBookVL1.
     * @return ExtCanBookVL1
     */
    public ViewLinkImpl getExtCanBookVL1() {
        return (ViewLinkImpl)findViewLink("ExtCanBookVL1");
    }

    /**
     * Container's getter for canExntCarParkStatusUpdateROVO1.
     * @return canExntCarParkStatusUpdateROVO1
     */
    public ViewObjectImpl getcanExntCarParkStatusUpdateROVO1() {
        return (ViewObjectImpl)findViewObject("canExntCarParkStatusUpdateROVO1");
    }

    /**
     * Container's getter for PropertyUnits_VO2.
     * @return PropertyUnits_VO2
     */
    public PropertyUnits_VOImpl getPropertyUnits_VO2() {
        return (PropertyUnits_VOImpl)findViewObject("PropertyUnits_VO2");
    }


    /**
     * Container's getter for getCarParkingUnitDetailsforExtension_ROVO2.
     * @return getCarParkingUnitDetailsforExtension_ROVO2
     */
    public ViewObjectImpl getgetCarParkingUnitDetailsforExtension_ROVO2() {
        return (ViewObjectImpl)findViewObject("getCarParkingUnitDetailsforExtension_ROVO2");
    }

    /**
     * Container's getter for getCarParkingUnitDetailsforExtension_ROVO3.
     * @return getCarParkingUnitDetailsforExtension_ROVO3
     */
    public ViewObjectImpl getgetCarParkingUnitDetailsforExtension_ROVO3() {
        return (ViewObjectImpl)findViewObject("getCarParkingUnitDetailsforExtension_ROVO3");
    }

    /**
     * Container's getter for ExtensionandOffer_VL2.
     * @return ExtensionandOffer_VL2
     */
    public ViewLinkImpl getExtensionandOffer_VL2() {
        return (ViewLinkImpl)findViewLink("ExtensionandOffer_VL2");
    }

    /**
     * Container's getter for OfferDetail_VO1.
     * @return OfferDetail_VO1
     */
    public ViewObjectImpl getOfferDetail_VO1() {
        return (ViewObjectImpl)findViewObject("OfferDetail_VO1");
    }

    /**
     * Container's getter for DiscountType_StaticRoVo1.
     * @return DiscountType_StaticRoVo1
     */
    public ViewObjectImpl getDiscountType_StaticRoVo1() {
        return (ViewObjectImpl)findViewObject("DiscountType_StaticRoVo1");
    }
}
