package model.AM.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 02 12:51:07 IST 2018
// ---------------------------------------------------------------------
public interface LeadAppModule extends ApplicationModule {
  void refreshLeadApplication();
}
