package model.VO;

import java.math.BigDecimal;

import java.sql.Date;
import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 07 17:05:02 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Billing_VORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        BillingId {
            public Object get(Billing_VORowImpl obj) {
                return obj.getBillingId();
            }

            public void put(Billing_VORowImpl obj, Object value) {
                obj.setBillingId((BigDecimal)value);
            }
        }
        ,
        BillingNumber {
            public Object get(Billing_VORowImpl obj) {
                return obj.getBillingNumber();
            }

            public void put(Billing_VORowImpl obj, Object value) {
                obj.setBillingNumber((String)value);
            }
        }
        ,
        BillingDate {
            public Object get(Billing_VORowImpl obj) {
                return obj.getBillingDate();
            }

            public void put(Billing_VORowImpl obj, Object value) {
                obj.setBillingDate((Date)value);
            }
        }
        ,
        OrgId {
            public Object get(Billing_VORowImpl obj) {
                return obj.getOrgId();
            }

            public void put(Billing_VORowImpl obj, Object value) {
                obj.setOrgId((BigDecimal)value);
            }
        }
        ,
        OrganizationName {
            public Object get(Billing_VORowImpl obj) {
                return obj.getOrganizationName();
            }

            public void put(Billing_VORowImpl obj, Object value) {
                obj.setOrganizationName((String)value);
            }
        }
        ,
        BookingId {
            public Object get(Billing_VORowImpl obj) {
                return obj.getBookingId();
            }

            public void put(Billing_VORowImpl obj, Object value) {
                obj.setBookingId((BigDecimal)value);
            }
        }
        ,
        BookingNumber {
            public Object get(Billing_VORowImpl obj) {
                return obj.getBookingNumber();
            }

            public void put(Billing_VORowImpl obj, Object value) {
                obj.setBookingNumber((String)value);
            }
        }
        ,
        PropertyName {
            public Object get(Billing_VORowImpl obj) {
                return obj.getPropertyName();
            }

            public void put(Billing_VORowImpl obj, Object value) {
                obj.setPropertyName((BigDecimal)value);
            }
        }
        ,
        BuildName {
            public Object get(Billing_VORowImpl obj) {
                return obj.getBuildName();
            }

            public void put(Billing_VORowImpl obj, Object value) {
                obj.setBuildName((BigDecimal)value);
            }
        }
        ,
        Status {
            public Object get(Billing_VORowImpl obj) {
                return obj.getStatus();
            }

            public void put(Billing_VORowImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        Description {
            public Object get(Billing_VORowImpl obj) {
                return obj.getDescription();
            }

            public void put(Billing_VORowImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        FuncId {
            public Object get(Billing_VORowImpl obj) {
                return obj.getFuncId();
            }

            public void put(Billing_VORowImpl obj, Object value) {
                obj.setFuncId((BigDecimal)value);
            }
        }
        ,
        FlowStatus {
            public Object get(Billing_VORowImpl obj) {
                return obj.getFlowStatus();
            }

            public void put(Billing_VORowImpl obj, Object value) {
                obj.setFlowStatus((String)value);
            }
        }
        ,
        FlowLevel {
            public Object get(Billing_VORowImpl obj) {
                return obj.getFlowLevel();
            }

            public void put(Billing_VORowImpl obj, Object value) {
                obj.setFlowLevel((BigDecimal)value);
            }
        }
        ,
        FlowWith {
            public Object get(Billing_VORowImpl obj) {
                return obj.getFlowWith();
            }

            public void put(Billing_VORowImpl obj, Object value) {
                obj.setFlowWith((BigDecimal)value);
            }
        }
        ,
        UserGrpId {
            public Object get(Billing_VORowImpl obj) {
                return obj.getUserGrpId();
            }

            public void put(Billing_VORowImpl obj, Object value) {
                obj.setUserGrpId((BigDecimal)value);
            }
        }
        ,
        CreatedBy {
            public Object get(Billing_VORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(Billing_VORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(Billing_VORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(Billing_VORowImpl obj, Object value) {
                obj.setCreationDate((Timestamp)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(Billing_VORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(Billing_VORowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(Billing_VORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(Billing_VORowImpl obj, Object value) {
                obj.setLastUpdateDate((Timestamp)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(Billing_VORowImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(Billing_VORowImpl obj, Object value) {
                obj.setLastUpdateLogin((String)value);
            }
        }
        ,
        Booking_Milestone_VO1 {
            public Object get(Billing_VORowImpl obj) {
                return obj.getBooking_Milestone_VO1();
            }

            public void put(Billing_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Org_ROVO1 {
            public Object get(Billing_VORowImpl obj) {
                return obj.getOrg_ROVO1();
            }

            public void put(Billing_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SearchBookingROVO1 {
            public Object get(Billing_VORowImpl obj) {
                return obj.getSearchBookingROVO1();
            }

            public void put(Billing_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        findPropertyROVO1 {
            public Object get(Billing_VORowImpl obj) {
                return obj.getfindPropertyROVO1();
            }

            public void put(Billing_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        findBuildingROVO1 {
            public Object get(Billing_VORowImpl obj) {
                return obj.getfindBuildingROVO1();
            }

            public void put(Billing_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Lookup_View_ROVO1 {
            public Object get(Billing_VORowImpl obj) {
                return obj.getLookup_View_ROVO1();
            }

            public void put(Billing_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        findByBuildName1 {
            public Object get(Billing_VORowImpl obj) {
                return obj.getfindByBuildName1();
            }

            public void put(Billing_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(Billing_VORowImpl object);

        public abstract void put(Billing_VORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BILLINGID = AttributesEnum.BillingId.index();
    public static final int BILLINGNUMBER = AttributesEnum.BillingNumber.index();
    public static final int BILLINGDATE = AttributesEnum.BillingDate.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int ORGANIZATIONNAME = AttributesEnum.OrganizationName.index();
    public static final int BOOKINGID = AttributesEnum.BookingId.index();
    public static final int BOOKINGNUMBER = AttributesEnum.BookingNumber.index();
    public static final int PROPERTYNAME = AttributesEnum.PropertyName.index();
    public static final int BUILDNAME = AttributesEnum.BuildName.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int FUNCID = AttributesEnum.FuncId.index();
    public static final int FLOWSTATUS = AttributesEnum.FlowStatus.index();
    public static final int FLOWLEVEL = AttributesEnum.FlowLevel.index();
    public static final int FLOWWITH = AttributesEnum.FlowWith.index();
    public static final int USERGRPID = AttributesEnum.UserGrpId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int BOOKING_MILESTONE_VO1 = AttributesEnum.Booking_Milestone_VO1.index();
    public static final int ORG_ROVO1 = AttributesEnum.Org_ROVO1.index();
    public static final int SEARCHBOOKINGROVO1 = AttributesEnum.SearchBookingROVO1.index();
    public static final int FINDPROPERTYROVO1 = AttributesEnum.findPropertyROVO1.index();
    public static final int FINDBUILDINGROVO1 = AttributesEnum.findBuildingROVO1.index();
    public static final int LOOKUP_VIEW_ROVO1 = AttributesEnum.Lookup_View_ROVO1.index();
    public static final int FINDBYBUILDNAME1 = AttributesEnum.findByBuildName1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public Billing_VORowImpl() {
    }

    /**
     * Gets Billing_EO entity object.
     * @return the Billing_EO
     */
    public EntityImpl getBilling_EO() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for BILLING_ID using the alias name BillingId.
     * @return the BILLING_ID
     */
    public BigDecimal getBillingId() {
        return (BigDecimal) getAttributeInternal(BILLINGID);
    }

    /**
     * Sets <code>value</code> as attribute value for BILLING_ID using the alias name BillingId.
     * @param value value to set the BILLING_ID
     */
    public void setBillingId(BigDecimal value) {
        setAttributeInternal(BILLINGID, value);
    }

    /**
     * Gets the attribute value for BILLING_NUMBER using the alias name BillingNumber.
     * @return the BILLING_NUMBER
     */
    public String getBillingNumber() {
        return (String) getAttributeInternal(BILLINGNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for BILLING_NUMBER using the alias name BillingNumber.
     * @param value value to set the BILLING_NUMBER
     */
    public void setBillingNumber(String value) {
        setAttributeInternal(BILLINGNUMBER, value);
    }

    /**
     * Gets the attribute value for BILLING_DATE using the alias name BillingDate.
     * @return the BILLING_DATE
     */
    public Date getBillingDate() {
        return (Date) getAttributeInternal(BILLINGDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for BILLING_DATE using the alias name BillingDate.
     * @param value value to set the BILLING_DATE
     */
    public void setBillingDate(Date value) {
        setAttributeInternal(BILLINGDATE, value);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public BigDecimal getOrgId() {
        return (BigDecimal) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(BigDecimal value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OrganizationName.
     * @return the OrganizationName
     */
    public String getOrganizationName() {
        return (String) getAttributeInternal(ORGANIZATIONNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OrganizationName.
     * @param value value to set the  OrganizationName
     */
    public void setOrganizationName(String value) {
        setAttributeInternal(ORGANIZATIONNAME, value);
    }

    /**
     * Gets the attribute value for BOOKING_ID using the alias name BookingId.
     * @return the BOOKING_ID
     */
    public BigDecimal getBookingId() {
        return (BigDecimal) getAttributeInternal(BOOKINGID);
    }

    /**
     * Sets <code>value</code> as attribute value for BOOKING_ID using the alias name BookingId.
     * @param value value to set the BOOKING_ID
     */
    public void setBookingId(BigDecimal value) {
        setAttributeInternal(BOOKINGID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BookingNumber.
     * @return the BookingNumber
     */
    public String getBookingNumber() {
        String bookingNumber=null;
         if (getBookingId()!= null) {
            Row[] deptRows;
            deptRows = getSearchBookingROVO1().getFilteredRows("BookingId", getBookingId());
                if (deptRows.length > 0) {
                     bookingNumber = deptRows[0].getAttribute("BookingNumber").toString();
                        }
                     return bookingNumber;
                        } else {
        return (String) getAttributeInternal(BOOKINGNUMBER);
                        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BookingNumber.
     * @param value value to set the  BookingNumber
     */
    public void setBookingNumber(String value) {
        setAttributeInternal(BOOKINGNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PropertyName.
     * @return the PropertyName
     */
    public BigDecimal getPropertyName() {
        return (BigDecimal) getAttributeInternal(PROPERTYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PropertyName.
     * @param value value to set the  PropertyName
     */
    public void setPropertyName(BigDecimal value) {
        setAttributeInternal(PROPERTYNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BuildName.
     * @return the BuildName
     */
    public BigDecimal getBuildName() {
        return (BigDecimal) getAttributeInternal(BUILDNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BuildName.
     * @param value value to set the  BuildName
     */
    public void setBuildName(BigDecimal value) {
        setAttributeInternal(BUILDNAME, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for DESCRIPTION using the alias name Description.
     * @return the DESCRIPTION
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for DESCRIPTION using the alias name Description.
     * @param value value to set the DESCRIPTION
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for FUNC_ID using the alias name FuncId.
     * @return the FUNC_ID
     */
    public BigDecimal getFuncId() {
        return (BigDecimal) getAttributeInternal(FUNCID);
    }

    /**
     * Sets <code>value</code> as attribute value for FUNC_ID using the alias name FuncId.
     * @param value value to set the FUNC_ID
     */
    public void setFuncId(BigDecimal value) {
        setAttributeInternal(FUNCID, value);
    }

    /**
     * Gets the attribute value for FLOW_STATUS using the alias name FlowStatus.
     * @return the FLOW_STATUS
     */
    public String getFlowStatus() {
        return (String) getAttributeInternal(FLOWSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for FLOW_STATUS using the alias name FlowStatus.
     * @param value value to set the FLOW_STATUS
     */
    public void setFlowStatus(String value) {
        setAttributeInternal(FLOWSTATUS, value);
    }

    /**
     * Gets the attribute value for FLOW_LEVEL using the alias name FlowLevel.
     * @return the FLOW_LEVEL
     */
    public BigDecimal getFlowLevel() {
        return (BigDecimal) getAttributeInternal(FLOWLEVEL);
    }

    /**
     * Sets <code>value</code> as attribute value for FLOW_LEVEL using the alias name FlowLevel.
     * @param value value to set the FLOW_LEVEL
     */
    public void setFlowLevel(BigDecimal value) {
        setAttributeInternal(FLOWLEVEL, value);
    }

    /**
     * Gets the attribute value for FLOW_WITH using the alias name FlowWith.
     * @return the FLOW_WITH
     */
    public BigDecimal getFlowWith() {
        return (BigDecimal) getAttributeInternal(FLOWWITH);
    }

    /**
     * Sets <code>value</code> as attribute value for FLOW_WITH using the alias name FlowWith.
     * @param value value to set the FLOW_WITH
     */
    public void setFlowWith(BigDecimal value) {
        setAttributeInternal(FLOWWITH, value);
    }

    /**
     * Gets the attribute value for USER_GRP_ID using the alias name UserGrpId.
     * @return the USER_GRP_ID
     */
    public BigDecimal getUserGrpId() {
        return (BigDecimal) getAttributeInternal(USERGRPID);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_GRP_ID using the alias name UserGrpId.
     * @param value value to set the USER_GRP_ID
     */
    public void setUserGrpId(BigDecimal value) {
        setAttributeInternal(USERGRPID, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }


    /**
     * Gets the associated <code>RowIterator</code> using master-detail link Booking_Milestone_VO.
     */
//    public RowIterator getBooking_Milestone_VO() {
//        return (RowIterator)getAttributeInternal(BOOKING_MILESTONE_VO);
//    }


    /**
     * Gets the associated <code>RowIterator</code> using master-detail link Booking_Milestone_VO1.
     */
    public RowIterator getBooking_Milestone_VO1() {
        return (RowIterator)getAttributeInternal(BOOKING_MILESTONE_VO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Org_ROVO1.
     */
    public RowSet getOrg_ROVO1() {
        return (RowSet)getAttributeInternal(ORG_ROVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SearchBookingROVO1.
     */
    public RowSet getSearchBookingROVO1() {
        return (RowSet)getAttributeInternal(SEARCHBOOKINGROVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> findPropertyROVO1.
     */
    public RowSet getfindPropertyROVO1() {
        return (RowSet)getAttributeInternal(FINDPROPERTYROVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> findBuildingROVO1.
     */
    public RowSet getfindBuildingROVO1() {
        return (RowSet)getAttributeInternal(FINDBUILDINGROVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Lookup_View_ROVO1.
     */
    public RowSet getLookup_View_ROVO1() {
        return (RowSet)getAttributeInternal(LOOKUP_VIEW_ROVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> findByBuildName1.
     */
    public RowSet getfindByBuildName1() {
        return (RowSet)getAttributeInternal(FINDBYBUILDNAME1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
