package model.VO;

import java.math.BigDecimal;

import oracle.adf.share.ADFContext;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 02 15:36:18 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OfferHrd_VORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Attribute1 {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        AttributeCategory {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getAttributeCategory();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setAttributeCategory((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setCreationDate((Timestamp)value);
            }
        }
        ,
        CustSiteId {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getCustSiteId();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setCustSiteId((Number)value);
            }
        }
        ,
        CustomerId {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getCustomerId();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setCustomerId((Number)value);
            }
        }
        ,
        Description {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getDescription();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        FlowLevel {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getFlowLevel();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setFlowLevel((Number)value);
            }
        }
        ,
        FlowStatus {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getFlowStatus();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setFlowStatus((String)value);
            }
        }
        ,
        FlowWith {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getFlowWith();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setFlowWith((Number)value);
            }
        }
        ,
        FuncId {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getFuncId();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setFuncId((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setLastUpdateDate((Timestamp)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setLastUpdateLogin((String)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LeadId {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getLeadId();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setLeadId((Number)value);
            }
        }
        ,
        MsHdrId {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getMsHdrId();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setMsHdrId((Number)value);
            }
        }
        ,
        NetOfferAmount {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getNetOfferAmount();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setNetOfferAmount((Number)value);
            }
        }
        ,
        OfferDate {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getOfferDate();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setOfferDate((Date)value);
            }
        }
        ,
        OfferFromDate {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getOfferFromDate();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setOfferFromDate((Date)value);
            }
        }
        ,
        OfferHdrId {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getOfferHdrId();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setOfferHdrId((Number)value);
            }
        }
        ,
        OfferNumber {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getOfferNumber();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setOfferNumber((String)value);
            }
        }
        ,
        OfferToDate {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getOfferToDate();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setOfferToDate((Date)value);
            }
        }
        ,
        OfferType {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getOfferType();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setOfferType((String)value);
            }
        }
        ,
        OrgId {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getOrgId();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        PerformedBy {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getPerformedBy();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setPerformedBy((Number)value);
            }
        }
        ,
        RevisionNo {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getRevisionNo();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setRevisionNo((Number)value);
            }
        }
        ,
        SalesmanId {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getSalesmanId();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setSalesmanId((Number)value);
            }
        }
        ,
        Status {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getStatus();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        TaxAmount {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getTaxAmount();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setTaxAmount((Number)value);
            }
        }
        ,
        PlId {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getPlId();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setPlId((Number)value);
            }
        }
        ,
        CustomerName {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getCustomerName();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setCustomerName((String)value);
            }
        }
        ,
        Currency {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getCurrency();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setCurrency((String)value);
            }
        }
        ,
        CustomerPhoneNo {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getCustomerPhoneNo();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setCustomerPhoneNo((String)value);
            }
        }
        ,
        CustomerCountry {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getCustomerCountry();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setCustomerCountry((String)value);
            }
        }
        ,
        Checklist {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getChecklist();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setChecklist((String)value);
            }
        }
        ,
        OfferTotal {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getOfferTotal();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setOfferTotal((Number)value);
            }
        }
        ,
        Terms {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getTerms();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setTerms((String)value);
            }
        }
        ,
        ObjectVersionNumber {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getObjectVersionNumber();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setObjectVersionNumber((Number)value);
            }
        }
        ,
        UserGrpId {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getUserGrpId();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setUserGrpId((BigDecimal)value);
            }
        }
        ,
        LeaseAgreementId {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getLeaseAgreementId();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setLeaseAgreementId((BigDecimal)value);
            }
        }
        ,
        OfferFlag {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getOfferFlag();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setOfferFlag((String)value);
            }
        }
        ,
        PropertyId {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getPropertyId();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setPropertyId((BigDecimal)value);
            }
        }
        ,
        BuildingId {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getBuildingId();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setBuildingId((BigDecimal)value);
            }
        }
        ,
        LeaseType {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getLeaseType();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setLeaseType((String)value);
            }
        }
        ,
        TaxCode {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getTaxCode();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setTaxCode((String)value);
            }
        }
        ,
        CarParkLeaseAgreId {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getCarParkLeaseAgreId();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setCarParkLeaseAgreId((BigDecimal)value);
            }
        }
        ,
        LeadName {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getLeadName();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setLeadName((String)value);
            }
        }
        ,
        LeadNumber {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getLeadNumber();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setLeadNumber((String)value);
            }
        }
        ,
        ExtensionDays {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getExtensionDays();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setExtensionDays((String)value);
            }
        }
        ,
        Offerexpireddate {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getOfferexpireddate();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setOfferexpireddate((Date)value);
            }
        }
        ,
        ExpectedDiscount {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getExpectedDiscount();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setExpectedDiscount((BigDecimal)value);
            }
        }
        ,
        Trans_LeadNumber {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getTrans_LeadNumber();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setTrans_LeadNumber((String)value);
            }
        }
        ,
        Current_Date {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getCurrent_Date();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setCurrent_Date((Date)value);
            }
        }
        ,
        DateRestriction_Trans {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getDateRestriction_Trans();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setDateRestriction_Trans((Date)value);
            }
        }
        ,
        Trans_PriceListType {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getTrans_PriceListType();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setTrans_PriceListType((String)value);
            }
        }
        ,
        TotalTaxAmountTrans {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getTotalTaxAmountTrans();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setTotalTaxAmountTrans((String)value);
            }
        }
        ,
        TotalBaseRAteTrans {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getTotalBaseRAteTrans();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setTotalBaseRAteTrans((String)value);
            }
        }
        ,
        TotalOfferRentTrans {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getTotalOfferRentTrans();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setTotalOfferRentTrans((String)value);
            }
        }
        ,
        TotalDiscountsRAteTrans {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getTotalDiscountsRAteTrans();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setTotalDiscountsRAteTrans((String)value);
            }
        }
        ,
        Trans_LeadName1 {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getTrans_LeadName1();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setTrans_LeadName1((String)value);
            }
        }
        ,
        Trans_MobileNumber {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getTrans_MobileNumber();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setTrans_MobileNumber((String)value);
            }
        }
        ,
        Trans_Address1 {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getTrans_Address1();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setTrans_Address1((String)value);
            }
        }
        ,
        Trans_Address2 {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getTrans_Address2();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setTrans_Address2((String)value);
            }
        }
        ,
        Trans_Address3 {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getTrans_Address3();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setTrans_Address3((String)value);
            }
        }
        ,
        Trans_Address4 {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getTrans_Address4();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setTrans_Address4((String)value);
            }
        }
        ,
        Trans_city {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getTrans_city();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setTrans_city((String)value);
            }
        }
        ,
        Trans_country {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getTrans_country();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setTrans_country((String)value);
            }
        }
        ,
        Trans_Email {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getTrans_Email();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setTrans_Email((String)value);
            }
        }
        ,
        CarParkLeaseAgreIdTrans {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getCarParkLeaseAgreIdTrans();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setCarParkLeaseAgreIdTrans((String)value);
            }
        }
        ,
        LeaseNumber_Trans {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getLeaseNumber_Trans();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setLeaseNumber_Trans((String)value);
            }
        }
        ,
        ExpectedDiscount_Trans {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getExpectedDiscount_Trans();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setExpectedDiscount_Trans((String)value);
            }
        }
        ,
        RequestedNetRent {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getRequestedNetRent();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setRequestedNetRent((BigDecimal)value);
            }
        }
        ,
        OfferTotalWithoutTax {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getOfferTotalWithoutTax();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setOfferTotalWithoutTax((BigDecimal)value);
            }
        }
        ,
        UnitIncharge {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getUnitIncharge();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setUnitIncharge((String)value);
            }
        }
        ,
        UnitOwner {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getUnitOwner();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setUnitOwner((String)value);
            }
        }
        ,
        OfferDetail_VO {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getOfferDetail_VO();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        OfferMilestoneDetail_VO {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getOfferMilestoneDetail_VO();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        getApprovalHistoryROVo {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getgetApprovalHistoryROVo();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        OfferDiscountFlow_VO {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getOfferDiscountFlow_VO();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LeadVA {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getLeadVA();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LeadVA_E {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getLeadVA_E();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Lookup_View_ROVA {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getLookup_View_ROVA();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Lookup_View_ROVA_OffType {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getLookup_View_ROVA_OffType();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Organizations_ROVA {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getOrganizations_ROVA();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        findByMileStoneNameROVA {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getfindByMileStoneNameROVA();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PlHeader_VO1 {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getPlHeader_VO1();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Lookup_View_ROVO_Terms {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getLookup_View_ROVO_Terms();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Lookup_View_ROVO_CheckLIst {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getLookup_View_ROVO_CheckLIst();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LeaseAgreement_VO1 {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getLeaseAgreement_VO1();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Lookup_View_ROVA_currency {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getLookup_View_ROVA_currency();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Lookup_View_ROVO1 {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getLookup_View_ROVO1();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PlHeader_VO2 {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getPlHeader_VO2();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        UnitTypeSTA1 {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getUnitTypeSTA1();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Lookup_View_ROVO2 {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getLookup_View_ROVO2();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        OfferDetail_VO_TotBaseRate {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getOfferDetail_VO_TotBaseRate();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        OfferDetail_VO2_Totaltax {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getOfferDetail_VO2_Totaltax();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        OfferDetail_VO_TotDsicount {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getOfferDetail_VO_TotDsicount();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        offerDetailsforExtnandCancel_ROVO1 {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getofferDetailsforExtnandCancel_ROVO1();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Lookup_View_Ext {
            public Object get(OfferHrd_VORowImpl obj) {
                return obj.getLookup_View_Ext();
            }

            public void put(OfferHrd_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(OfferHrd_VORowImpl object);

        public abstract void put(OfferHrd_VORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTECATEGORY = AttributesEnum.AttributeCategory.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CUSTSITEID = AttributesEnum.CustSiteId.index();
    public static final int CUSTOMERID = AttributesEnum.CustomerId.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int FLOWLEVEL = AttributesEnum.FlowLevel.index();
    public static final int FLOWSTATUS = AttributesEnum.FlowStatus.index();
    public static final int FLOWWITH = AttributesEnum.FlowWith.index();
    public static final int FUNCID = AttributesEnum.FuncId.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LEADID = AttributesEnum.LeadId.index();
    public static final int MSHDRID = AttributesEnum.MsHdrId.index();
    public static final int NETOFFERAMOUNT = AttributesEnum.NetOfferAmount.index();
    public static final int OFFERDATE = AttributesEnum.OfferDate.index();
    public static final int OFFERFROMDATE = AttributesEnum.OfferFromDate.index();
    public static final int OFFERHDRID = AttributesEnum.OfferHdrId.index();
    public static final int OFFERNUMBER = AttributesEnum.OfferNumber.index();
    public static final int OFFERTODATE = AttributesEnum.OfferToDate.index();
    public static final int OFFERTYPE = AttributesEnum.OfferType.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int PERFORMEDBY = AttributesEnum.PerformedBy.index();
    public static final int REVISIONNO = AttributesEnum.RevisionNo.index();
    public static final int SALESMANID = AttributesEnum.SalesmanId.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int TAXAMOUNT = AttributesEnum.TaxAmount.index();
    public static final int PLID = AttributesEnum.PlId.index();
    public static final int CUSTOMERNAME = AttributesEnum.CustomerName.index();
    public static final int CURRENCY = AttributesEnum.Currency.index();
    public static final int CUSTOMERPHONENO = AttributesEnum.CustomerPhoneNo.index();
    public static final int CUSTOMERCOUNTRY = AttributesEnum.CustomerCountry.index();
    public static final int CHECKLIST = AttributesEnum.Checklist.index();
    public static final int OFFERTOTAL = AttributesEnum.OfferTotal.index();
    public static final int TERMS = AttributesEnum.Terms.index();
    public static final int OBJECTVERSIONNUMBER = AttributesEnum.ObjectVersionNumber.index();
    public static final int USERGRPID = AttributesEnum.UserGrpId.index();
    public static final int LEASEAGREEMENTID = AttributesEnum.LeaseAgreementId.index();
    public static final int OFFERFLAG = AttributesEnum.OfferFlag.index();
    public static final int PROPERTYID = AttributesEnum.PropertyId.index();
    public static final int BUILDINGID = AttributesEnum.BuildingId.index();
    public static final int LEASETYPE = AttributesEnum.LeaseType.index();
    public static final int TAXCODE = AttributesEnum.TaxCode.index();
    public static final int CARPARKLEASEAGREID = AttributesEnum.CarParkLeaseAgreId.index();
    public static final int LEADNAME = AttributesEnum.LeadName.index();
    public static final int LEADNUMBER = AttributesEnum.LeadNumber.index();
    public static final int EXTENSIONDAYS = AttributesEnum.ExtensionDays.index();
    public static final int OFFEREXPIREDDATE = AttributesEnum.Offerexpireddate.index();
    public static final int EXPECTEDDISCOUNT = AttributesEnum.ExpectedDiscount.index();
    public static final int TRANS_LEADNUMBER = AttributesEnum.Trans_LeadNumber.index();
    public static final int CURRENT_DATE = AttributesEnum.Current_Date.index();
    public static final int DATERESTRICTION_TRANS = AttributesEnum.DateRestriction_Trans.index();
    public static final int TRANS_PRICELISTTYPE = AttributesEnum.Trans_PriceListType.index();
    public static final int TOTALTAXAMOUNTTRANS = AttributesEnum.TotalTaxAmountTrans.index();
    public static final int TOTALBASERATETRANS = AttributesEnum.TotalBaseRAteTrans.index();
    public static final int TOTALOFFERRENTTRANS = AttributesEnum.TotalOfferRentTrans.index();
    public static final int TOTALDISCOUNTSRATETRANS = AttributesEnum.TotalDiscountsRAteTrans.index();
    public static final int TRANS_LEADNAME1 = AttributesEnum.Trans_LeadName1.index();
    public static final int TRANS_MOBILENUMBER = AttributesEnum.Trans_MobileNumber.index();
    public static final int TRANS_ADDRESS1 = AttributesEnum.Trans_Address1.index();
    public static final int TRANS_ADDRESS2 = AttributesEnum.Trans_Address2.index();
    public static final int TRANS_ADDRESS3 = AttributesEnum.Trans_Address3.index();
    public static final int TRANS_ADDRESS4 = AttributesEnum.Trans_Address4.index();
    public static final int TRANS_CITY = AttributesEnum.Trans_city.index();
    public static final int TRANS_COUNTRY = AttributesEnum.Trans_country.index();
    public static final int TRANS_EMAIL = AttributesEnum.Trans_Email.index();
    public static final int CARPARKLEASEAGREIDTRANS = AttributesEnum.CarParkLeaseAgreIdTrans.index();
    public static final int LEASENUMBER_TRANS = AttributesEnum.LeaseNumber_Trans.index();
    public static final int EXPECTEDDISCOUNT_TRANS = AttributesEnum.ExpectedDiscount_Trans.index();
    public static final int REQUESTEDNETRENT = AttributesEnum.RequestedNetRent.index();
    public static final int OFFERTOTALWITHOUTTAX = AttributesEnum.OfferTotalWithoutTax.index();
    public static final int UNITINCHARGE = AttributesEnum.UnitIncharge.index();
    public static final int UNITOWNER = AttributesEnum.UnitOwner.index();
    public static final int OFFERDETAIL_VO = AttributesEnum.OfferDetail_VO.index();
    public static final int OFFERMILESTONEDETAIL_VO = AttributesEnum.OfferMilestoneDetail_VO.index();
    public static final int GETAPPROVALHISTORYROVO = AttributesEnum.getApprovalHistoryROVo.index();
    public static final int OFFERDISCOUNTFLOW_VO = AttributesEnum.OfferDiscountFlow_VO.index();
    public static final int LEADVA = AttributesEnum.LeadVA.index();
    public static final int LEADVA_E = AttributesEnum.LeadVA_E.index();
    public static final int LOOKUP_VIEW_ROVA = AttributesEnum.Lookup_View_ROVA.index();
    public static final int LOOKUP_VIEW_ROVA_OFFTYPE = AttributesEnum.Lookup_View_ROVA_OffType.index();
    public static final int ORGANIZATIONS_ROVA = AttributesEnum.Organizations_ROVA.index();
    public static final int FINDBYMILESTONENAMEROVA = AttributesEnum.findByMileStoneNameROVA.index();
    public static final int PLHEADER_VO1 = AttributesEnum.PlHeader_VO1.index();
    public static final int LOOKUP_VIEW_ROVO_TERMS = AttributesEnum.Lookup_View_ROVO_Terms.index();
    public static final int LOOKUP_VIEW_ROVO_CHECKLIST = AttributesEnum.Lookup_View_ROVO_CheckLIst.index();
    public static final int LEASEAGREEMENT_VO1 = AttributesEnum.LeaseAgreement_VO1.index();
    public static final int LOOKUP_VIEW_ROVA_CURRENCY = AttributesEnum.Lookup_View_ROVA_currency.index();
    public static final int LOOKUP_VIEW_ROVO1 = AttributesEnum.Lookup_View_ROVO1.index();
    public static final int PLHEADER_VO2 = AttributesEnum.PlHeader_VO2.index();
    public static final int UNITTYPESTA1 = AttributesEnum.UnitTypeSTA1.index();
    public static final int LOOKUP_VIEW_ROVO2 = AttributesEnum.Lookup_View_ROVO2.index();
    public static final int OFFERDETAIL_VO_TOTBASERATE = AttributesEnum.OfferDetail_VO_TotBaseRate.index();
    public static final int OFFERDETAIL_VO2_TOTALTAX = AttributesEnum.OfferDetail_VO2_Totaltax.index();
    public static final int OFFERDETAIL_VO_TOTDSICOUNT = AttributesEnum.OfferDetail_VO_TotDsicount.index();
    public static final int OFFERDETAILSFOREXTNANDCANCEL_ROVO1 = AttributesEnum.offerDetailsforExtnandCancel_ROVO1.index();
    public static final int LOOKUP_VIEW_EXT = AttributesEnum.Lookup_View_Ext.index();

    /**
     * This is the default constructor (do not remove).
     */
    public OfferHrd_VORowImpl() {
    }

    /**
     * Gets OfferHeaderVO entity object.
     * @return the OfferHeaderVO
     */
    public EntityImpl getOfferHeaderVO() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @return the ATTRIBUTE_CATEGORY
     */
    public String getAttributeCategory() {
        return (String) getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @param value value to set the ATTRIBUTE_CATEGORY
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CUST_SITE_ID using the alias name CustSiteId.
     * @return the CUST_SITE_ID
     */
    public Number getCustSiteId() {
        return (Number)getAttributeInternal(CUSTSITEID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUST_SITE_ID using the alias name CustSiteId.
     * @param value value to set the CUST_SITE_ID
     */
    public void setCustSiteId(Number value) {
        setAttributeInternal(CUSTSITEID, value);
    }

    /**
     * Gets the attribute value for CUSTOMER_ID using the alias name CustomerId.
     * @return the CUSTOMER_ID
     */
    public Number getCustomerId() {
        return (Number)getAttributeInternal(CUSTOMERID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMER_ID using the alias name CustomerId.
     * @param value value to set the CUSTOMER_ID
     */
    public void setCustomerId(Number value) {
        setAttributeInternal(CUSTOMERID, value);
    }

    /**
     * Gets the attribute value for DESCRIPTION using the alias name Description.
     * @return the DESCRIPTION
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for DESCRIPTION using the alias name Description.
     * @param value value to set the DESCRIPTION
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for FLOW_LEVEL using the alias name FlowLevel.
     * @return the FLOW_LEVEL
     */
    public Number getFlowLevel() {
        return (Number)getAttributeInternal(FLOWLEVEL);
    }

    /**
     * Sets <code>value</code> as attribute value for FLOW_LEVEL using the alias name FlowLevel.
     * @param value value to set the FLOW_LEVEL
     */
    public void setFlowLevel(Number value) {
        setAttributeInternal(FLOWLEVEL, value);
    }

    /**
     * Gets the attribute value for FLOW_STATUS using the alias name FlowStatus.
     * @return the FLOW_STATUS
     */
    public String getFlowStatus() {
        return (String) getAttributeInternal(FLOWSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for FLOW_STATUS using the alias name FlowStatus.
     * @param value value to set the FLOW_STATUS
     */
    public void setFlowStatus(String value) {
        setAttributeInternal(FLOWSTATUS, value);
    }

    /**
     * Gets the attribute value for FLOW_WITH using the alias name FlowWith.
     * @return the FLOW_WITH
     */
    public Number getFlowWith() {
        return (Number)getAttributeInternal(FLOWWITH);
    }

    /**
     * Sets <code>value</code> as attribute value for FLOW_WITH using the alias name FlowWith.
     * @param value value to set the FLOW_WITH
     */
    public void setFlowWith(Number value) {
        setAttributeInternal(FLOWWITH, value);
    }

    /**
     * Gets the attribute value for FUNC_ID using the alias name FuncId.
     * @return the FUNC_ID
     */
    public Number getFuncId() {
        return (Number)getAttributeInternal(FUNCID);
    }

    /**
     * Sets <code>value</code> as attribute value for FUNC_ID using the alias name FuncId.
     * @param value value to set the FUNC_ID
     */
    public void setFuncId(Number value) {
        setAttributeInternal(FUNCID, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LEAD_ID using the alias name LeadId.
     * @return the LEAD_ID
     */
    public Number getLeadId() {
        return (Number)getAttributeInternal(LEADID);
    }

    /**
     * Sets <code>value</code> as attribute value for LEAD_ID using the alias name LeadId.
     * @param value value to set the LEAD_ID
     */
    public void setLeadId(Number value) {
        setAttributeInternal(LEADID, value);
    }

    /**
     * Gets the attribute value for MS_HDR_ID using the alias name MsHdrId.
     * @return the MS_HDR_ID
     */
    public Number getMsHdrId() {
        return (Number)getAttributeInternal(MSHDRID);
    }

    /**
     * Sets <code>value</code> as attribute value for MS_HDR_ID using the alias name MsHdrId.
     * @param value value to set the MS_HDR_ID
     */
    public void setMsHdrId(Number value) {
        setAttributeInternal(MSHDRID, value);
    }

    /**
     * Gets the attribute value for NET_OFFER_AMOUNT using the alias name NetOfferAmount.
     * @return the NET_OFFER_AMOUNT
     */
    public Number getNetOfferAmount() {
        return (Number)getAttributeInternal(NETOFFERAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for NET_OFFER_AMOUNT using the alias name NetOfferAmount.
     * @param value value to set the NET_OFFER_AMOUNT
     */
    public void setNetOfferAmount(Number value) {
        setAttributeInternal(NETOFFERAMOUNT, value);
    }

    /**
     * Gets the attribute value for OFFER_DATE using the alias name OfferDate.
     * @return the OFFER_DATE
     */
    public Date getOfferDate() {
        return (Date)getAttributeInternal(OFFERDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for OFFER_DATE using the alias name OfferDate.
     * @param value value to set the OFFER_DATE
     */
    public void setOfferDate(Date value) {
        setAttributeInternal(OFFERDATE, value);
    }

    /**
     * Gets the attribute value for OFFER_FROM_DATE using the alias name OfferFromDate.
     * @return the OFFER_FROM_DATE
     */
    public Date getOfferFromDate() {
        return (Date)getAttributeInternal(OFFERFROMDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for OFFER_FROM_DATE using the alias name OfferFromDate.
     * @param value value to set the OFFER_FROM_DATE
     */
    public void setOfferFromDate(Date value) {
        setAttributeInternal(OFFERFROMDATE, value);
    }

    /**
     * Gets the attribute value for OFFER_HDR_ID using the alias name OfferHdrId.
     * @return the OFFER_HDR_ID
     */
    public Number getOfferHdrId() {
        return (Number)getAttributeInternal(OFFERHDRID);
    }

    /**
     * Sets <code>value</code> as attribute value for OFFER_HDR_ID using the alias name OfferHdrId.
     * @param value value to set the OFFER_HDR_ID
     */
    public void setOfferHdrId(Number value) {
        setAttributeInternal(OFFERHDRID, value);
    }

    /**
     * Gets the attribute value for OFFER_NUMBER using the alias name OfferNumber.
     * @return the OFFER_NUMBER
     */
    public String getOfferNumber() {
        return (String) getAttributeInternal(OFFERNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for OFFER_NUMBER using the alias name OfferNumber.
     * @param value value to set the OFFER_NUMBER
     */
    public void setOfferNumber(String value) {
        setAttributeInternal(OFFERNUMBER, value);
    }

    /**
     * Gets the attribute value for OFFER_TO_DATE using the alias name OfferToDate.
     * @return the OFFER_TO_DATE
     */
    public Date getOfferToDate() {
        return (Date)getAttributeInternal(OFFERTODATE);
    }

    /**
     * Sets <code>value</code> as attribute value for OFFER_TO_DATE using the alias name OfferToDate.
     * @param value value to set the OFFER_TO_DATE
     */
    public void setOfferToDate(Date value) {
        setAttributeInternal(OFFERTODATE, value);
    }

    /**
     * Gets the attribute value for OFFER_TYPE using the alias name OfferType.
     * @return the OFFER_TYPE
     */
    public String getOfferType() {
        return (String) getAttributeInternal(OFFERTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for OFFER_TYPE using the alias name OfferType.
     * @param value value to set the OFFER_TYPE
     */
    public void setOfferType(String value) {
        setAttributeInternal(OFFERTYPE, value);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for PERFORMED_BY using the alias name PerformedBy.
     * @return the PERFORMED_BY
     */
    public Number getPerformedBy() {
        return (Number)getAttributeInternal(PERFORMEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for PERFORMED_BY using the alias name PerformedBy.
     * @param value value to set the PERFORMED_BY
     */
    public void setPerformedBy(Number value) {
        setAttributeInternal(PERFORMEDBY, value);
    }

    /**
     * Gets the attribute value for REVISION_NO using the alias name RevisionNo.
     * @return the REVISION_NO
     */
    public Number getRevisionNo() {
        return (Number)getAttributeInternal(REVISIONNO);
    }

    /**
     * Sets <code>value</code> as attribute value for REVISION_NO using the alias name RevisionNo.
     * @param value value to set the REVISION_NO
     */
    public void setRevisionNo(Number value) {
        setAttributeInternal(REVISIONNO, value);
    }

    /**
     * Gets the attribute value for SALESMAN_ID using the alias name SalesmanId.
     * @return the SALESMAN_ID
     */
    public Number getSalesmanId() {
        return (Number)getAttributeInternal(SALESMANID);
    }

    /**
     * Sets <code>value</code> as attribute value for SALESMAN_ID using the alias name SalesmanId.
     * @param value value to set the SALESMAN_ID
     */
    public void setSalesmanId(Number value) {
        setAttributeInternal(SALESMANID, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for TAX_AMOUNT using the alias name TaxAmount.
     * @return the TAX_AMOUNT
     */
    public Number getTaxAmount() {
        return (Number)getAttributeInternal(TAXAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for TAX_AMOUNT using the alias name TaxAmount.
     * @param value value to set the TAX_AMOUNT
     */
    public void setTaxAmount(Number value) {
        setAttributeInternal(TAXAMOUNT, value);
    }

    /**
     * Gets the attribute value for PL_ID using the alias name PlId.
     * @return the PL_ID
     */
    public Number getPlId() {
        return (Number)getAttributeInternal(PLID);
    }

    /**
     * Sets <code>value</code> as attribute value for PL_ID using the alias name PlId.
     * @param value value to set the PL_ID
     */
    public void setPlId(Number value) {
        setAttributeInternal(PLID, value);
    }

    /**
     * Gets the attribute value for CUSTOMER_NAME using the alias name CustomerName.
     * @return the CUSTOMER_NAME
     */
    public String getCustomerName() {
        return (String) getAttributeInternal(CUSTOMERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMER_NAME using the alias name CustomerName.
     * @param value value to set the CUSTOMER_NAME
     */
    public void setCustomerName(String value) {
        setAttributeInternal(CUSTOMERNAME, value);
    }

    /**
     * Gets the attribute value for CURRENCY using the alias name Currency.
     * @return the CURRENCY
     */
    public String getCurrency() {
        return (String) getAttributeInternal(CURRENCY);
    }

    /**
     * Sets <code>value</code> as attribute value for CURRENCY using the alias name Currency.
     * @param value value to set the CURRENCY
     */
    public void setCurrency(String value) {
        setAttributeInternal(CURRENCY, value);
    }

    /**
     * Gets the attribute value for CUSTOMER_PHONE_NO using the alias name CustomerPhoneNo.
     * @return the CUSTOMER_PHONE_NO
     */
    public String getCustomerPhoneNo() {
        return (String) getAttributeInternal(CUSTOMERPHONENO);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMER_PHONE_NO using the alias name CustomerPhoneNo.
     * @param value value to set the CUSTOMER_PHONE_NO
     */
    public void setCustomerPhoneNo(String value) {
        setAttributeInternal(CUSTOMERPHONENO, value);
    }

    /**
     * Gets the attribute value for CUSTOMER_COUNTRY using the alias name CustomerCountry.
     * @return the CUSTOMER_COUNTRY
     */
    public String getCustomerCountry() {
        return (String) getAttributeInternal(CUSTOMERCOUNTRY);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMER_COUNTRY using the alias name CustomerCountry.
     * @param value value to set the CUSTOMER_COUNTRY
     */
    public void setCustomerCountry(String value) {
        setAttributeInternal(CUSTOMERCOUNTRY, value);
    }

    /**
     * Gets the attribute value for CHECKLIST using the alias name Checklist.
     * @return the CHECKLIST
     */
    public String getChecklist() {
        return (String) getAttributeInternal(CHECKLIST);
    }

    /**
     * Sets <code>value</code> as attribute value for CHECKLIST using the alias name Checklist.
     * @param value value to set the CHECKLIST
     */
    public void setChecklist(String value) {
        setAttributeInternal(CHECKLIST, value);
    }

    /**
     * Gets the attribute value for OFFER_TOTAL using the alias name OfferTotal.
     * @return the OFFER_TOTAL
     */
    public Number getOfferTotal() {
        return (Number)getAttributeInternal(OFFERTOTAL);
    }

    /**
     * Sets <code>value</code> as attribute value for OFFER_TOTAL using the alias name OfferTotal.
     * @param value value to set the OFFER_TOTAL
     */
    public void setOfferTotal(Number value) {
        setAttributeInternal(OFFERTOTAL, value);
    }

    /**
     * Gets the attribute value for TERMS using the alias name Terms.
     * @return the TERMS
     */
    public String getTerms() {
        return (String) getAttributeInternal(TERMS);
    }

    /**
     * Sets <code>value</code> as attribute value for TERMS using the alias name Terms.
     * @param value value to set the TERMS
     */
    public void setTerms(String value) {
        setAttributeInternal(TERMS, value);
    }

    /**
     * Gets the attribute value for OBJECT_VERSION_NUMBER using the alias name ObjectVersionNumber.
     * @return the OBJECT_VERSION_NUMBER
     */
    public Number getObjectVersionNumber() {
        return (Number)getAttributeInternal(OBJECTVERSIONNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJECT_VERSION_NUMBER using the alias name ObjectVersionNumber.
     * @param value value to set the OBJECT_VERSION_NUMBER
     */
    public void setObjectVersionNumber(Number value) {
        setAttributeInternal(OBJECTVERSIONNUMBER, value);
    }

    /**
     * Gets the attribute value for USER_GRP_ID using the alias name UserGrpId.
     * @return the USER_GRP_ID
     */
    public BigDecimal getUserGrpId() {
        return (BigDecimal) getAttributeInternal(USERGRPID);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_GRP_ID using the alias name UserGrpId.
     * @param value value to set the USER_GRP_ID
     */
    public void setUserGrpId(BigDecimal value) {
        setAttributeInternal(USERGRPID, value);
    }

    /**
     * Gets the attribute value for LEASE_AGREEMENT_ID using the alias name LeaseAgreementId.
     * @return the LEASE_AGREEMENT_ID
     */
    public BigDecimal getLeaseAgreementId() {
        return (BigDecimal) getAttributeInternal(LEASEAGREEMENTID);
    }

    /**
     * Sets <code>value</code> as attribute value for LEASE_AGREEMENT_ID using the alias name LeaseAgreementId.
     * @param value value to set the LEASE_AGREEMENT_ID
     */
    public void setLeaseAgreementId(BigDecimal value) {
        setAttributeInternal(LEASEAGREEMENTID, value);
    }

    /**
     * Gets the attribute value for OFFER_FLAG using the alias name OfferFlag.
     * @return the OFFER_FLAG
     */
    public String getOfferFlag() {
        return (String) getAttributeInternal(OFFERFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for OFFER_FLAG using the alias name OfferFlag.
     * @param value value to set the OFFER_FLAG
     */
    public void setOfferFlag(String value) {
        setAttributeInternal(OFFERFLAG, value);
    }

    /**
     * Gets the attribute value for PROPERTY_ID using the alias name PropertyId.
     * @return the PROPERTY_ID
     */
    public BigDecimal getPropertyId() {
        return (BigDecimal) getAttributeInternal(PROPERTYID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROPERTY_ID using the alias name PropertyId.
     * @param value value to set the PROPERTY_ID
     */
    public void setPropertyId(BigDecimal value) {
        setAttributeInternal(PROPERTYID, value);
    }

    /**
     * Gets the attribute value for BUILDING_ID using the alias name BuildingId.
     * @return the BUILDING_ID
     */
    public BigDecimal getBuildingId() {
        return (BigDecimal) getAttributeInternal(BUILDINGID);
    }

    /**
     * Sets <code>value</code> as attribute value for BUILDING_ID using the alias name BuildingId.
     * @param value value to set the BUILDING_ID
     */
    public void setBuildingId(BigDecimal value) {
        setAttributeInternal(BUILDINGID, value);
    }
    /**
     * Gets the attribute value for LEASE_TYPE using the alias name LeaseType.
     * @return the LEASE_TYPE
     */
    public String getLeaseType() {
        return (String) getAttributeInternal(LEASETYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for LEASE_TYPE using the alias name LeaseType.
     * @param value value to set the LEASE_TYPE
     */
    public void setLeaseType(String value) {
        setAttributeInternal(LEASETYPE, value);
    }
    /**
     * Gets the attribute value for the calculated attribute LeadName.
     * @return the LeadName
     */
    public String getLeadName() {
        return (String) getAttributeInternal(LEADNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LeadName.
     * @param value value to set the  LeadName
     */
    public void setLeadName(String value) {
        setAttributeInternal(LEADNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LeadNumber.
     * @return the LeadNumber
     */
    public String getLeadNumber() {
        return (String) getAttributeInternal(LEADNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LeadNumber.
     * @param value value to set the  LeadNumber
     */
    public void setLeadNumber(String value) {
        setAttributeInternal(LEADNUMBER, value);
    }


    /**
     * Gets the attribute value for the calculated attribute Trans_LeadNumber.
     * @return the Trans_LeadNumber
     */
    public String getTrans_LeadNumber() {
        Number LeadId = null;
        String LeadName = null;
        //Check if DepartmentId is not null then get DepartmentName for that Id
        if (getLeadId() != null) {
            LeadId = getLeadId();
            //getDepartmentsVO1 is ViewAccessor of LOV ViewObject
            Row[] deptRows;
            deptRows = getLeadVA().getFilteredRows("LeadId", LeadId);
            if (deptRows.length > 0) {
                LeadName = deptRows[0].getAttribute("LeadNumber").toString();
            }
            return LeadName;

        } else {
            return (String)getAttributeInternal(TRANS_LEADNUMBER);
        }


    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_LeadNumber.
     * @param value value to set the  Trans_LeadNumber
     */
    public void setTrans_LeadNumber(String value) {
        setAttributeInternal(TRANS_LEADNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_MobileNumber.
     * @return the Trans_MobileNumber
     */
    public String getTrans_MobileNumber() {
        return (String) getAttributeInternal(TRANS_MOBILENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_MobileNumber.
     * @param value value to set the  Trans_MobileNumber
     */
    public void setTrans_MobileNumber(String value) {
        setAttributeInternal(TRANS_MOBILENUMBER, value);
    }


    /**
     * Gets the attribute value for the calculated attribute Trans_Address1.
     * @return the Trans_Address1
     */
    public String getTrans_Address1() {
        return (String) getAttributeInternal(TRANS_ADDRESS1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_Address1.
     * @param value value to set the  Trans_Address1
     */
    public void setTrans_Address1(String value) {
        setAttributeInternal(TRANS_ADDRESS1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_Address2.
     * @return the Trans_Address2
     */
    public String getTrans_Address2() {
        return (String) getAttributeInternal(TRANS_ADDRESS2);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_Address2.
     * @param value value to set the  Trans_Address2
     */
    public void setTrans_Address2(String value) {
        setAttributeInternal(TRANS_ADDRESS2, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_Address3.
     * @return the Trans_Address3
     */
    public String getTrans_Address3() {
        return (String) getAttributeInternal(TRANS_ADDRESS3);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_Address3.
     * @param value value to set the  Trans_Address3
     */
    public void setTrans_Address3(String value) {
        setAttributeInternal(TRANS_ADDRESS3, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_Address4.
     * @return the Trans_Address4
     */
    public String getTrans_Address4() {
        return (String) getAttributeInternal(TRANS_ADDRESS4);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_Address4.
     * @param value value to set the  Trans_Address4
     */
    public void setTrans_Address4(String value) {
        setAttributeInternal(TRANS_ADDRESS4, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_city.
     * @return the Trans_city
     */
    public String getTrans_city() {
        return (String) getAttributeInternal(TRANS_CITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_city.
     * @param value value to set the  Trans_city
     */
    public void setTrans_city(String value) {
        setAttributeInternal(TRANS_CITY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_country.
     * @return the Trans_country
     */
    public String getTrans_country() {
        return (String) getAttributeInternal(TRANS_COUNTRY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_country.
     * @param value value to set the  Trans_country
     */
    public void setTrans_country(String value) {
        setAttributeInternal(TRANS_COUNTRY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_Email.
     * @return the Trans_Email
     */
    public String getTrans_Email() {
        return (String) getAttributeInternal(TRANS_EMAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_Email.
     * @param value value to set the  Trans_Email
     */
    public void setTrans_Email(String value) {
        setAttributeInternal(TRANS_EMAIL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CarParkLeaseAgreIdTrans.
     * @return the CarParkLeaseAgreIdTrans
     */
    public String getCarParkLeaseAgreIdTrans() {
       String LeaseNumber=null;
        if (getCarParkLeaseAgreId()!= null) {
            Row[] deptRows;
            deptRows =
                    getofferDetailsforExtnandCancel_ROVO1().getFilteredRows("LeaseAgreementId", getCarParkLeaseAgreId());
            if (deptRows.length > 0) {
                LeaseNumber = deptRows[0].getAttribute("LeaseNumber").toString();
            }
            return LeaseNumber;
        } else {
            return (String) getAttributeInternal(CARPARKLEASEAGREIDTRANS);
        }
                       
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CarParkLeaseAgreIdTrans.
     * @param value value to set the  CarParkLeaseAgreIdTrans
     */
    public void setCarParkLeaseAgreIdTrans(String value) {
        setAttributeInternal(CARPARKLEASEAGREIDTRANS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LeaseNumber_Trans.
     * @return the LeaseNumber_Trans
     */
    public String getLeaseNumber_Trans() {
        String LeaseNumber=null;
        String LeaseAgreementId=null;
                 if (getLeaseAgreementId()!= null) {
                     Row[] deptRows;
                     deptRows =
                             getLeaseAgreement_VO1().getFilteredRows("LeaseAgreementId", getLeaseAgreementId());
                     if (deptRows.length > 0) {
                         LeaseNumber = deptRows[0].getAttribute("LeaseNumber").toString();
                         LeaseAgreementId = deptRows[0].getAttribute("LeaseAgreementId").toString();
                     }         
                     ADFContext.getCurrent().getSessionScope().put("LeaseId",
                                                                   LeaseAgreementId);
                     return LeaseNumber;
                 } else {
               
        return (String) getAttributeInternal(LEASENUMBER_TRANS);
    }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LeaseNumber_Trans.
     * @param value value to set the  LeaseNumber_Trans
     */
    public void setLeaseNumber_Trans(String value) {
        setAttributeInternal(LEASENUMBER_TRANS, value);
    }

    /**
     * Gets the attribute value for EXTENSION_DAYS using the alias name ExtensionDays.
     * @return the EXTENSION_DAYS
     */
    public String getExtensionDays() {
        return (String) getAttributeInternal(EXTENSIONDAYS);
    }

    /**
     * Sets <code>value</code> as attribute value for EXTENSION_DAYS using the alias name ExtensionDays.
     * @param value value to set the EXTENSION_DAYS
     */
    public void setExtensionDays(String value) {
        setAttributeInternal(EXTENSIONDAYS, value);
    }

    /**
     * Gets the attribute value for OFFEREXPIREDDATE using the alias name Offerexpireddate.
     * @return the OFFEREXPIREDDATE
     */
    public Date getOfferexpireddate() {
        return (Date) getAttributeInternal(OFFEREXPIREDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for OFFEREXPIREDDATE using the alias name Offerexpireddate.
     * @param value value to set the OFFEREXPIREDDATE
     */
    public void setOfferexpireddate(Date value) {
        setAttributeInternal(OFFEREXPIREDDATE, value);
    }


    /**
     * Gets the attribute value for EXPECTED_DISCOUNT using the alias name ExpectedDiscount.
     * @return the EXPECTED_DISCOUNT
     */
    public BigDecimal getExpectedDiscount() {
        return (BigDecimal) getAttributeInternal(EXPECTEDDISCOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for EXPECTED_DISCOUNT using the alias name ExpectedDiscount.
     * @param value value to set the EXPECTED_DISCOUNT
     */
    public void setExpectedDiscount(BigDecimal value) {
        setAttributeInternal(EXPECTEDDISCOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ExpectedDiscount_Trans.
     * @return the ExpectedDiscount_Trans
     */
    public String getExpectedDiscount_Trans() {
        String exptDisc=null;
        if (getExpectedDiscount()!= null) {
           exptDisc = getExpectedDiscount().toString();
            return exptDisc;
        }else{
        return (String) getAttributeInternal(EXPECTEDDISCOUNT_TRANS);
        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ExpectedDiscount_Trans.
     * @param value value to set the  ExpectedDiscount_Trans
     */
    public void setExpectedDiscount_Trans(String value) {
        setAttributeInternal(EXPECTEDDISCOUNT_TRANS, value);
    }


    /**
     * Gets the attribute value for REQUESTED_NET_RENT using the alias name RequestedNetRent.
     * @return the REQUESTED_NET_RENT
     */
    public BigDecimal getRequestedNetRent() {
        return (BigDecimal) getAttributeInternal(REQUESTEDNETRENT);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUESTED_NET_RENT using the alias name RequestedNetRent.
     * @param value value to set the REQUESTED_NET_RENT
     */
    public void setRequestedNetRent(BigDecimal value) {
        setAttributeInternal(REQUESTEDNETRENT, value);
    }

    /**
     * Gets the attribute value for OFFER_TOTAL_WITHOUT_TAX using the alias name OfferTotalWithoutTax.
     * @return the OFFER_TOTAL_WITHOUT_TAX
     */
    public BigDecimal getOfferTotalWithoutTax() {
        return (BigDecimal) getAttributeInternal(OFFERTOTALWITHOUTTAX);
    }

    /**
     * Sets <code>value</code> as attribute value for OFFER_TOTAL_WITHOUT_TAX using the alias name OfferTotalWithoutTax.
     * @param value value to set the OFFER_TOTAL_WITHOUT_TAX
     */
    public void setOfferTotalWithoutTax(BigDecimal value) {
        setAttributeInternal(OFFERTOTALWITHOUTTAX, value);
    }

    /**
     * Gets the attribute value for UNIT_INCHARGE using the alias name UnitIncharge.
     * @return the UNIT_INCHARGE
     */
    public String getUnitIncharge() {
        return (String) getAttributeInternal(UNITINCHARGE);
    }

    /**
     * Sets <code>value</code> as attribute value for UNIT_INCHARGE using the alias name UnitIncharge.
     * @param value value to set the UNIT_INCHARGE
     */
    public void setUnitIncharge(String value) {
        setAttributeInternal(UNITINCHARGE, value);
    }

    /**
     * Gets the attribute value for UNIT_OWNER using the alias name UnitOwner.
     * @return the UNIT_OWNER
     */
    public String getUnitOwner() {
        return (String) getAttributeInternal(UNITOWNER);
    }

    /**
     * Sets <code>value</code> as attribute value for UNIT_OWNER using the alias name UnitOwner.
     * @param value value to set the UNIT_OWNER
     */
    public void setUnitOwner(String value) {
        setAttributeInternal(UNITOWNER, value);
    }

    /**
     * Gets the attribute value for CAR_PARK_LEASE_AGRE_ID using the alias name CarParkLeaseAgreId.
     * @return the CAR_PARK_LEASE_AGRE_ID
     */
    public BigDecimal getCarParkLeaseAgreId() {
        return (BigDecimal) getAttributeInternal(CARPARKLEASEAGREID);
    }

    /**
     * Sets <code>value</code> as attribute value for CAR_PARK_LEASE_AGRE_ID using the alias name CarParkLeaseAgreId.
     * @param value value to set the CAR_PARK_LEASE_AGRE_ID
     */
    public void setCarParkLeaseAgreId(BigDecimal value) {
        setAttributeInternal(CARPARKLEASEAGREID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Current_Date.
     * @return the Current_Date
     */
    public Date getCurrent_Date() {
        return (Date)getAttributeInternal(CURRENT_DATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Current_Date.
     * @param value value to set the  Current_Date
     */
    public void setCurrent_Date(Date value) {
        setAttributeInternal(CURRENT_DATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DateRestriction_Trans.
     * @return the DateRestriction_Trans
     */
    public Date getDateRestriction_Trans() {
        return (Date)getAttributeInternal(DATERESTRICTION_TRANS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DateRestriction_Trans.
     * @param value value to set the  DateRestriction_Trans
     */
    public void setDateRestriction_Trans(Date value) {
        setAttributeInternal(DATERESTRICTION_TRANS, value);
    }


    /**
     * Gets the attribute value for the calculated attribute Trans_PriceListType.
     * @return the Trans_PriceListType
     */
    public String getTrans_PriceListType() {
        return (String) getAttributeInternal(TRANS_PRICELISTTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_PriceListType.
     * @param value value to set the  Trans_PriceListType
     */
    public void setTrans_PriceListType(String value) {
        setAttributeInternal(TRANS_PRICELISTTYPE, value);
    }


    /**
     * Gets the attribute value for the calculated attribute TotalTaxAmountTrans.
     * @return the TotalTaxAmountTrans
     */
    public String getTotalTaxAmountTrans() {
        return (String) getAttributeInternal(TOTALTAXAMOUNTTRANS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TotalTaxAmountTrans.
     * @param value value to set the  TotalTaxAmountTrans
     */
    public void setTotalTaxAmountTrans(String value) {
        setAttributeInternal(TOTALTAXAMOUNTTRANS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TotalBaseRAteTrans.
     * @return the TotalBaseRAteTrans
     */
    public String getTotalBaseRAteTrans() {
        return (String) getAttributeInternal(TOTALBASERATETRANS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TotalBaseRAteTrans.
     * @param value value to set the  TotalBaseRAteTrans
     */
    public void setTotalBaseRAteTrans(String value) {
        setAttributeInternal(TOTALBASERATETRANS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TotalOfferRentTrans.
     * @return the TotalOfferRentTrans
     */
    public String getTotalOfferRentTrans() {
        return (String) getAttributeInternal(TOTALOFFERRENTTRANS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TotalOfferRentTrans.
     * @param value value to set the  TotalOfferRentTrans
     */
    public void setTotalOfferRentTrans(String value) {
        setAttributeInternal(TOTALOFFERRENTTRANS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TotalDiscountsRAteTrans.
     * @return the TotalDiscountsRAteTrans
     */
    public String getTotalDiscountsRAteTrans() {
        return (String) getAttributeInternal(TOTALDISCOUNTSRATETRANS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TotalDiscountsRAteTrans.
     * @param value value to set the  TotalDiscountsRAteTrans
     */
    public void setTotalDiscountsRAteTrans(String value) {
        setAttributeInternal(TOTALDISCOUNTSRATETRANS, value);
    }


    /**
     * Gets the attribute value for the calculated attribute Trans_LeadName1.
     * @return the Trans_LeadName1
     */
    public String getTrans_LeadName1() {
        return (String) getAttributeInternal(TRANS_LEADNAME1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_LeadName1.
     * @param value value to set the  Trans_LeadName1
     */
    public void setTrans_LeadName1(String value) {
        setAttributeInternal(TRANS_LEADNAME1, value);
    }

    /**
     * Gets the attribute value for TAX_CODE using the alias name TaxCode.
     * @return the TAX_CODE
     */
    public String getTaxCode() {
        return (String) getAttributeInternal(TAXCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for TAX_CODE using the alias name TaxCode.
     * @param value value to set the TAX_CODE
     */
    public void setTaxCode(String value) {
        setAttributeInternal(TAXCODE, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link OfferDetail_VO.
     */
    public RowIterator getOfferDetail_VO() {
        return (RowIterator)getAttributeInternal(OFFERDETAIL_VO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link OfferMilestoneDetail_VO.
     */
    public RowIterator getOfferMilestoneDetail_VO() {
        return (RowIterator)getAttributeInternal(OFFERMILESTONEDETAIL_VO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link getApprovalHistoryROVo.
     */
    public RowIterator getgetApprovalHistoryROVo() {
        return (RowIterator)getAttributeInternal(GETAPPROVALHISTORYROVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link OfferDiscountFlow_VO.
     */
    public RowIterator getOfferDiscountFlow_VO() {
        return (RowIterator)getAttributeInternal(OFFERDISCOUNTFLOW_VO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LeadVA.
     */
    public RowSet getLeadVA() {
        return (RowSet)getAttributeInternal(LEADVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LeadVA_E.
     */
    public RowSet getLeadVA_E() {
        return (RowSet)getAttributeInternal(LEADVA_E);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Lookup_View_ROVA.
     */
    public RowSet getLookup_View_ROVA() {
        return (RowSet)getAttributeInternal(LOOKUP_VIEW_ROVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Lookup_View_ROVA_OffType.
     */
    public RowSet getLookup_View_ROVA_OffType() {
        return (RowSet)getAttributeInternal(LOOKUP_VIEW_ROVA_OFFTYPE);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Organizations_ROVA.
     */
    public RowSet getOrganizations_ROVA() {
        return (RowSet)getAttributeInternal(ORGANIZATIONS_ROVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> findByMileStoneNameROVA.
     */
    public RowSet getfindByMileStoneNameROVA() {
        return (RowSet)getAttributeInternal(FINDBYMILESTONENAMEROVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PlHeader_VO1.
     */
    public RowSet getPlHeader_VO1() {
        return (RowSet)getAttributeInternal(PLHEADER_VO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Lookup_View_ROVO_Terms.
     */
    public RowSet getLookup_View_ROVO_Terms() {
        return (RowSet)getAttributeInternal(LOOKUP_VIEW_ROVO_TERMS);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Lookup_View_ROVO_CheckLIst.
     */
    public RowSet getLookup_View_ROVO_CheckLIst() {
        return (RowSet)getAttributeInternal(LOOKUP_VIEW_ROVO_CHECKLIST);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LeaseAgreement_VO1.
     */
    public RowSet getLeaseAgreement_VO1() {
        return (RowSet)getAttributeInternal(LEASEAGREEMENT_VO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Lookup_View_ROVA_currency.
     */
    public RowSet getLookup_View_ROVA_currency() {
        return (RowSet)getAttributeInternal(LOOKUP_VIEW_ROVA_CURRENCY);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Lookup_View_ROVO1.
     */
    public RowSet getLookup_View_ROVO1() {
        return (RowSet)getAttributeInternal(LOOKUP_VIEW_ROVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PlHeader_VO2.
     */
    public RowSet getPlHeader_VO2() {
        return (RowSet)getAttributeInternal(PLHEADER_VO2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> UnitTypeSTA1.
     */
    public RowSet getUnitTypeSTA1() {
        return (RowSet)getAttributeInternal(UNITTYPESTA1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Lookup_View_ROVO2.
     */
    public RowSet getLookup_View_ROVO2() {
        return (RowSet)getAttributeInternal(LOOKUP_VIEW_ROVO2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> OfferDetail_VO_TotBaseRate.
     */
    public RowSet getOfferDetail_VO_TotBaseRate() {
        return (RowSet)getAttributeInternal(OFFERDETAIL_VO_TOTBASERATE);
    }

    /**
     * Gets the view accessor <code>RowSet</code> OfferDetail_VO2_Totaltax.
     */
    public RowSet getOfferDetail_VO2_Totaltax() {
        return (RowSet)getAttributeInternal(OFFERDETAIL_VO2_TOTALTAX);
    }

    /**
     * Gets the view accessor <code>RowSet</code> OfferDetail_VO_TotDsicount.
     */
    public RowSet getOfferDetail_VO_TotDsicount() {
        return (RowSet)getAttributeInternal(OFFERDETAIL_VO_TOTDSICOUNT);
    }

    /**
     * Gets the view accessor <code>RowSet</code> offerDetailsforExtnandCancel_ROVO1.
     */
    public RowSet getofferDetailsforExtnandCancel_ROVO1() {
        return (RowSet)getAttributeInternal(OFFERDETAILSFOREXTNANDCANCEL_ROVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Lookup_View_Ext.
     */
    public RowSet getLookup_View_Ext() {
        return (RowSet)getAttributeInternal(LOOKUP_VIEW_EXT);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
