package model.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 15 18:04:37 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OtherChargesHeader_VOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public OtherChargesHeader_VOImpl() {
    }
}
