package model.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 11 13:31:48 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PlHeader_VOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PlHeader_VOImpl() {
    }

    /**
     * Returns the variable value for BV_PLID.
     * @return variable value for BV_PLID
     */
    public String getBV_PLID() {
        return (String)ensureVariableManager().getVariableValue("BV_PLID");
    }

    /**
     * Sets <code>value</code> for variable BV_PLID.
     * @param value value to bind as BV_PLID
     */
    public void setBV_PLID(String value) {
        ensureVariableManager().setVariableValue("BV_PLID", value);
    }

    /**
     * Returns the variable value for ORGId.
     * @return variable value for ORGId
     */
    public String getORGId() {
        return (String)ensureVariableManager().getVariableValue("ORGId");
    }

    /**
     * Sets <code>value</code> for variable ORGId.
     * @param value value to bind as ORGId
     */
    public void setORGId(String value) {
        ensureVariableManager().setVariableValue("ORGId", value);
    }

    /**
     * Returns the variable value for BV_ACT_YN.
     * @return variable value for BV_ACT_YN
     */
    public String getBV_ACT_YN() {
        return (String)ensureVariableManager().getVariableValue("BV_ACT_YN");
    }

    /**
     * Sets <code>value</code> for variable BV_ACT_YN.
     * @param value value to bind as BV_ACT_YN
     */
    public void setBV_ACT_YN(String value) {
        ensureVariableManager().setVariableValue("BV_ACT_YN", value);
    }
}
