package model.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 12 18:56:11 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PropertyUnits_VOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PropertyUnits_VOImpl() {
    }

    /**
     * Returns the variable value for U_ID.
     * @return variable value for U_ID
     */
    public String getU_ID() {
        return (String)ensureVariableManager().getVariableValue("U_ID");
    }

    /**
     * Sets <code>value</code> for variable U_ID.
     * @param value value to bind as U_ID
     */
    public void setU_ID(String value) {
        ensureVariableManager().setVariableValue("U_ID", value);
    }
}
