package model.VO;

import java.math.BigDecimal;

import java.sql.Date;
import java.sql.Timestamp;

import model.EO.LeaseAgreement_EOImpl;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jun 17 14:04:47 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LeaseAgreement_VORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        BusinessUnit {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getBusinessUnit();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setBusinessUnit((String)value);
            }
        }
        ,
        Propertynumber {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getPropertynumber();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setPropertynumber((String)value);
            }
        }
        ,
        Buildnumber {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getBuildnumber();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setBuildnumber((String)value);
            }
        }
        ,
        UnitnumberTrans {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getUnitnumberTrans();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setUnitnumberTrans((String)value);
            }
        }
        ,
        UnitnumberDummy {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getUnitnumberDummy();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setUnitnumberDummy((String)value);
            }
        }
        ,
        BookingnoTrans {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getBookingnoTrans();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setBookingnoTrans((String)value);
            }
        }
        ,
        RecommendnoTrans {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getRecommendnoTrans();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setRecommendnoTrans((String)value);
            }
        }
        ,
        OffernoTrans {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getOffernoTrans();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setOffernoTrans((String)value);
            }
        }
        ,
        Attribute1 {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getAttribute11();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getAttribute12();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getAttribute13();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getAttribute14();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getAttribute15();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        Attribute16 {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getAttribute16();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttribute16((String)value);
            }
        }
        ,
        Attribute17 {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getAttribute17();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttribute17((String)value);
            }
        }
        ,
        Attribute18 {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getAttribute18();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttribute18((String)value);
            }
        }
        ,
        Attribute19 {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getAttribute19();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttribute19((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute20 {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getAttribute20();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttribute20((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        AttributeCategory {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getAttributeCategory();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttributeCategory((String)value);
            }
        }
        ,
        BookingId {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getBookingId();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setBookingId((BigDecimal)value);
            }
        }
        ,
        Customer {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getCustomer();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setCustomer((String)value);
            }
        }
        ,
        OfferHdrId {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getOfferHdrId();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setOfferHdrId((BigDecimal)value);
            }
        }
        ,
        CreatedBy {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setCreationDate((Timestamp)value);
            }
        }
        ,
        Description {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getDescription();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        FlowLevel {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getFlowLevel();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setFlowLevel((BigDecimal)value);
            }
        }
        ,
        FlowStatus {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getFlowStatus();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setFlowStatus((String)value);
            }
        }
        ,
        FlowWith {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getFlowWith();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setFlowWith((BigDecimal)value);
            }
        }
        ,
        FuncId {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getFuncId();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setFuncId((BigDecimal)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setLastUpdateDate((Timestamp)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setLastUpdateLogin((String)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LeaseAgreementId {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getLeaseAgreementId();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setLeaseAgreementId((BigDecimal)value);
            }
        }
        ,
        RecommendId {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getRecommendId();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setRecommendId((BigDecimal)value);
            }
        }
        ,
        Status {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getStatus();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        TenancyConDocNo {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getTenancyConDocNo();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setTenancyConDocNo((String)value);
            }
        }
        ,
        LeaseNumber {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getLeaseNumber();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setLeaseNumber((String)value);
            }
        }
        ,
        OrgId {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getOrgId();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setOrgId((BigDecimal)value);
            }
        }
        ,
        PropertyId {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getPropertyId();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setPropertyId((BigDecimal)value);
            }
        }
        ,
        UserGrpId {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getUserGrpId();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setUserGrpId((BigDecimal)value);
            }
        }
        ,
        BuildingId {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getBuildingId();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setBuildingId((BigDecimal)value);
            }
        }
        ,
        LeaseStartDate {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getLeaseStartDate();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setLeaseStartDate((Date)value);
            }
        }
        ,
        LeaseEndDate {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getLeaseEndDate();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setLeaseEndDate((Date)value);
            }
        }
        ,
        TaxCode {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getTaxCode();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setTaxCode((String)value);
            }
        }
        ,
        NoOfYears {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getNoOfYears();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setNoOfYears((BigDecimal)value);
            }
        }
        ,
        PurposeOfRent {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getPurposeOfRent();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setPurposeOfRent((String)value);
            }
        }
        ,
        ResidentialDetails {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getResidentialDetails();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setResidentialDetails((String)value);
            }
        }
        ,
        CarParkLeaseAgreId {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getCarParkLeaseAgreId();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setCarParkLeaseAgreId((BigDecimal)value);
            }
        }
        ,
        OfferTotal {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getOfferTotal();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setOfferTotal((BigDecimal)value);
            }
        }
        ,
        TotalInWords {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getTotalInWords();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setTotalInWords((String)value);
            }
        }
        ,
        IntegrationResponse {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getIntegrationResponse();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setIntegrationResponse((String)value);
            }
        }
        ,
        TenanctStatus {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getTenanctStatus();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setTenanctStatus((String)value);
            }
        }
        ,
        CustomerName_Trans {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getCustomerName_Trans();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setCustomerName_Trans((String)value);
            }
        }
        ,
        CustomerBankName_Trans {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getCustomerBankName_Trans();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setCustomerBankName_Trans((String)value);
            }
        }
        ,
        Trans_LeaseNumber {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getTrans_LeaseNumber();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setTrans_LeaseNumber((String)value);
            }
        }
        ,
        RecommendationIdTrans {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getRecommendationIdTrans();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setRecommendationIdTrans((String)value);
            }
        }
        ,
        UnitIncharge {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getUnitIncharge();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setUnitIncharge((String)value);
            }
        }
        ,
        UnitOwner {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getUnitOwner();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setUnitOwner((String)value);
            }
        }
        ,
        Booking_Milestone_VO {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getBooking_Milestone_VO();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BookingDetail_VO {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getBookingDetail_VO();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MoveInOut_VO {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getMoveInOut_VO();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ExtCanVO {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getExtCanVO();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Booking_Milestone_VO1 {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getBooking_Milestone_VO1();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Receipt_VO {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getReceipt_VO();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        getApprovalHistoryROVo {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getgetApprovalHistoryROVo();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LeaseAgree_ROVO1 {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getLeaseAgree_ROVO1();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        getLeaseDetailsForRecomROVO1 {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getgetLeaseDetailsForRecomROVO1();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Lookup_View_ROVO1 {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getLookup_View_ROVO1();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LookupDetails_ROVO1 {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getLookupDetails_ROVO1();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Lookup_View_ROVO_Tax {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getLookup_View_ROVO_Tax();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Lookup_View_RES {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getLookup_View_RES();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        getLeaseNumber1 {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getgetLeaseNumber1();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        OfferHrd_VO1 {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getOfferHrd_VO1();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Lookup_View_PurOfRent {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getLookup_View_PurOfRent();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Organizations_ROVO1 {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getOrganizations_ROVO1();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        findByPropertyName1 {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getfindByPropertyName1();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        findByBuildName1 {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getfindByBuildName1();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        findByUnitName1 {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getfindByUnitName1();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        getLeaseDetailsForRecomROVO2 {
            public Object get(LeaseAgreement_VORowImpl obj) {
                return obj.getgetLeaseDetailsForRecomROVO2();
            }

            public void put(LeaseAgreement_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(LeaseAgreement_VORowImpl object);

        public abstract void put(LeaseAgreement_VORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BUSINESSUNIT = AttributesEnum.BusinessUnit.index();
    public static final int PROPERTYNUMBER = AttributesEnum.Propertynumber.index();
    public static final int BUILDNUMBER = AttributesEnum.Buildnumber.index();
    public static final int UNITNUMBERTRANS = AttributesEnum.UnitnumberTrans.index();
    public static final int UNITNUMBERDUMMY = AttributesEnum.UnitnumberDummy.index();
    public static final int BOOKINGNOTRANS = AttributesEnum.BookingnoTrans.index();
    public static final int RECOMMENDNOTRANS = AttributesEnum.RecommendnoTrans.index();
    public static final int OFFERNOTRANS = AttributesEnum.OffernoTrans.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int ATTRIBUTE16 = AttributesEnum.Attribute16.index();
    public static final int ATTRIBUTE17 = AttributesEnum.Attribute17.index();
    public static final int ATTRIBUTE18 = AttributesEnum.Attribute18.index();
    public static final int ATTRIBUTE19 = AttributesEnum.Attribute19.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE20 = AttributesEnum.Attribute20.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTECATEGORY = AttributesEnum.AttributeCategory.index();
    public static final int BOOKINGID = AttributesEnum.BookingId.index();
    public static final int CUSTOMER = AttributesEnum.Customer.index();
    public static final int OFFERHDRID = AttributesEnum.OfferHdrId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int FLOWLEVEL = AttributesEnum.FlowLevel.index();
    public static final int FLOWSTATUS = AttributesEnum.FlowStatus.index();
    public static final int FLOWWITH = AttributesEnum.FlowWith.index();
    public static final int FUNCID = AttributesEnum.FuncId.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LEASEAGREEMENTID = AttributesEnum.LeaseAgreementId.index();
    public static final int RECOMMENDID = AttributesEnum.RecommendId.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int TENANCYCONDOCNO = AttributesEnum.TenancyConDocNo.index();
    public static final int LEASENUMBER = AttributesEnum.LeaseNumber.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int PROPERTYID = AttributesEnum.PropertyId.index();
    public static final int USERGRPID = AttributesEnum.UserGrpId.index();
    public static final int BUILDINGID = AttributesEnum.BuildingId.index();
    public static final int LEASESTARTDATE = AttributesEnum.LeaseStartDate.index();
    public static final int LEASEENDDATE = AttributesEnum.LeaseEndDate.index();
    public static final int TAXCODE = AttributesEnum.TaxCode.index();
    public static final int NOOFYEARS = AttributesEnum.NoOfYears.index();
    public static final int PURPOSEOFRENT = AttributesEnum.PurposeOfRent.index();
    public static final int RESIDENTIALDETAILS = AttributesEnum.ResidentialDetails.index();
    public static final int CARPARKLEASEAGREID = AttributesEnum.CarParkLeaseAgreId.index();
    public static final int OFFERTOTAL = AttributesEnum.OfferTotal.index();
    public static final int TOTALINWORDS = AttributesEnum.TotalInWords.index();
    public static final int INTEGRATIONRESPONSE = AttributesEnum.IntegrationResponse.index();
    public static final int TENANCTSTATUS = AttributesEnum.TenanctStatus.index();
    public static final int CUSTOMERNAME_TRANS = AttributesEnum.CustomerName_Trans.index();
    public static final int CUSTOMERBANKNAME_TRANS = AttributesEnum.CustomerBankName_Trans.index();
    public static final int TRANS_LEASENUMBER = AttributesEnum.Trans_LeaseNumber.index();
    public static final int RECOMMENDATIONIDTRANS = AttributesEnum.RecommendationIdTrans.index();
    public static final int UNITINCHARGE = AttributesEnum.UnitIncharge.index();
    public static final int UNITOWNER = AttributesEnum.UnitOwner.index();
    public static final int BOOKING_MILESTONE_VO = AttributesEnum.Booking_Milestone_VO.index();
    public static final int BOOKINGDETAIL_VO = AttributesEnum.BookingDetail_VO.index();
    public static final int MOVEINOUT_VO = AttributesEnum.MoveInOut_VO.index();
    public static final int EXTCANVO = AttributesEnum.ExtCanVO.index();
    public static final int BOOKING_MILESTONE_VO1 = AttributesEnum.Booking_Milestone_VO1.index();
    public static final int RECEIPT_VO = AttributesEnum.Receipt_VO.index();
    public static final int GETAPPROVALHISTORYROVO = AttributesEnum.getApprovalHistoryROVo.index();
    public static final int LEASEAGREE_ROVO1 = AttributesEnum.LeaseAgree_ROVO1.index();
    public static final int GETLEASEDETAILSFORRECOMROVO1 = AttributesEnum.getLeaseDetailsForRecomROVO1.index();
    public static final int LOOKUP_VIEW_ROVO1 = AttributesEnum.Lookup_View_ROVO1.index();
    public static final int LOOKUPDETAILS_ROVO1 = AttributesEnum.LookupDetails_ROVO1.index();
    public static final int LOOKUP_VIEW_ROVO_TAX = AttributesEnum.Lookup_View_ROVO_Tax.index();
    public static final int LOOKUP_VIEW_RES = AttributesEnum.Lookup_View_RES.index();
    public static final int GETLEASENUMBER1 = AttributesEnum.getLeaseNumber1.index();
    public static final int OFFERHRD_VO1 = AttributesEnum.OfferHrd_VO1.index();
    public static final int LOOKUP_VIEW_PUROFRENT = AttributesEnum.Lookup_View_PurOfRent.index();
    public static final int ORGANIZATIONS_ROVO1 = AttributesEnum.Organizations_ROVO1.index();
    public static final int FINDBYPROPERTYNAME1 = AttributesEnum.findByPropertyName1.index();
    public static final int FINDBYBUILDNAME1 = AttributesEnum.findByBuildName1.index();
    public static final int FINDBYUNITNAME1 = AttributesEnum.findByUnitName1.index();
    public static final int GETLEASEDETAILSFORRECOMROVO2 = AttributesEnum.getLeaseDetailsForRecomROVO2.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LeaseAgreement_VORowImpl() {
    }

    /**
     * Gets LeaseAgreement_EO entity object.
     * @return the LeaseAgreement_EO
     */
    public LeaseAgreement_EOImpl getLeaseAgreement_EO() {
        return (LeaseAgreement_EOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for the calculated attribute BusinessUnit.
     * @return the BusinessUnit
     */
    public String getBusinessUnit() {
        return (String) getAttributeInternal(BUSINESSUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BusinessUnit.
     * @param value value to set the  BusinessUnit
     */
    public void setBusinessUnit(String value) {
        setAttributeInternal(BUSINESSUNIT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Propertynumber.
     * @return the Propertynumber
     */
    public String getPropertynumber() {
        return (String) getAttributeInternal(PROPERTYNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Propertynumber.
     * @param value value to set the  Propertynumber
     */
    public void setPropertynumber(String value) {
        setAttributeInternal(PROPERTYNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Buildnumber.
     * @return the Buildnumber
     */
    public String getBuildnumber() {
        return (String) getAttributeInternal(BUILDNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Buildnumber.
     * @param value value to set the  Buildnumber
     */
    public void setBuildnumber(String value) {
        setAttributeInternal(BUILDNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute UnitnumberTrans.
     * @return the UnitnumberTrans
     */
    public String getUnitnumberTrans() {
        return (String) getAttributeInternal(UNITNUMBERTRANS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UnitnumberTrans.
     * @param value value to set the  UnitnumberTrans
     */
    public void setUnitnumberTrans(String value) {
        setAttributeInternal(UNITNUMBERTRANS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute UnitnumberDummy.
     * @return the UnitnumberDummy
     */
    public String getUnitnumberDummy() {
        return (String) getAttributeInternal(UNITNUMBERDUMMY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UnitnumberDummy.
     * @param value value to set the  UnitnumberDummy
     */
    public void setUnitnumberDummy(String value) {
        setAttributeInternal(UNITNUMBERDUMMY, value);
    }


    /**
     * Gets the attribute value for the calculated attribute BookingnoTrans.
     * @return the BookingnoTrans
     */
    public String getBookingnoTrans() {
        return (String) getAttributeInternal(BOOKINGNOTRANS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BookingnoTrans.
     * @param value value to set the  BookingnoTrans
     */
    public void setBookingnoTrans(String value) {
        setAttributeInternal(BOOKINGNOTRANS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RecommendnoTrans.
     * @return the RecommendnoTrans
     */
    public String getRecommendnoTrans() {
        return (String) getAttributeInternal(RECOMMENDNOTRANS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RecommendnoTrans.
     * @param value value to set the  RecommendnoTrans
     */
    public void setRecommendnoTrans(String value) {
        setAttributeInternal(RECOMMENDNOTRANS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OffernoTrans.
     * @return the OffernoTrans
     */
    public String getOffernoTrans() {
        return (String) getAttributeInternal(OFFERNOTRANS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OffernoTrans.
     * @param value value to set the  OffernoTrans
     */
    public void setOffernoTrans(String value) {
        setAttributeInternal(OFFERNOTRANS, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @return the ATTRIBUTE11
     */
    public String getAttribute11() {
        return (String) getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @param value value to set the ATTRIBUTE11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @return the ATTRIBUTE12
     */
    public String getAttribute12() {
        return (String) getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @param value value to set the ATTRIBUTE12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @return the ATTRIBUTE13
     */
    public String getAttribute13() {
        return (String) getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @param value value to set the ATTRIBUTE13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @return the ATTRIBUTE14
     */
    public String getAttribute14() {
        return (String) getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @param value value to set the ATTRIBUTE14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @return the ATTRIBUTE15
     */
    public String getAttribute15() {
        return (String) getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @param value value to set the ATTRIBUTE15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE16 using the alias name Attribute16.
     * @return the ATTRIBUTE16
     */
    public String getAttribute16() {
        return (String) getAttributeInternal(ATTRIBUTE16);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE16 using the alias name Attribute16.
     * @param value value to set the ATTRIBUTE16
     */
    public void setAttribute16(String value) {
        setAttributeInternal(ATTRIBUTE16, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE17 using the alias name Attribute17.
     * @return the ATTRIBUTE17
     */
    public String getAttribute17() {
        return (String) getAttributeInternal(ATTRIBUTE17);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE17 using the alias name Attribute17.
     * @param value value to set the ATTRIBUTE17
     */
    public void setAttribute17(String value) {
        setAttributeInternal(ATTRIBUTE17, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE18 using the alias name Attribute18.
     * @return the ATTRIBUTE18
     */
    public String getAttribute18() {
        return (String) getAttributeInternal(ATTRIBUTE18);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE18 using the alias name Attribute18.
     * @param value value to set the ATTRIBUTE18
     */
    public void setAttribute18(String value) {
        setAttributeInternal(ATTRIBUTE18, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE19 using the alias name Attribute19.
     * @return the ATTRIBUTE19
     */
    public String getAttribute19() {
        return (String) getAttributeInternal(ATTRIBUTE19);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE19 using the alias name Attribute19.
     * @param value value to set the ATTRIBUTE19
     */
    public void setAttribute19(String value) {
        setAttributeInternal(ATTRIBUTE19, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE20 using the alias name Attribute20.
     * @return the ATTRIBUTE20
     */
    public String getAttribute20() {
        return (String) getAttributeInternal(ATTRIBUTE20);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE20 using the alias name Attribute20.
     * @param value value to set the ATTRIBUTE20
     */
    public void setAttribute20(String value) {
        setAttributeInternal(ATTRIBUTE20, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @return the ATTRIBUTE_CATEGORY
     */
    public String getAttributeCategory() {
        return (String) getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @param value value to set the ATTRIBUTE_CATEGORY
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**
     * Gets the attribute value for BOOKING_ID using the alias name BookingId.
     * @return the BOOKING_ID
     */
    public BigDecimal getBookingId() {
        return (BigDecimal) getAttributeInternal(BOOKINGID);
    }

    /**
     * Sets <code>value</code> as attribute value for BOOKING_ID using the alias name BookingId.
     * @param value value to set the BOOKING_ID
     */
    public void setBookingId(BigDecimal value) {
        setAttributeInternal(BOOKINGID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Customer.
     * @return the Customer
     */
    public String getCustomer() {
        return (String) getAttributeInternal(CUSTOMER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Customer.
     * @param value value to set the  Customer
     */
    public void setCustomer(String value) {
        setAttributeInternal(CUSTOMER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OfferHdrId.
     * @return the OfferHdrId
     */
    public BigDecimal getOfferHdrId() {
        return (BigDecimal) getAttributeInternal(OFFERHDRID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OfferHdrId.
     * @param value value to set the  OfferHdrId
     */
    public void setOfferHdrId(BigDecimal value) {
        setAttributeInternal(OFFERHDRID, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for DESCRIPTION using the alias name Description.
     * @return the DESCRIPTION
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for DESCRIPTION using the alias name Description.
     * @param value value to set the DESCRIPTION
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for FLOW_LEVEL using the alias name FlowLevel.
     * @return the FLOW_LEVEL
     */
    public BigDecimal getFlowLevel() {
        return (BigDecimal) getAttributeInternal(FLOWLEVEL);
    }

    /**
     * Sets <code>value</code> as attribute value for FLOW_LEVEL using the alias name FlowLevel.
     * @param value value to set the FLOW_LEVEL
     */
    public void setFlowLevel(BigDecimal value) {
        setAttributeInternal(FLOWLEVEL, value);
    }

    /**
     * Gets the attribute value for FLOW_STATUS using the alias name FlowStatus.
     * @return the FLOW_STATUS
     */
    public String getFlowStatus() {
        return (String) getAttributeInternal(FLOWSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for FLOW_STATUS using the alias name FlowStatus.
     * @param value value to set the FLOW_STATUS
     */
    public void setFlowStatus(String value) {
        setAttributeInternal(FLOWSTATUS, value);
    }

    /**
     * Gets the attribute value for FLOW_WITH using the alias name FlowWith.
     * @return the FLOW_WITH
     */
    public BigDecimal getFlowWith() {
        return (BigDecimal) getAttributeInternal(FLOWWITH);
    }

    /**
     * Sets <code>value</code> as attribute value for FLOW_WITH using the alias name FlowWith.
     * @param value value to set the FLOW_WITH
     */
    public void setFlowWith(BigDecimal value) {
        setAttributeInternal(FLOWWITH, value);
    }

    /**
     * Gets the attribute value for FUNC_ID using the alias name FuncId.
     * @return the FUNC_ID
     */
    public BigDecimal getFuncId() {
        return (BigDecimal) getAttributeInternal(FUNCID);
    }

    /**
     * Sets <code>value</code> as attribute value for FUNC_ID using the alias name FuncId.
     * @param value value to set the FUNC_ID
     */
    public void setFuncId(BigDecimal value) {
        setAttributeInternal(FUNCID, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LEASE_AGREEMENT_ID using the alias name LeaseAgreementId.
     * @return the LEASE_AGREEMENT_ID
     */
    public BigDecimal getLeaseAgreementId() {
        return (BigDecimal) getAttributeInternal(LEASEAGREEMENTID);
    }

    /**
     * Sets <code>value</code> as attribute value for LEASE_AGREEMENT_ID using the alias name LeaseAgreementId.
     * @param value value to set the LEASE_AGREEMENT_ID
     */
    public void setLeaseAgreementId(BigDecimal value) {
        setAttributeInternal(LEASEAGREEMENTID, value);
    }

    /**
     * Gets the attribute value for RECOMMEND_ID using the alias name RecommendId.
     * @return the RECOMMEND_ID
     */
    public BigDecimal getRecommendId() {
        return (BigDecimal) getAttributeInternal(RECOMMENDID);
    }

    /**
     * Sets <code>value</code> as attribute value for RECOMMEND_ID using the alias name RecommendId.
     * @param value value to set the RECOMMEND_ID
     */
    public void setRecommendId(BigDecimal value) {
        setAttributeInternal(RECOMMENDID, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for TENANCY_CON_DOC_NO using the alias name TenancyConDocNo.
     * @return the TENANCY_CON_DOC_NO
     */
    public String getTenancyConDocNo() {
        return (String) getAttributeInternal(TENANCYCONDOCNO);
    }

    /**
     * Sets <code>value</code> as attribute value for TENANCY_CON_DOC_NO using the alias name TenancyConDocNo.
     * @param value value to set the TENANCY_CON_DOC_NO
     */
    public void setTenancyConDocNo(String value) {
        setAttributeInternal(TENANCYCONDOCNO, value);
    }

    /**
     * Gets the attribute value for LEASE_NUMBER using the alias name LeaseNumber.
     * @return the LEASE_NUMBER
     */
    public String getLeaseNumber() {
        return (String) getAttributeInternal(LEASENUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for LEASE_NUMBER using the alias name LeaseNumber.
     * @param value value to set the LEASE_NUMBER
     */
    public void setLeaseNumber(String value) {
        setAttributeInternal(LEASENUMBER, value);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public BigDecimal getOrgId() {
        return (BigDecimal) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(BigDecimal value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for PROPERTY_ID using the alias name PropertyId.
     * @return the PROPERTY_ID
     */
    public BigDecimal getPropertyId() {
        return (BigDecimal) getAttributeInternal(PROPERTYID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROPERTY_ID using the alias name PropertyId.
     * @param value value to set the PROPERTY_ID
     */
    public void setPropertyId(BigDecimal value) {
        setAttributeInternal(PROPERTYID, value);
    }

    /**
     * Gets the attribute value for USER_GRP_ID using the alias name UserGrpId.
     * @return the USER_GRP_ID
     */
    public BigDecimal getUserGrpId() {
        return (BigDecimal) getAttributeInternal(USERGRPID);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_GRP_ID using the alias name UserGrpId.
     * @param value value to set the USER_GRP_ID
     */
    public void setUserGrpId(BigDecimal value) {
        setAttributeInternal(USERGRPID, value);
    }

    /**
     * Gets the attribute value for BUILDING_ID using the alias name BuildingId.
     * @return the BUILDING_ID
     */
    public BigDecimal getBuildingId() {
        return (BigDecimal) getAttributeInternal(BUILDINGID);
    }

    /**
     * Sets <code>value</code> as attribute value for BUILDING_ID using the alias name BuildingId.
     * @param value value to set the BUILDING_ID
     */
    public void setBuildingId(BigDecimal value) {
        setAttributeInternal(BUILDINGID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CustomerName_Trans.
     * @return the CustomerName_Trans
     */
    public String getCustomerName_Trans() {
        return (String) getAttributeInternal(CUSTOMERNAME_TRANS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CustomerName_Trans.
     * @param value value to set the  CustomerName_Trans
     */
    public void setCustomerName_Trans(String value) {
        setAttributeInternal(CUSTOMERNAME_TRANS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CustomerBankName_Trans.
     * @return the CustomerBankName_Trans
     */
    public String getCustomerBankName_Trans() {
        return (String) getAttributeInternal(CUSTOMERBANKNAME_TRANS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CustomerBankName_Trans.
     * @param value value to set the  CustomerBankName_Trans
     */
    public void setCustomerBankName_Trans(String value) {
        setAttributeInternal(CUSTOMERBANKNAME_TRANS, value);
    }


    /**
     * Gets the attribute value for NO_OF_YEARS using the alias name NoOfYears.
     * @return the NO_OF_YEARS
     */
    public BigDecimal getNoOfYears() {
        return (BigDecimal) getAttributeInternal(NOOFYEARS);
    }

    /**
     * Sets <code>value</code> as attribute value for NO_OF_YEARS using the alias name NoOfYears.
     * @param value value to set the NO_OF_YEARS
     */
    public void setNoOfYears(BigDecimal value) {
        setAttributeInternal(NOOFYEARS, value);
    }

    /**
     * Gets the attribute value for PURPOSE_OF_RENT using the alias name PurposeOfRent.
     * @return the PURPOSE_OF_RENT
     */
    public String getPurposeOfRent() {
        return (String) getAttributeInternal(PURPOSEOFRENT);
    }

    /**
     * Sets <code>value</code> as attribute value for PURPOSE_OF_RENT using the alias name PurposeOfRent.
     * @param value value to set the PURPOSE_OF_RENT
     */
    public void setPurposeOfRent(String value) {
        setAttributeInternal(PURPOSEOFRENT, value);
    }

    /**
     * Gets the attribute value for RESIDENTIAL_DETAILS using the alias name ResidentialDetails.
     * @return the RESIDENTIAL_DETAILS
     */
    public String getResidentialDetails() {
        return (String) getAttributeInternal(RESIDENTIALDETAILS);
    }

    /**
     * Sets <code>value</code> as attribute value for RESIDENTIAL_DETAILS using the alias name ResidentialDetails.
     * @param value value to set the RESIDENTIAL_DETAILS
     */
    public void setResidentialDetails(String value) {
        setAttributeInternal(RESIDENTIALDETAILS, value);
    }

    /**
     * Gets the attribute value for CAR_PARK_LEASE_AGRE_ID using the alias name CarParkLeaseAgreId.
     * @return the CAR_PARK_LEASE_AGRE_ID
     */
    public BigDecimal getCarParkLeaseAgreId() {
        return (BigDecimal) getAttributeInternal(CARPARKLEASEAGREID);
    }

    /**
     * Sets <code>value</code> as attribute value for CAR_PARK_LEASE_AGRE_ID using the alias name CarParkLeaseAgreId.
     * @param value value to set the CAR_PARK_LEASE_AGRE_ID
     */
    public void setCarParkLeaseAgreId(BigDecimal value) {
        setAttributeInternal(CARPARKLEASEAGREID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_LeaseNumber.
     * @return the Trans_LeaseNumber
     */
    public String getTrans_LeaseNumber() {
        return (String) getAttributeInternal(TRANS_LEASENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_LeaseNumber.
     * @param value value to set the  Trans_LeaseNumber
     */
    public void setTrans_LeaseNumber(String value) {
        setAttributeInternal(TRANS_LEASENUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RecommendationIdTrans.
     * @return the RecommendationIdTrans
     */
    public String getRecommendationIdTrans() {
        Number RecommendId = null;
        String RecommendNumber = null;
        //Check if DepartmentId is not null then get DepartmentName for that Id
        if (getRecommendId() != null) {
            RecommendId = getRecommendId();
            //getDepartmentsVO1 is ViewAccessor of LOV ViewObject
            Row[] deptRows;
            deptRows = getgetLeaseDetailsForRecomROVO1().getFilteredRows("RecommendId", RecommendId);
            if (deptRows.length > 0) {
                RecommendNumber =
                        deptRows[0].getAttribute("RecommendNumber").toString();
            }
            return RecommendNumber;

        } else {
            return (String) getAttributeInternal(RECOMMENDATIONIDTRANS);
        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RecommendationIdTrans.
     * @param value value to set the  RecommendationIdTrans
     */
    public void setRecommendationIdTrans(String value) {
        setAttributeInternal(RECOMMENDATIONIDTRANS, value);
    }

    /**
     * Gets the attribute value for UNIT_INCHARGE using the alias name UnitIncharge.
     * @return the UNIT_INCHARGE
     */
    public String getUnitIncharge() {
        return (String) getAttributeInternal(UNITINCHARGE);
    }

    /**
     * Sets <code>value</code> as attribute value for UNIT_INCHARGE using the alias name UnitIncharge.
     * @param value value to set the UNIT_INCHARGE
     */
    public void setUnitIncharge(String value) {
        setAttributeInternal(UNITINCHARGE, value);
    }

    /**
     * Gets the attribute value for UNIT_OWNER using the alias name UnitOwner.
     * @return the UNIT_OWNER
     */
    public String getUnitOwner() {
        return (String) getAttributeInternal(UNITOWNER);
    }

    /**
     * Sets <code>value</code> as attribute value for UNIT_OWNER using the alias name UnitOwner.
     * @param value value to set the UNIT_OWNER
     */
    public void setUnitOwner(String value) {
        setAttributeInternal(UNITOWNER, value);
    }

    /**
     * Gets the attribute value for INTEGRATION_RESPONSE using the alias name IntegrationResponse.
     * @return the INTEGRATION_RESPONSE
     */
    public String getIntegrationResponse() {
        return (String) getAttributeInternal(INTEGRATIONRESPONSE);
    }

    /**
     * Sets <code>value</code> as attribute value for INTEGRATION_RESPONSE using the alias name IntegrationResponse.
     * @param value value to set the INTEGRATION_RESPONSE
     */
    public void setIntegrationResponse(String value) {
        setAttributeInternal(INTEGRATIONRESPONSE, value);
    }

    /**
     * Gets the attribute value for TENANCT_STATUS using the alias name TenanctStatus.
     * @return the TENANCT_STATUS
     */
    public String getTenanctStatus() {
        return (String) getAttributeInternal(TENANCTSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for TENANCT_STATUS using the alias name TenanctStatus.
     * @param value value to set the TENANCT_STATUS
     */
    public void setTenanctStatus(String value) {
        setAttributeInternal(TENANCTSTATUS, value);
    }

    /**
     * Gets the attribute value for OFFER_TOTAL using the alias name OfferTotal.
     * @return the OFFER_TOTAL
     */
    public BigDecimal getOfferTotal() {
        return (BigDecimal) getAttributeInternal(OFFERTOTAL);
    }

    /**
     * Sets <code>value</code> as attribute value for OFFER_TOTAL using the alias name OfferTotal.
     * @param value value to set the OFFER_TOTAL
     */
    public void setOfferTotal(BigDecimal value) {
        setAttributeInternal(OFFERTOTAL, value);
    }

    /**
     * Gets the attribute value for TOTAL_IN_WORDS using the alias name TotalInWords.
     * @return the TOTAL_IN_WORDS
     */
    public String getTotalInWords() {
        return (String) getAttributeInternal(TOTALINWORDS);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_IN_WORDS using the alias name TotalInWords.
     * @param value value to set the TOTAL_IN_WORDS
     */
    public void setTotalInWords(String value) {
        setAttributeInternal(TOTALINWORDS, value);
    }

    /**
     * Gets the attribute value for TAX_CODE using the alias name TaxCode.
     * @return the TAX_CODE
     */
    public String getTaxCode() {
        return (String) getAttributeInternal(TAXCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for TAX_CODE using the alias name TaxCode.
     * @param value value to set the TAX_CODE
     */
    public void setTaxCode(String value) {
        setAttributeInternal(TAXCODE, value);
    }

    /**
     * Gets the attribute value for LEASE_END_DATE using the alias name LeaseEndDate.
     * @return the LEASE_END_DATE
     */
    public Date getLeaseEndDate() {
        return (Date) getAttributeInternal(LEASEENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LEASE_END_DATE using the alias name LeaseEndDate.
     * @param value value to set the LEASE_END_DATE
     */
    public void setLeaseEndDate(Date value) {
        setAttributeInternal(LEASEENDDATE, value);
    }

    /**
     * Gets the attribute value for LEASE_START_DATE using the alias name LeaseStartDate.
     * @return the LEASE_START_DATE
     */
    public Date getLeaseStartDate() {
        return (Date) getAttributeInternal(LEASESTARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LEASE_START_DATE using the alias name LeaseStartDate.
     * @param value value to set the LEASE_START_DATE
     */
    public void setLeaseStartDate(Date value) {
        setAttributeInternal(LEASESTARTDATE, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link Booking_Milestone_VO.
     */
    public RowIterator getBooking_Milestone_VO() {
        return (RowIterator)getAttributeInternal(BOOKING_MILESTONE_VO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link BookingDetail_VO.
     */
    public RowIterator getBookingDetail_VO() {
        return (RowIterator)getAttributeInternal(BOOKINGDETAIL_VO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link MoveInOut_VO.
     */
    public RowIterator getMoveInOut_VO() {
        return (RowIterator)getAttributeInternal(MOVEINOUT_VO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ExtCanVO.
     */
    public RowIterator getExtCanVO() {
        return (RowIterator)getAttributeInternal(EXTCANVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link Booking_Milestone_VO1.
     */
    public RowIterator getBooking_Milestone_VO1() {
        return (RowIterator)getAttributeInternal(BOOKING_MILESTONE_VO1);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link Receipt_VO.
     */
    public RowIterator getReceipt_VO() {
        return (RowIterator)getAttributeInternal(RECEIPT_VO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link getApprovalHistoryROVo.
     */
    public RowIterator getgetApprovalHistoryROVo() {
        return (RowIterator)getAttributeInternal(GETAPPROVALHISTORYROVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LeaseAgree_ROVO1.
     */
    public RowSet getLeaseAgree_ROVO1() {
        return (RowSet)getAttributeInternal(LEASEAGREE_ROVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> getLeaseDetailsForRecomROVO1.
     */
    public RowSet getgetLeaseDetailsForRecomROVO1() {
        return (RowSet)getAttributeInternal(GETLEASEDETAILSFORRECOMROVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Lookup_View_ROVO1.
     */
    public RowSet getLookup_View_ROVO1() {
        return (RowSet)getAttributeInternal(LOOKUP_VIEW_ROVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LookupDetails_ROVO1.
     */
    public RowSet getLookupDetails_ROVO1() {
        return (RowSet)getAttributeInternal(LOOKUPDETAILS_ROVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Lookup_View_ROVO_Tax.
     */
    public RowSet getLookup_View_ROVO_Tax() {
        return (RowSet)getAttributeInternal(LOOKUP_VIEW_ROVO_TAX);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Lookup_View_RES.
     */
    public RowSet getLookup_View_RES() {
        return (RowSet)getAttributeInternal(LOOKUP_VIEW_RES);
    }


    /**
     * Gets the view accessor <code>RowSet</code> getLeaseNumber1.
     */
    public RowSet getgetLeaseNumber1() {
        return (RowSet)getAttributeInternal(GETLEASENUMBER1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> OfferHrd_VO1.
     */
    public RowSet getOfferHrd_VO1() {
        return (RowSet)getAttributeInternal(OFFERHRD_VO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Lookup_View_PurOfRent.
     */
    public RowSet getLookup_View_PurOfRent() {
        return (RowSet)getAttributeInternal(LOOKUP_VIEW_PUROFRENT);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Organizations_ROVO1.
     */
    public RowSet getOrganizations_ROVO1() {
        return (RowSet)getAttributeInternal(ORGANIZATIONS_ROVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> findByPropertyName1.
     */
    public RowSet getfindByPropertyName1() {
        return (RowSet)getAttributeInternal(FINDBYPROPERTYNAME1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> findByBuildName1.
     */
    public RowSet getfindByBuildName1() {
        return (RowSet)getAttributeInternal(FINDBYBUILDNAME1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> findByUnitName1.
     */
    public RowSet getfindByUnitName1() {
        return (RowSet)getAttributeInternal(FINDBYUNITNAME1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> getLeaseDetailsForRecomROVO2.
     */
    public RowSet getgetLeaseDetailsForRecomROVO2() {
        return (RowSet)getAttributeInternal(GETLEASEDETAILSFORRECOMROVO2);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
