package model.ROVO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Mar 24 20:02:36 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SearchRecommendationRoVoImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SearchRecommendationRoVoImpl() {
    }


    /**
     * Returns the variable value for p_milestoneName.
     * @return variable value for p_milestoneName
     */
    public String getp_milestoneName() {
        return (String)ensureVariableManager().getVariableValue("p_milestoneName");
    }

    /**
     * Sets <code>value</code> for variable p_milestoneName.
     * @param value value to bind as p_milestoneName
     */
    public void setp_milestoneName(String value) {
        ensureVariableManager().setVariableValue("p_milestoneName", value);
    }

    /**
     * Returns the variable value for b_unitNumDummy.
     * @return variable value for b_unitNumDummy
     */
    public String getb_unitNumDummy() {
        return (String)ensureVariableManager().getVariableValue("b_unitNumDummy");
    }

    /**
     * Sets <code>value</code> for variable b_unitNumDummy.
     * @param value value to bind as b_unitNumDummy
     */
    public void setb_unitNumDummy(String value) {
        ensureVariableManager().setVariableValue("b_unitNumDummy", value);
    }

    /**
     * Returns the variable value for b_unitNumTrans.
     * @return variable value for b_unitNumTrans
     */
    public String getb_unitNumTrans() {
        return (String)ensureVariableManager().getVariableValue("b_unitNumTrans");
    }

    /**
     * Sets <code>value</code> for variable b_unitNumTrans.
     * @param value value to bind as b_unitNumTrans
     */
    public void setb_unitNumTrans(String value) {
        ensureVariableManager().setVariableValue("b_unitNumTrans", value);
    }

    /**
     * Returns the bind variable value for P_GRP_ID.
     * @return bind variable value for P_GRP_ID
     */
    public String getP_GRP_ID() {
        return (String)getNamedWhereClauseParam("P_GRP_ID");
    }

    /**
     * Sets <code>value</code> for bind variable P_GRP_ID.
     * @param value value to bind as P_GRP_ID
     */
    public void setP_GRP_ID(String value) {
        setNamedWhereClauseParam("P_GRP_ID", value);
    }
}
