package model.AM.client;

import model.AM.common.ExtensionCancellation_AM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jul 15 14:24:18 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ExtensionCancellation_AMClient extends ApplicationModuleImpl implements ExtensionCancellation_AM {
    /**
     * This is the default constructor (do not remove).
     */
    public ExtensionCancellation_AMClient() {
    }

    public String UpdateOfferAndLeaseDate(String bookingid, String extnid,
                                          String userId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"UpdateOfferAndLeaseDate",new String [] {"java.lang.String","java.lang.String","java.lang.String"},new Object[] {bookingid, extnid, userId});
        return (String)_ret;
    }

    public String invokeLocationName(String b_lease_id) {
        Object _ret =
            this.riInvokeExportedMethod(this,"invokeLocationName",new String [] {"java.lang.String"},new Object[] {b_lease_id});
        return (String)_ret;
    }
}
