package model.AM.client;

import model.AM.common.LeaseAgreement_AM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 12 00:22:16 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LeaseAgreement_AMClient extends ApplicationModuleImpl implements LeaseAgreement_AM {
    /**
     * This is the default constructor (do not remove).
     */
    public LeaseAgreement_AMClient() {
    }


    public String getGLCodeCombination(String pBusinessunitId,
                                       String pChargeType, String pUnitId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getGLCodeCombination",new String [] {"java.lang.String","java.lang.String","java.lang.String"},new Object[] {pBusinessunitId, pChargeType, pUnitId});
        return (String)_ret;
    }

    public String getARInvoiceTrxDetails(String pLeaseNo, String pChargeTyp,
                                         String pCustomerTrxId,
                                         String pCustomerTrxNo) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getARInvoiceTrxDetails",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {pLeaseNo, pChargeTyp, pCustomerTrxId, pCustomerTrxNo});
        return (String)_ret;
    }

    public String getCodeSegmentCombination(String pBusinessUnitId,
                                            String pChargeType,
                                            String pUnitId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getCodeSegmentCombination",new String [] {"java.lang.String","java.lang.String","java.lang.String"},new Object[] {pBusinessUnitId, pChargeType, pUnitId});
        return (String)_ret;
    }

    public String autoRoffer(String offerHdrId, String leaseId,
                             String userName) {
        Object _ret =
            this.riInvokeExportedMethod(this,"autoRoffer",new String [] {"java.lang.String","java.lang.String","java.lang.String"},new Object[] {offerHdrId, leaseId, userName});
        return (String)_ret;
    }

    public String autoSoffer(String offerHdrId, String leaseId,
                             String userName) {
        Object _ret =
            this.riInvokeExportedMethod(this,"autoSoffer",new String [] {"java.lang.String","java.lang.String","java.lang.String"},new Object[] {offerHdrId, leaseId, userName});
        return (String)_ret;
    }

    public String sbmtforappr(String p_func_id, String p_ref_id,
                              String p_table_name, String p_org_id,
                              String p_prop_id, String p_build_id,
                              String p_unit_id) {
        Object _ret =
            this.riInvokeExportedMethod(this,"sbmtforappr",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {p_func_id, p_ref_id, p_table_name, p_org_id, p_prop_id, p_build_id, p_unit_id});
        return (String)_ret;
    }

    public String forappr(String p_func_id, String p_ref_id,
                          String p_user_grp_id, String p_level_no,
                          String p_flow_with_id, String p_reason,
                          String p_apr_rej) {
        Object _ret =
            this.riInvokeExportedMethod(this,"forappr",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {p_func_id, p_ref_id, p_user_grp_id, p_level_no, p_flow_with_id, p_reason, p_apr_rej});
        return (String)_ret;
    }

    public String submitLaForAppr(String laId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"submitLaForAppr",new String [] {"java.lang.String"},new Object[] {laId});
        return (String)_ret;
    }

    public String responseLaForAppr(String laId, String reason,
                                    String apr_rej) {
        Object _ret =
            this.riInvokeExportedMethod(this,"responseLaForAppr",new String [] {"java.lang.String","java.lang.String","java.lang.String"},new Object[] {laId, reason, apr_rej});
        return (String)_ret;
    }

    public String getCashRcptIdRspnse(String pReceiptNo, String pCshRcptId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getCashRcptIdRspnse",new String [] {"java.lang.String","java.lang.String"},new Object[] {pReceiptNo, pCshRcptId});
        return (String)_ret;
    }

    public String cancellationCall(String leaseId, String userName) {
        Object _ret =
            this.riInvokeExportedMethod(this,"cancellationCall",new String [] {"java.lang.String","java.lang.String"},new Object[] {leaseId, userName});
        return (String)_ret;
    }
}
