package model.ROVO;

import java.sql.ResultSet;

import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 09 17:41:37 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LeasUnitMappingROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LeasUnitMappingROVOImpl() {
    }

    /**
     * Returns the bind variable value for P_LEASE_AGREEMENT_ID.
     * @return bind variable value for P_LEASE_AGREEMENT_ID
     */
    public String getP_LEASE_AGREEMENT_ID() {
        return (String)getNamedWhereClauseParam("P_LEASE_AGREEMENT_ID");
    }

    /**
     * Sets <code>value</code> for bind variable P_LEASE_AGREEMENT_ID.
     * @param value value to bind as P_LEASE_AGREEMENT_ID
     */
    public void setP_LEASE_AGREEMENT_ID(String value) {
        setNamedWhereClauseParam("P_LEASE_AGREEMENT_ID", value);
    }

    /**
     * executeQueryForCollection - overridden for custom java data source support.
     */
    protected void executeQueryForCollection(Object qc, Object[] params,
                                             int noUserParams) {
        super.executeQueryForCollection(qc, params, noUserParams);
    }

    /**
     * hasNextForCollection - overridden for custom java data source support.
     */
    protected boolean hasNextForCollection(Object qc) {
        boolean bRet = super.hasNextForCollection(qc);
        return bRet;
    }

    /**
     * createRowFromResultSet - overridden for custom java data source support.
     */
    protected ViewRowImpl createRowFromResultSet(Object qc,
                                                 ResultSet resultSet) {
        ViewRowImpl value = super.createRowFromResultSet(qc, resultSet);
        return value;
    }

    /**
     * getQueryHitCount - overridden for custom java data source support.
     */
    public long getQueryHitCount(ViewRowSetImpl viewRowSet) {
        long value = super.getQueryHitCount(viewRowSet);
        return value;
    }
}
