package model.AM.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jun 06 15:31:42 IST 2021
// ---------------------------------------------------------------------
public interface WoScheduler_AM extends ApplicationModule {
    String reWorkForHistRecord(String mainId, String userId, String reason);
}
