package model.AM.client;

import model.AM.common.WoInv_AM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 15 19:00:19 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WoInv_AMClient extends ApplicationModuleImpl implements WoInv_AM {
    /**
     * This is the default constructor (do not remove).
     */
    public WoInv_AMClient() {
    }


    public String createWoArLines(String wo_inv_hdr_id, String material_cost,
                                  String resource_cost, String user_name) {
        Object _ret =
            this.riInvokeExportedMethod(this,"createWoArLines",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {wo_inv_hdr_id, material_cost, resource_cost, user_name});
        return (String)_ret;
    }

    public String getARInvoiceTrxDetailsWoInv(String pWoInvNum,
                                              String pCustomerTrxId,
                                              String pCustomerTrxNo) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getARInvoiceTrxDetailsWoInv",new String [] {"java.lang.String","java.lang.String","java.lang.String"},new Object[] {pWoInvNum, pCustomerTrxId, pCustomerTrxNo});
        return (String)_ret;
    }

    public String callAutoWoInv(String frmDate, String tooDate) {
        Object _ret =
            this.riInvokeExportedMethod(this,"callAutoWoInv",new String [] {"java.lang.String","java.lang.String"},new Object[] {frmDate, tooDate});
        return (String)_ret;
    }
}
