package model.EO;

import oracle.jbo.server.EntityCache;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 18 14:46:12 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OfferDetail_EOCollImpl extends EntityCache {
    /**
     * This is the default constructor (do not remove).
     */
    public OfferDetail_EOCollImpl() {
    }
}
