package model.VO;

import java.math.BigDecimal;

import java.sql.Blob;
import java.sql.Timestamp;

import oracle.jbo.RowSet;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 21 14:36:10 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ChecklistResponse_VORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ClResId {
            public Object get(ChecklistResponse_VORowImpl obj) {
                return obj.getClResId();
            }

            public void put(ChecklistResponse_VORowImpl obj, Object value) {
                obj.setClResId((BigDecimal)value);
            }
        }
        ,
        FuncId {
            public Object get(ChecklistResponse_VORowImpl obj) {
                return obj.getFuncId();
            }

            public void put(ChecklistResponse_VORowImpl obj, Object value) {
                obj.setFuncId((BigDecimal)value);
            }
        }
        ,
        FuncRefId {
            public Object get(ChecklistResponse_VORowImpl obj) {
                return obj.getFuncRefId();
            }

            public void put(ChecklistResponse_VORowImpl obj, Object value) {
                obj.setFuncRefId((BigDecimal)value);
            }
        }
        ,
        FuncClId {
            public Object get(ChecklistResponse_VORowImpl obj) {
                return obj.getFuncClId();
            }

            public void put(ChecklistResponse_VORowImpl obj, Object value) {
                obj.setFuncClId((BigDecimal)value);
            }
        }
        ,
        ItemResponse1 {
            public Object get(ChecklistResponse_VORowImpl obj) {
                return obj.getItemResponse1();
            }

            public void put(ChecklistResponse_VORowImpl obj, Object value) {
                obj.setItemResponse1((String)value);
            }
        }
        ,
        ItemResponse2 {
            public Object get(ChecklistResponse_VORowImpl obj) {
                return obj.getItemResponse2();
            }

            public void put(ChecklistResponse_VORowImpl obj, Object value) {
                obj.setItemResponse2((Blob)value);
            }
        }
        ,
        RespondedYn {
            public Object get(ChecklistResponse_VORowImpl obj) {
                return obj.getRespondedYn();
            }

            public void put(ChecklistResponse_VORowImpl obj, Object value) {
                obj.setRespondedYn((String)value);
            }
        }
        ,
        AttributeCategory {
            public Object get(ChecklistResponse_VORowImpl obj) {
                return obj.getAttributeCategory();
            }

            public void put(ChecklistResponse_VORowImpl obj, Object value) {
                obj.setAttributeCategory((String)value);
            }
        }
        ,
        Attribute1 {
            public Object get(ChecklistResponse_VORowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(ChecklistResponse_VORowImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(ChecklistResponse_VORowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(ChecklistResponse_VORowImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(ChecklistResponse_VORowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(ChecklistResponse_VORowImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(ChecklistResponse_VORowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(ChecklistResponse_VORowImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(ChecklistResponse_VORowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(ChecklistResponse_VORowImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(ChecklistResponse_VORowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(ChecklistResponse_VORowImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(ChecklistResponse_VORowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(ChecklistResponse_VORowImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(ChecklistResponse_VORowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(ChecklistResponse_VORowImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(ChecklistResponse_VORowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(ChecklistResponse_VORowImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(ChecklistResponse_VORowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(ChecklistResponse_VORowImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(ChecklistResponse_VORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(ChecklistResponse_VORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(ChecklistResponse_VORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(ChecklistResponse_VORowImpl obj, Object value) {
                obj.setCreationDate((Timestamp)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(ChecklistResponse_VORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(ChecklistResponse_VORowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(ChecklistResponse_VORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(ChecklistResponse_VORowImpl obj, Object value) {
                obj.setLastUpdateDate((Timestamp)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(ChecklistResponse_VORowImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(ChecklistResponse_VORowImpl obj, Object value) {
                obj.setLastUpdateLogin((String)value);
            }
        }
        ,
        RowID {
            public Object get(ChecklistResponse_VORowImpl obj) {
                return obj.getRowID();
            }

            public void put(ChecklistResponse_VORowImpl obj, Object value) {
                obj.setRowID((String)value);
            }
        }
        ,
        Trns_Active {
            public Object get(ChecklistResponse_VORowImpl obj) {
                return obj.getTrns_Active();
            }

            public void put(ChecklistResponse_VORowImpl obj, Object value) {
                obj.setTrns_Active((Boolean)value);
            }
        }
        ,
        CheckListResponse_ROVO1 {
            public Object get(ChecklistResponse_VORowImpl obj) {
                return obj.getCheckListResponse_ROVO1();
            }

            public void put(ChecklistResponse_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(ChecklistResponse_VORowImpl object);

        public abstract void put(ChecklistResponse_VORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int CLRESID = AttributesEnum.ClResId.index();
    public static final int FUNCID = AttributesEnum.FuncId.index();
    public static final int FUNCREFID = AttributesEnum.FuncRefId.index();
    public static final int FUNCCLID = AttributesEnum.FuncClId.index();
    public static final int ITEMRESPONSE1 = AttributesEnum.ItemResponse1.index();
    public static final int ITEMRESPONSE2 = AttributesEnum.ItemResponse2.index();
    public static final int RESPONDEDYN = AttributesEnum.RespondedYn.index();
    public static final int ATTRIBUTECATEGORY = AttributesEnum.AttributeCategory.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int ROWID = AttributesEnum.RowID.index();
    public static final int TRNS_ACTIVE = AttributesEnum.Trns_Active.index();
    public static final int CHECKLISTRESPONSE_ROVO1 = AttributesEnum.CheckListResponse_ROVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ChecklistResponse_VORowImpl() {
    }

    /**
     * Gets ChecklistResponse_EO entity object.
     * @return the ChecklistResponse_EO
     */
    public EntityImpl getChecklistResponse_EO() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for CL_RES_ID using the alias name ClResId.
     * @return the CL_RES_ID
     */
    public BigDecimal getClResId() {
        return (BigDecimal) getAttributeInternal(CLRESID);
    }

    /**
     * Sets <code>value</code> as attribute value for CL_RES_ID using the alias name ClResId.
     * @param value value to set the CL_RES_ID
     */
    public void setClResId(BigDecimal value) {
        setAttributeInternal(CLRESID, value);
    }

    /**
     * Gets the attribute value for FUNC_ID using the alias name FuncId.
     * @return the FUNC_ID
     */
    public BigDecimal getFuncId() {
        return (BigDecimal) getAttributeInternal(FUNCID);
    }

    /**
     * Sets <code>value</code> as attribute value for FUNC_ID using the alias name FuncId.
     * @param value value to set the FUNC_ID
     */
    public void setFuncId(BigDecimal value) {
        setAttributeInternal(FUNCID, value);
    }

    /**
     * Gets the attribute value for FUNC_REF_ID using the alias name FuncRefId.
     * @return the FUNC_REF_ID
     */
    public BigDecimal getFuncRefId() {
        return (BigDecimal) getAttributeInternal(FUNCREFID);
    }

    /**
     * Sets <code>value</code> as attribute value for FUNC_REF_ID using the alias name FuncRefId.
     * @param value value to set the FUNC_REF_ID
     */
    public void setFuncRefId(BigDecimal value) {
        setAttributeInternal(FUNCREFID, value);
    }

    /**
     * Gets the attribute value for FUNC_CL_ID using the alias name FuncClId.
     * @return the FUNC_CL_ID
     */
    public BigDecimal getFuncClId() {
        return (BigDecimal) getAttributeInternal(FUNCCLID);
    }

    /**
     * Sets <code>value</code> as attribute value for FUNC_CL_ID using the alias name FuncClId.
     * @param value value to set the FUNC_CL_ID
     */
    public void setFuncClId(BigDecimal value) {
        setAttributeInternal(FUNCCLID, value);
    }

    /**
     * Gets the attribute value for ITEM_RESPONSE1 using the alias name ItemResponse1.
     * @return the ITEM_RESPONSE1
     */
    public String getItemResponse1() {
        return (String) getAttributeInternal(ITEMRESPONSE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_RESPONSE1 using the alias name ItemResponse1.
     * @param value value to set the ITEM_RESPONSE1
     */
    public void setItemResponse1(String value) {
        setAttributeInternal(ITEMRESPONSE1, value);
    }

    /**
     * Gets the attribute value for ITEM_RESPONSE2 using the alias name ItemResponse2.
     * @return the ITEM_RESPONSE2
     */
    public Blob getItemResponse2() {
        return (Blob) getAttributeInternal(ITEMRESPONSE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_RESPONSE2 using the alias name ItemResponse2.
     * @param value value to set the ITEM_RESPONSE2
     */
    public void setItemResponse2(Blob value) {
        setAttributeInternal(ITEMRESPONSE2, value);
    }

    /**
     * Gets the attribute value for RESPONDED_YN using the alias name RespondedYn.
     * @return the RESPONDED_YN
     */
    public String getRespondedYn() {
        return (String) getAttributeInternal(RESPONDEDYN);
    }

    /**
     * Sets <code>value</code> as attribute value for RESPONDED_YN using the alias name RespondedYn.
     * @param value value to set the RESPONDED_YN
     */
    public void setRespondedYn(String value) {
        setAttributeInternal(RESPONDEDYN, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @return the ATTRIBUTE_CATEGORY
     */
    public String getAttributeCategory() {
        return (String) getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @param value value to set the ATTRIBUTE_CATEGORY
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for ROWID using the alias name RowID.
     * @return the ROWID
     */
    public String getRowID() {
        return (String) getAttributeInternal(ROWID);
    }

    /**
     * Sets <code>value</code> as attribute value for ROWID using the alias name RowID.
     * @param value value to set the ROWID
     */
    public void setRowID(String value) {
        setAttributeInternal(ROWID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trns_Active.
     * @return the Trns_Active
     */
    public Boolean getTrns_Active() {
        Boolean flag = false;
        if (this.getRespondedYn() != null && this.getRespondedYn().equals("Y")) {
            flag = true;
        } else {
            flag = false;
        }
        return flag;
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trns_Active.
     * @param value value to set the  Trns_Active
     */
    public void setTrns_Active(Boolean value) {
        if (value) {
            setRespondedYn("Y");
        } else {
            setRespondedYn("N");
        }
        setAttributeInternal(TRNS_ACTIVE, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CheckListResponse_ROVO1.
     */
    public RowSet getCheckListResponse_ROVO1() {
        return (RowSet)getAttributeInternal(CHECKLISTRESPONSE_ROVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
