package model.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 02 15:36:18 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OfferHrd_VOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public OfferHrd_VOImpl() {
    }


    /**
     * Returns the variable value for BV_Off_ID.
     * @return variable value for BV_Off_ID
     */
    public String getBV_Off_ID() {
        return (String)ensureVariableManager().getVariableValue("BV_Off_ID");
    }

    /**
     * Sets <code>value</code> for variable BV_Off_ID.
     * @param value value to bind as BV_Off_ID
     */
    public void setBV_Off_ID(String value) {
        ensureVariableManager().setVariableValue("BV_Off_ID", value);
    }

    /**
     * Returns the variable value for B_CAR_PARK.
     * @return variable value for B_CAR_PARK
     */
    public String getB_CAR_PARK() {
        return (String)ensureVariableManager().getVariableValue("B_CAR_PARK");
    }

    /**
     * Sets <code>value</code> for variable B_CAR_PARK.
     * @param value value to bind as B_CAR_PARK
     */
    public void setB_CAR_PARK(String value) {
        ensureVariableManager().setVariableValue("B_CAR_PARK", value);
    }
}
