package model.AM;

import java.math.BigDecimal;

import java.sql.CallableStatement;


import java.sql.SQLException;
import java.sql.Types;

import java.text.ParseException;
import java.text.SimpleDateFormat;

import java.util.ArrayList;


import java.util.Date;

import model.AM.common.Cancellation_AM;

import model.VO.BookingDetail_VOImpl;
import model.VO.BookingMilestonesOtherChargesVOImpl;
import model.VO.Booking_Milestone_VOImpl;
import model.VO.Cancellation_VOImpl;

import model.VO.LeaseAgreement_VOImpl;
import model.VO.PropertyUnits_VOImpl;
import model.VO.Receipt_VOImpl;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 24 18:26:10 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Cancellation_AMImpl extends ApplicationModuleImpl implements Cancellation_AM {
    /**
     * This is the default constructor (do not remove).
     */
    public Cancellation_AMImpl() {
    }

    /**
     * Container's getter for Cancellation_VO1.
     * @return Cancellation_VO1
     */
    public Cancellation_VOImpl getCancellation_VO1() {
        return (Cancellation_VOImpl)findViewObject("Cancellation_VO1");
    }

    /**
     * Container's getter for CancelDueAmountArDtl_VO1.
     * @return CancelDueAmountArDtl_VO1
     */
    public ViewObjectImpl getCancelDueAmountArDtl_VO1() {
        return (ViewObjectImpl)findViewObject("CancelDueAmountArDtl_VO1");
    }

    /**
     * Container's getter for BookingMilestonesOtherChargesVO1.
     * @return BookingMilestonesOtherChargesVO1
     */
    public ViewObjectImpl getBookingMilestonesOtherChargesVO1() {
        return (ViewObjectImpl)findViewObject("BookingMilestonesOtherChargesVO1");
    }

    /**
     * Container's getter for BookingDetail_VO1.
     * @return BookingDetail_VO1
     */
    public ViewObjectImpl getBookingDetail_VO1() {
        return (ViewObjectImpl)findViewObject("BookingDetail_VO1");
    }

    /**
     * Container's getter for CancelDueAmountDtl_VO1.
     * @return CancelDueAmountDtl_VO1
     */
    public ViewObjectImpl getCancelDueAmountDtl_VO1() {
        return (ViewObjectImpl)findViewObject("CancelDueAmountDtl_VO1");
    }

    /**
     * Container's getter for SrearchCancellation_RoVo1.
     * @return SrearchCancellation_RoVo1
     */
    public ViewObjectImpl getSrearchCancellation_RoVo1() {
        return (ViewObjectImpl)findViewObject("SrearchCancellation_RoVo1");
    }

    /**
     * Container's getter for getFunctionCodeROVO1.
     * @return getFunctionCodeROVO1
     */
    public ViewObjectImpl getgetFunctionCodeROVO1() {
        return (ViewObjectImpl)findViewObject("getFunctionCodeROVO1");
    }

    /**
     * Container's getter for Booking_Milestone_VO1.
     * @return Booking_Milestone_VO1
     */
    public Booking_Milestone_VOImpl getBooking_Milestone_VO1() {
        return (Booking_Milestone_VOImpl)findViewObject("Booking_Milestone_VO1");
    }

    /**
     * Container's getter for Cancel_BookingDetail_Vl1.
     * @return Cancel_BookingDetail_Vl1
     */
    public ViewLinkImpl getCancel_BookingDetail_Vl1() {
        return (ViewLinkImpl)findViewLink("Cancel_BookingDetail_Vl1");
    }

    /**
     * Container's getter for Cancel_CancelDueAmtDtl_Vl1.
     * @return Cancel_CancelDueAmtDtl_Vl1
     */
    public ViewLinkImpl getCancel_CancelDueAmtDtl_Vl1() {
        return (ViewLinkImpl)findViewLink("Cancel_CancelDueAmtDtl_Vl1");
    }

    /**
     * Container's getter for Cancel_BookingMilestonesVo_Vl1.
     * @return Cancel_BookingMilestonesVo_Vl1
     */
    public ViewLinkImpl getCancel_BookingMilestonesVo_Vl1() {
        return (ViewLinkImpl)findViewLink("Cancel_BookingMilestonesVo_Vl1");
    }
    
    public ArrayList getdetails(BigDecimal p_lease_id, BigDecimal p_org_id,String p_termination_date) {
                System.err.println("lll"+p_lease_id);
                System.err.println("ooo"+p_org_id);
                System.err.println("ttt"+p_termination_date);
                ArrayList list=new ArrayList();
        
                try{
                    
                        
                CallableStatement cs=this.getDBTransaction().createCallableStatement("{call xxpm_can_ext_pkg.get_header_info(?,?,?,?,?,?,?)}", 1);
                cs.setBigDecimal(1,p_lease_id);
                cs.setBigDecimal(2,p_org_id);
                cs.setString(3,p_termination_date);
                cs.registerOutParameter(4, Types.NUMERIC);
                cs.registerOutParameter(5, Types.NUMERIC);
                cs.registerOutParameter(6, Types.NUMERIC);
                cs.registerOutParameter(7, Types.NUMERIC);
                cs.execute();
                System.err.println(cs.getBigDecimal(4));
              list.add(cs.getBigDecimal(4));
              list.add(cs.getBigDecimal(5));
              list.add(cs.getBigDecimal(6));
              list.add(cs.getBigDecimal(7));
                
                
                    
                    
                    }
                catch(Exception e)
                {
                }
                return list;
    
    }
    
    public void getcancellation(BigDecimal leaseid,BigDecimal DaysConsumed,BigDecimal DaysRemaining,BigDecimal DailyRentalRate,BigDecimal DailyDiscountingRate)
    {
         
                CallableStatement cs=this.getDBTransaction().createCallableStatement("{call xxpm_can_ext_pkg.cancellation_dlt_creation(?,?,?,?,?)}",1);
                try {
//                    
                    cs.setBigDecimal(1,leaseid);
                    cs.setBigDecimal(2,DaysConsumed);
                    cs.setBigDecimal(3,DaysRemaining);
                    cs.setBigDecimal(4,DailyRentalRate);
                    cs.setBigDecimal(5,DailyDiscountingRate);
                    cs.execute();
                } catch (SQLException e) {
                    
                }
    }


    public void getStatusChange(BigDecimal cancelid,BigDecimal leaseid,BigDecimal unitid)
    {
         
                CallableStatement cs=this.getDBTransaction().createCallableStatement("{call xxpm_can_ext_pkg.unitStatusChange(?,?,?)}",1);
                try {
    //
                    cs.setBigDecimal(1,unitid);
                    cs.setBigDecimal(2,cancelid);
                    cs.setBigDecimal(3,leaseid);
                    
                    cs.execute();
                } catch (SQLException e) {
                    
                }
    }

    //Direct rejection from draft
        public String directRejectionFromDraft(String cnId,String userId,String funcId,String reasonCN)
        {
            String flag="null";
            CallableStatement cs=this.getDBTransaction().createCallableStatement("{call XXFND_UTIL_PKG.DIRECT_REJECTION(?,?,?,?,?,?)}",1);
            try {
                cs.setString(1,cnId);
                cs.setString(2,userId);
                cs.setString(3,funcId);
                cs.setString(4,reasonCN);
                cs.registerOutParameter(5,Types.VARCHAR);
                cs.registerOutParameter(6,Types.VARCHAR);
                cs.execute();
           
              flag=cs.getString(6).toString();
            } catch (SQLException e) {
            }
            return flag;
        }
    //update cancelled tag for offer and bk dtl lines for multiple offer renewal
        public String updateCancelledTagOnApproved(String cnId)
        {
            String flag="null";
            CallableStatement cs=this.getDBTransaction().createCallableStatement("{call auto_create_pkg.UPDATE_CANCELLED_TAG_ON_APR(?,?,?)}",1);
            try {
                cs.setString(1,cnId);
                cs.registerOutParameter(2,Types.VARCHAR);
                cs.registerOutParameter(3,Types.VARCHAR);
                cs.execute();
           
              flag=cs.getString(3).toString();
            } catch (SQLException e) {
            }
            return flag;
        }
    /**
     * Container's getter for SrearchCancellation_RoVo2.
     * @return SrearchCancellation_RoVo2
     */
    public ViewObjectImpl getSrearchCancellation_RoVo2() {
        return (ViewObjectImpl)findViewObject("SrearchCancellation_RoVo2");
    }

    /**
     * Container's getter for CancelDueAmountArDtl_VO2.
     * @return CancelDueAmountArDtl_VO2
     */
    public ViewObjectImpl getCancelDueAmountArDtl_VO2() {
        return (ViewObjectImpl)findViewObject("CancelDueAmountArDtl_VO2");
    }

    /**
     * Container's getter for Cancel_CancelDueAr_VL1.
     * @return Cancel_CancelDueAr_VL1
     */
    public ViewLinkImpl getCancel_CancelDueAr_VL1() {
        return (ViewLinkImpl)findViewLink("Cancel_CancelDueAr_VL1");
    }

    /**
     * Container's getter for Org_ROVO1.
     * @return Org_ROVO1
     */
    public ViewObjectImpl getOrg_ROVO1() {
        return (ViewObjectImpl)findViewObject("Org_ROVO1");
    }

    /**
     * Container's getter for OfferType_ROVO1.
     * @return OfferType_ROVO1
     */
    public ViewObjectImpl getOfferType_ROVO1() {
        return (ViewObjectImpl)findViewObject("OfferType_ROVO1");
    }

    /**
     * Container's getter for getPayloadInformationCancellation_ROVO1.
     * @return getPayloadInformationCancellation_ROVO1
     */
    public ViewObjectImpl getgetPayloadInformationCancellation_ROVO1() {
        return (ViewObjectImpl)findViewObject("getPayloadInformationCancellation_ROVO1");
    }
    public String getCodeSegmentCombination(String pBusinessUnitId,
                                                String pChargeType,
                                                String pUnitId) {
        System.err.println(pBusinessUnitId+""+pChargeType+""+pUnitId);
            String returnResult = null;
//            java.math.BigDecimal businessUnitId =
//                new java.math.BigDecimal(pBusinessUnitId);
            Object businessUnitId=pBusinessUnitId;
            Object chargeType = pChargeType;
//            java.math.BigDecimal unitId = new java.math.BigDecimal(pUnitId);
            Object unitId=pUnitId;
            String stmt =
                "begin xxpm_util_package.get_gl_code (?,?,?,?,?,?); end;";
            CallableStatement cst = null;
            try {
                cst = this.getDBTransaction().createCallableStatement(stmt, 0);
                cst.setObject("p_business_unit_id", businessUnitId);
                cst.setObject("p_charge_type_code", chargeType);
                cst.setObject("p_unit_id", unitId);
                cst.registerOutParameter("x_gl_code", Types.VARCHAR);
                cst.registerOutParameter("x_err_code", Types.VARCHAR);
                cst.registerOutParameter("x_err_msg", Types.VARCHAR);
                cst.executeUpdate();
                returnResult = cst.getString("x_err_code");
                return cst.getString("x_gl_code");
            } catch (SQLException e) {
                e.printStackTrace();
                returnResult = e.toString();
                return returnResult;
            } finally {
                if (cst != null) {
                    try {
                        cst.close();
                    } catch (SQLException e) {
                        returnResult = e.toString();
                        return returnResult;
                    }
                }
            }
        }

    /**
     * Container's getter for getTaxCodeROVO1.
     * @return getTaxCodeROVO1
     */
    public ViewObjectImpl getgetTaxCodeROVO1() {
        return (ViewObjectImpl)findViewObject("getTaxCodeROVO1");
    }

    /**
     * Container's getter for getARSetupDetails_ROVO1.
     * @return getARSetupDetails_ROVO1
     */
    public ViewObjectImpl getgetARSetupDetails_ROVO1() {
        return (ViewObjectImpl)findViewObject("getARSetupDetails_ROVO1");
    }

    /**
     * Container's getter for Lookup_View_ROVO1.
     * @return Lookup_View_ROVO1
     */
    public ViewObjectImpl getLookup_View_ROVO1() {
        return (ViewObjectImpl)findViewObject("Lookup_View_ROVO1");
    }

    /**
     * Container's getter for Lookup_View_ROVO3.
     * @return Lookup_View_ROVO3
     */
    public ViewObjectImpl getLookup_View_ROVO3() {
        return (ViewObjectImpl)findViewObject("Lookup_View_ROVO3");
    }

    /**
     * Container's getter for findByUnitName1.
     * @return findByUnitName1
     */
    public ViewObjectImpl getfindByUnitName1() {
        return (ViewObjectImpl)findViewObject("findByUnitName1");
    }

    /**
     * Container's getter for masterdetail_ROVO1.
     * @return masterdetail_ROVO1
     */
    public ViewObjectImpl getmasterdetail_ROVO1() {
        return (ViewObjectImpl)findViewObject("masterdetail_ROVO1");
    }


    /**
     * Container's getter for getApprovalHistoryROVo1.
     * @return getApprovalHistoryROVo1
     */
    public ViewObjectImpl getgetApprovalHistoryROVo1() {
        return (ViewObjectImpl)findViewObject("getApprovalHistoryROVo1");
    }

    /**
     * Container's getter for CancellationApproval_VL1.
     * @return CancellationApproval_VL1
     */
    public ViewLinkImpl getCancellationApproval_VL1() {
        return (ViewLinkImpl)findViewLink("CancellationApproval_VL1");
    }

    /**
     * Container's getter for CancellationHeaderProposedROVO1.
     * @return CancellationHeaderProposedROVO1
     */
    public ViewObjectImpl getCancellationHeaderProposedROVO1() {
        return (ViewObjectImpl)findViewObject("CancellationHeaderProposedROVO1");
    }

    /**
     * Container's getter for cancelHH_VL1.
     * @return cancelHH_VL1
     */
    public ViewLinkImpl getcancelHH_VL1() {
        return (ViewLinkImpl)findViewLink("cancelHH_VL1");
    }

    /**
     * Container's getter for CancellationDetailProposed_ROVO1.
     * @return CancellationDetailProposed_ROVO1
     */
    public ViewObjectImpl getCancellationDetailProposed_ROVO1() {
        return (ViewObjectImpl)findViewObject("CancellationDetailProposed_ROVO1");
    }

    /**
     * Container's getter for CancelHD_H_VL1.
     * @return CancelHD_H_VL1
     */
    public ViewLinkImpl getCancelHD_H_VL1() {
        return (ViewLinkImpl)findViewLink("CancelHD_H_VL1");
    }
    
    public void cancellation_proposal(Long P_cancellationId)
    {
        CallableStatement cs=this.getDBTransaction().createCallableStatement("{call xxpm_can_ext_pkg.cancellation_proposed(?)}",1);
        try {
            cs.setLong(1,P_cancellationId);
            cs.execute();
        } catch (SQLException e) {
        }
        
    }

    /**
     * Container's getter for CancellationOtherChargeProposed_ROVO1.
     * @return CancellationOtherChargeProposed_ROVO1
     */
    public ViewObjectImpl getCancellationOtherChargeProposed_ROVO1() {
        return (ViewObjectImpl)findViewObject("CancellationOtherChargeProposed_ROVO1");
    }

    /**
     * Container's getter for CancelHO_VL1.
     * @return CancelHO_VL1
     */
    public ViewLinkImpl getCancelHO_VL1() {
        return (ViewLinkImpl)findViewLink("CancelHO_VL1");
    }

    /**
     * Container's getter for Receipt_VO1.
     * @return Receipt_VO1
     */
    public Receipt_VOImpl getReceipt_VO1() {
        return (Receipt_VOImpl)findViewObject("Receipt_VO1");
    }

    /**
     * Container's getter for Cancel_Receipt_Vl1.
     * @return Cancel_Receipt_Vl1
     */
    public ViewLinkImpl getCancel_Receipt_Vl1() {
        return (ViewLinkImpl)findViewLink("Cancel_Receipt_Vl1");
    }

    /**
     * Container's getter for LeaseAgreement_VO1.
     * @return LeaseAgreement_VO1
     */
    public LeaseAgreement_VOImpl getLeaseAgreement_VO1() {
        return (LeaseAgreement_VOImpl)findViewObject("LeaseAgreement_VO1");
    }

    /**
     * Container's getter for PropertyUnits_VO1.
     * @return PropertyUnits_VO1
     */
    public PropertyUnits_VOImpl getPropertyUnits_VO1() {
        return (PropertyUnits_VOImpl)findViewObject("PropertyUnits_VO1");
    }
}
