package model.AM.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 04 10:39:44 IST 2018
// ---------------------------------------------------------------------
public interface Receipt extends ApplicationModule {
    String OnCreateReceipt();
}
