package model.AM;

import model.AM.common.Receipt;

import oracle.adf.share.ADFContext;

import oracle.jbo.Row;
import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaRow;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 04 10:33:38 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ReceiptImpl extends ApplicationModuleImpl implements Receipt {
    /**
     * This is the default constructor (do not remove).
     */
    public ReceiptImpl() {
    }

    /**
     * Container's getter for Receipt_VO1.
     * @return Receipt_VO1
     */
    public ViewObjectImpl getReceipt_VO1() {
        return (ViewObjectImpl)findViewObject("Receipt_VO1");
    }
    
    
    public String OnCreateReceipt(){
        ViewObject revVO=this.getReceipt_VO1().getViewObject();
        Row receiptRow=revVO.createRow();
        receiptRow.setAttribute("OrgId", ADFContext.getCurrent().getPageFlowScope().get("OrgId")==null?"":ADFContext.getCurrent().getPageFlowScope().get("OrgId").toString());
        receiptRow.setAttribute("CustomerName", ADFContext.getCurrent().getPageFlowScope().get("CustName")==null?"":ADFContext.getCurrent().getPageFlowScope().get("CustName").toString());
        receiptRow.setAttribute("BankName", ADFContext.getCurrent().getPageFlowScope().get("CustBankName")==null?"":ADFContext.getCurrent().getPageFlowScope().get("CustBankName").toString());
        receiptRow.setAttribute("PayRefNumber",
                                ADFContext.getCurrent().getPageFlowScope().get("CustBankAccNumber")==null?"":ADFContext.getCurrent().getPageFlowScope().get("CustBankAccNumber").toString());
        receiptRow.setAttribute("BankBranchName",
                                ADFContext.getCurrent().getPageFlowScope().get("CustBranchName")==null?"":ADFContext.getCurrent().getPageFlowScope().get("CustBranchName").toString());
        receiptRow.setAttribute("SourceFuncRefId",
                                ADFContext.getCurrent().getPageFlowScope().get("BookingId")==null?"":ADFContext.getCurrent().getPageFlowScope().get("BookingId").toString());
        receiptRow.setAttribute("SourceFuncRefId",
                                ADFContext.getCurrent().getPageFlowScope().get("BookingId")==null?"":ADFContext.getCurrent().getPageFlowScope().get("BookingId").toString());
       
//       System.out.println("--------"+ADFContext.getCurrent().getPageFlowScope().get("scfnId"));
       receiptRow.setAttribute("SourceFuncRefId",
                                ADFContext.getCurrent().getPageFlowScope().get("scfnId")==null?"":ADFContext.getCurrent().getPageFlowScope().get("scfnId").toString());
       
        //27-MAY FOR OC
        receiptRow.setAttribute("SourceFuncId",
                                 ADFContext.getCurrent().getPageFlowScope().get("funcId")==null?"":ADFContext.getCurrent().getPageFlowScope().get("funcId").toString());
       //03-12-19 for OcFlag C from OC
       receiptRow.setAttribute("CancelId", ADFContext.getCurrent().getPageFlowScope().get("CancelId")==null?"":ADFContext.getCurrent().getPageFlowScope().get("CancelId").toString());
       
       Object val=ADFContext.getCurrent().getPageFlowScope().get("BookingId")==null?"":ADFContext.getCurrent().getPageFlowScope().get("BookingId").toString();
       
        //receiptRow.setAttribute("ReceiptType",
                               // ADFContext.getCurrent().getPageFlowScope().get("receiptType")==null?"":ADFContext.getCurrent().getPageFlowScope().get("receiptType").toString());
        //Object val=ADFContext.getCurrent().getPageFlowScope().get("BookingId")==null?"":ADFContext.getCurrent().getPageFlowScope().get("BookingId").toString();
       
       
       //#{pageFlowScope.receiptType}
        
//        receiptRow.setAttribute("ReceiptAmount",
//                                ADFContext.getCurrent().getPageFlowScope().get("InstallmentAmount")==null?"":ADFContext.getCurrent().getPageFlowScope().get("InstallmentAmount").toString());
        receiptRow.setAttribute("RecommendedAmount",
                                ADFContext.getCurrent().getPageFlowScope().get("Amount")==null?"":ADFContext.getCurrent().getPageFlowScope().get("Amount").toString());
        //#{bindings.ReceivedAmount.hints.displayWidth}
        
        receiptRow.setAttribute("ReceivedAmount",
                                ADFContext.getCurrent().getPageFlowScope().get("Amount")==null?"":ADFContext.getCurrent().getPageFlowScope().get("Amount").toString());
        receiptRow.setAttribute("PayRecDate",
                                ADFContext.getCurrent().getPageFlowScope().get("DueDate")==null?"":ADFContext.getCurrent().getPageFlowScope().get("DueDate").toString());
        //23-may for chrg Type in oc rcpt
        receiptRow.setAttribute("RctType",
                                ADFContext.getCurrent().getPageFlowScope().get("chrgTyp")==null?"":ADFContext.getCurrent().getPageFlowScope().get("chrgTyp").toString());
        
        
        //PayRecDate
//        receiptRow.setAttribute("ReceivedAmount",
//                                ADFContext.getCurrent().getPageFlowScope().get("InstallmentAmount")==null?"":ADFContext.getCurrent().getPageFlowScope().get("InstallmentAmount").toString());
        revVO.insertRow(receiptRow);
        
        Object lineval=ADFContext.getCurrent().getPageFlowScope().get("Type")==null?"":ADFContext.getCurrent().getPageFlowScope().get("Type").toString();
        if(lineval.equals("INS")){
            
            ViewObject revDtlVO=this.getReceiptDtlVO1().getViewObject();
            Row receiptDtlRow=revDtlVO.createRow();
            receiptDtlRow.setAttribute("BookingMsDtlId", ADFContext.getCurrent().getPageFlowScope().get("BookingMsId")==null?"":ADFContext.getCurrent().getPageFlowScope().get("BookingMsId").toString());
            receiptDtlRow.setAttribute("AppliedDate", ADFContext.getCurrent().getPageFlowScope().get("DueDate")==null?"":ADFContext.getCurrent().getPageFlowScope().get("DueDate").toString());
            receiptDtlRow.setAttribute("AmountApplied", ADFContext.getCurrent().getPageFlowScope().get("Amount")==null?"":ADFContext.getCurrent().getPageFlowScope().get("Amount").toString());
            revDtlVO.insertRow(receiptDtlRow);
            
            
        }
        
        
        
        
        return null;
    }

    /**
     * Container's getter for ReceiptDtlVO1.
     * @return ReceiptDtlVO1
     */
    public ViewObjectImpl getReceiptDtlVO1() {
        return (ViewObjectImpl)findViewObject("ReceiptDtlVO1");
    }

    /**
     * Container's getter for ReceiptHdr_Dtl_VL1.
     * @return ReceiptHdr_Dtl_VL1
     */
    public ViewLinkImpl getReceiptHdr_Dtl_VL1() {
        return (ViewLinkImpl)findViewLink("ReceiptHdr_Dtl_VL1");
    }

    /**
     * Container's getter for getFunctionCodeROVO1.
     * @return getFunctionCodeROVO1
     */
    public ViewObjectImpl getgetFunctionCodeROVO1() {
        return (ViewObjectImpl)findViewObject("getFunctionCodeROVO1");
    }

    /**
     * Container's getter for Lookup_View_ROVO1.
     * @return Lookup_View_ROVO1
     */
    public ViewObjectImpl getLookup_View_ROVO1() {
        return (ViewObjectImpl)findViewObject("Lookup_View_ROVO1");
    }

    /**
     * Container's getter for ARReceiptMethod_ROVO1.
     * @return ARReceiptMethod_ROVO1
     */
    public ViewObjectImpl getARReceiptMethod_ROVO1() {
        return (ViewObjectImpl)findViewObject("ARReceiptMethod_ROVO1");
    }

    /**
     * Container's getter for SearchReceiptRoVo1.
     * @return SearchReceiptRoVo1
     */
    public ViewObjectImpl getSearchReceiptRoVo1() {
        return (ViewObjectImpl)findViewObject("SearchReceiptRoVo1");
    }
}
