package model.AM;

import java.sql.CallableStatement;

import java.sql.SQLException;
import java.sql.Types;

import model.AM.common.WoScheduler_AM;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jun 06 14:04:24 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WoScheduler_AMImpl extends ApplicationModuleImpl implements WoScheduler_AM {
    /**
     * This is the default constructor (do not remove).
     */
    public WoScheduler_AMImpl() {
    }

    /**
     * Container's getter for SearchWoSchedulerTnx_RoVo1.
     * @return SearchWoSchedulerTnx_RoVo1
     */
    public ViewObjectImpl getSearchWoSchedulerTnx_RoVo1() {
        return (ViewObjectImpl)findViewObject("SearchWoSchedulerTnx_RoVo1");
    }

    /**
     * Container's getter for WoSchedulingMainHdr_VO1.
     * @return WoSchedulingMainHdr_VO1
     */
    public ViewObjectImpl getWoSchedulingMainHdr_VO1() {
        return (ViewObjectImpl)findViewObject("WoSchedulingMainHdr_VO1");
    }

    /**
     * Container's getter for WoSchedulerTnxHdr_VO1.
     * @return WoSchedulerTnxHdr_VO1
     */
    public ViewObjectImpl getWoSchedulerTnxHdr_VO1() {
        return (ViewObjectImpl)findViewObject("WoSchedulerTnxHdr_VO1");
    }

    /**
     * Container's getter for WoSchedulerTnxResource_VO1.
     * @return WoSchedulerTnxResource_VO1
     */
    public ViewObjectImpl getWoSchedulerTnxResource_VO1() {
        return (ViewObjectImpl)findViewObject("WoSchedulerTnxResource_VO1");
    }

    /**
     * Container's getter for getApprovalHistoryROVo1.
     * @return getApprovalHistoryROVo1
     */
    public ViewObjectImpl getgetApprovalHistoryROVo1() {
        return (ViewObjectImpl)findViewObject("getApprovalHistoryROVo1");
    }

    /**
     * Container's getter for WoSchMainHdr_WoSchTnxHdr_VL1.
     * @return WoSchMainHdr_WoSchTnxHdr_VL1
     */
    public ViewLinkImpl getWoSchMainHdr_WoSchTnxHdr_VL1() {
        return (ViewLinkImpl)findViewLink("WoSchMainHdr_WoSchTnxHdr_VL1");
    }

    /**
     * Container's getter for WoSchTnxHdrTnxResource_VL1.
     * @return WoSchTnxHdrTnxResource_VL1
     */
    public ViewLinkImpl getWoSchTnxHdrTnxResource_VL1() {
        return (ViewLinkImpl)findViewLink("WoSchTnxHdrTnxResource_VL1");
    }

    /**
     * Container's getter for WoSchMainHdr_Approval_VL1.
     * @return WoSchMainHdr_Approval_VL1
     */
    public ViewLinkImpl getWoSchMainHdr_Approval_VL1() {
        return (ViewLinkImpl)findViewLink("WoSchMainHdr_Approval_VL1");
    }
    //reWorkForHistRecord
            public String reWorkForHistRecord(String mainId,String userId,String reason)
            {
                String flag="null";
                CallableStatement cs=this.getDBTransaction().createCallableStatement("{call WO_SCH_PKG.WO_SCHEDING_HIST(?,?,?,?,?)}",1);
                try {
                    cs.setString(1,mainId);
                    cs.setString(2,userId);
                    cs.setString(3,reason);
                    cs.registerOutParameter(4,Types.VARCHAR);
                    cs.registerOutParameter(5,Types.VARCHAR);
                    cs.execute();              
                  flag=cs.getString(5).toString();
                } catch (SQLException e) {
                }
                return flag;
            }

    /**
     * Container's getter for getFunctionCodeROVO1.
     * @return getFunctionCodeROVO1
     */
    public ViewObjectImpl getgetFunctionCodeROVO1() {
        return (ViewObjectImpl)findViewObject("getFunctionCodeROVO1");
    }

    /**
     * Container's getter for getAllWoRscTnxDtls_RoVo1.
     * @return getAllWoRscTnxDtls_RoVo1
     */
    public ViewObjectImpl getgetAllWoRscTnxDtls_RoVo1() {
        return (ViewObjectImpl)findViewObject("getAllWoRscTnxDtls_RoVo1");
    }

    /**
     * Container's getter for GetWoOperationRoVo1.
     * @return GetWoOperationRoVo1
     */
    public ViewObjectImpl getGetWoOperationRoVo1() {
        return (ViewObjectImpl)findViewObject("GetWoOperationRoVo1");
    }
}
