package model.VO;

import java.math.BigDecimal;

import java.sql.Timestamp;

import model.EO.BookingCustomer_EOImpl;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.RowSetIterator;
import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaRow;
import oracle.jbo.ViewObject;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 13 17:02:20 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BookingCustomer_VORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        BookCustId {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getBookCustId();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setBookCustId((BigDecimal)value);
            }
        }
        ,
        BookingId {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getBookingId();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setBookingId((BigDecimal)value);
            }
        }
        ,
        CustId {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getCustId();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setCustId((BigDecimal)value);
            }
        }
        ,
        CustSiteId {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getCustSiteId();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setCustSiteId((BigDecimal)value);
            }
        }
        ,
        CustContactId {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getCustContactId();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setCustContactId((BigDecimal)value);
            }
        }
        ,
        CustName {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getCustName();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setCustName((String)value);
            }
        }
        ,
        TrnNumber {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getTrnNumber();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setTrnNumber((BigDecimal)value);
            }
        }
        ,
        CustCategory {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getCustCategory();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setCustCategory((String)value);
            }
        }
        ,
        CustAccName {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getCustAccName();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setCustAccName((String)value);
            }
        }
        ,
        ShipToAddr {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getShipToAddr();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setShipToAddr((String)value);
            }
        }
        ,
        BillToAddr {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getBillToAddr();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setBillToAddr((String)value);
            }
        }
        ,
        Religion {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getReligion();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setReligion((String)value);
            }
        }
        ,
        VisaType {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getVisaType();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setVisaType((String)value);
            }
        }
        ,
        Nationality {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getNationality();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setNationality((String)value);
            }
        }
        ,
        CustBankName {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getCustBankName();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setCustBankName((String)value);
            }
        }
        ,
        CustBranchName {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getCustBranchName();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setCustBranchName((String)value);
            }
        }
        ,
        CustBankAccNumber {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getCustBankAccNumber();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setCustBankAccNumber((String)value);
            }
        }
        ,
        AttributeCategory {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getAttributeCategory();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setAttributeCategory((String)value);
            }
        }
        ,
        Attribute1 {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getAttribute11();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getAttribute12();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getAttribute13();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getAttribute14();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getAttribute15();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        Attribute16 {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getAttribute16();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute16((String)value);
            }
        }
        ,
        Attribute17 {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getAttribute17();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute17((String)value);
            }
        }
        ,
        Attribute18 {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getAttribute18();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute18((String)value);
            }
        }
        ,
        Attribute19 {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getAttribute19();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute19((String)value);
            }
        }
        ,
        Attribute20 {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getAttribute20();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute20((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setCreationDate((Timestamp)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setLastUpdateDate((Timestamp)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setLastUpdateLogin((String)value);
            }
        }
        ,
        RowID {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getRowID();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setRowID((String)value);
            }
        }
        ,
        CustomerNameAr {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getCustomerNameAr();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setCustomerNameAr((String)value);
            }
        }
        ,
        CustomerNumberAr {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getCustomerNumberAr();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setCustomerNumberAr((String)value);
            }
        }
        ,
        CustIdAr {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getCustIdAr();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setCustIdAr((BigDecimal)value);
            }
        }
        ,
        BillToAddr1 {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getBillToAddr1();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setBillToAddr1((String)value);
            }
        }
        ,
        ShipToAddr1 {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getShipToAddr1();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setShipToAddr1((String)value);
            }
        }
        ,
        MobileNo {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getMobileNo();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setMobileNo((String)value);
            }
        }
        ,
        PhoneNo {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getPhoneNo();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setPhoneNo((String)value);
            }
        }
        ,
        EmailId {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getEmailId();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setEmailId((String)value);
            }
        }
        ,
        Trans_CustomerNo {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getTrans_CustomerNo();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setTrans_CustomerNo((String)value);
            }
        }
        ,
        NationalityTrans {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getNationalityTrans();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setNationalityTrans((String)value);
            }
        }
        ,
        Trans_CustIdAr {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getTrans_CustIdAr();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setTrans_CustIdAr((String)value);
            }
        }
        ,
        MobileNoTrans {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getMobileNoTrans();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setMobileNoTrans((String)value);
            }
        }
        ,
        PhoneNoTrans {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getPhoneNoTrans();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setPhoneNoTrans((String)value);
            }
        }
        ,
        EmailIdTrans {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getEmailIdTrans();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setEmailIdTrans((String)value);
            }
        }
        ,
        Lookup_View_ROVO1 {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getLookup_View_ROVO1();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CustomerTypeStaticROVO1 {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getCustomerTypeStaticROVO1();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Lookup_View_VisaType {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getLookup_View_VisaType();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Lookup_View_Res {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getLookup_View_Res();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GetCustomerDetailsROVO1 {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getGetCustomerDetailsROVO1();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GetCustomerDetailsROVO2 {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getGetCustomerDetailsROVO2();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GetCustomerDetailsROVO3 {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getGetCustomerDetailsROVO3();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        getCustomerSiteDetailsROVO1 {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getgetCustomerSiteDetailsROVO1();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        getCustomerSiteDetailsROVO2 {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getgetCustomerSiteDetailsROVO2();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        getCustomerSiteDetailsROVO3 {
            public Object get(BookingCustomer_VORowImpl obj) {
                return obj.getgetCustomerSiteDetailsROVO3();
            }

            public void put(BookingCustomer_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(BookingCustomer_VORowImpl object);

        public abstract void put(BookingCustomer_VORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BOOKCUSTID = AttributesEnum.BookCustId.index();
    public static final int BOOKINGID = AttributesEnum.BookingId.index();
    public static final int CUSTID = AttributesEnum.CustId.index();
    public static final int CUSTSITEID = AttributesEnum.CustSiteId.index();
    public static final int CUSTCONTACTID = AttributesEnum.CustContactId.index();
    public static final int CUSTNAME = AttributesEnum.CustName.index();
    public static final int TRNNUMBER = AttributesEnum.TrnNumber.index();
    public static final int CUSTCATEGORY = AttributesEnum.CustCategory.index();
    public static final int CUSTACCNAME = AttributesEnum.CustAccName.index();
    public static final int SHIPTOADDR = AttributesEnum.ShipToAddr.index();
    public static final int BILLTOADDR = AttributesEnum.BillToAddr.index();
    public static final int RELIGION = AttributesEnum.Religion.index();
    public static final int VISATYPE = AttributesEnum.VisaType.index();
    public static final int NATIONALITY = AttributesEnum.Nationality.index();
    public static final int CUSTBANKNAME = AttributesEnum.CustBankName.index();
    public static final int CUSTBRANCHNAME = AttributesEnum.CustBranchName.index();
    public static final int CUSTBANKACCNUMBER = AttributesEnum.CustBankAccNumber.index();
    public static final int ATTRIBUTECATEGORY = AttributesEnum.AttributeCategory.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int ATTRIBUTE16 = AttributesEnum.Attribute16.index();
    public static final int ATTRIBUTE17 = AttributesEnum.Attribute17.index();
    public static final int ATTRIBUTE18 = AttributesEnum.Attribute18.index();
    public static final int ATTRIBUTE19 = AttributesEnum.Attribute19.index();
    public static final int ATTRIBUTE20 = AttributesEnum.Attribute20.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int ROWID = AttributesEnum.RowID.index();
    public static final int CUSTOMERNAMEAR = AttributesEnum.CustomerNameAr.index();
    public static final int CUSTOMERNUMBERAR = AttributesEnum.CustomerNumberAr.index();
    public static final int CUSTIDAR = AttributesEnum.CustIdAr.index();
    public static final int BILLTOADDR1 = AttributesEnum.BillToAddr1.index();
    public static final int SHIPTOADDR1 = AttributesEnum.ShipToAddr1.index();
    public static final int MOBILENO = AttributesEnum.MobileNo.index();
    public static final int PHONENO = AttributesEnum.PhoneNo.index();
    public static final int EMAILID = AttributesEnum.EmailId.index();
    public static final int TRANS_CUSTOMERNO = AttributesEnum.Trans_CustomerNo.index();
    public static final int NATIONALITYTRANS = AttributesEnum.NationalityTrans.index();
    public static final int TRANS_CUSTIDAR = AttributesEnum.Trans_CustIdAr.index();
    public static final int MOBILENOTRANS = AttributesEnum.MobileNoTrans.index();
    public static final int PHONENOTRANS = AttributesEnum.PhoneNoTrans.index();
    public static final int EMAILIDTRANS = AttributesEnum.EmailIdTrans.index();
    public static final int LOOKUP_VIEW_ROVO1 = AttributesEnum.Lookup_View_ROVO1.index();
    public static final int CUSTOMERTYPESTATICROVO1 = AttributesEnum.CustomerTypeStaticROVO1.index();
    public static final int LOOKUP_VIEW_VISATYPE = AttributesEnum.Lookup_View_VisaType.index();
    public static final int LOOKUP_VIEW_RES = AttributesEnum.Lookup_View_Res.index();
    public static final int GETCUSTOMERDETAILSROVO1 = AttributesEnum.GetCustomerDetailsROVO1.index();
    public static final int GETCUSTOMERDETAILSROVO2 = AttributesEnum.GetCustomerDetailsROVO2.index();
    public static final int GETCUSTOMERDETAILSROVO3 = AttributesEnum.GetCustomerDetailsROVO3.index();
    public static final int GETCUSTOMERSITEDETAILSROVO1 = AttributesEnum.getCustomerSiteDetailsROVO1.index();
    public static final int GETCUSTOMERSITEDETAILSROVO2 = AttributesEnum.getCustomerSiteDetailsROVO2.index();
    public static final int GETCUSTOMERSITEDETAILSROVO3 = AttributesEnum.getCustomerSiteDetailsROVO3.index();

    /**
     * This is the default constructor (do not remove).
     */
    public BookingCustomer_VORowImpl() {
    }

    /**
     * Gets BookingCustomer_EO entity object.
     * @return the BookingCustomer_EO
     */
    public BookingCustomer_EOImpl getBookingCustomer_EO() {
        return (BookingCustomer_EOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for BOOK_CUST_ID using the alias name BookCustId.
     * @return the BOOK_CUST_ID
     */
    public BigDecimal getBookCustId() {
        return (BigDecimal) getAttributeInternal(BOOKCUSTID);
    }

    /**
     * Sets <code>value</code> as attribute value for BOOK_CUST_ID using the alias name BookCustId.
     * @param value value to set the BOOK_CUST_ID
     */
    public void setBookCustId(BigDecimal value) {
        setAttributeInternal(BOOKCUSTID, value);
    }

    /**
     * Gets the attribute value for BOOKING_ID using the alias name BookingId.
     * @return the BOOKING_ID
     */
    public BigDecimal getBookingId() {
        return (BigDecimal) getAttributeInternal(BOOKINGID);
    }

    /**
     * Sets <code>value</code> as attribute value for BOOKING_ID using the alias name BookingId.
     * @param value value to set the BOOKING_ID
     */
    public void setBookingId(BigDecimal value) {
        setAttributeInternal(BOOKINGID, value);
    }

    /**
     * Gets the attribute value for CUST_ID using the alias name CustId.
     * @return the CUST_ID
     */
    public BigDecimal getCustId() {
        return (BigDecimal) getAttributeInternal(CUSTID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUST_ID using the alias name CustId.
     * @param value value to set the CUST_ID
     */
    public void setCustId(BigDecimal value) {
        setAttributeInternal(CUSTID, value);
    }

    /**
     * Gets the attribute value for CUST_SITE_ID using the alias name CustSiteId.
     * @return the CUST_SITE_ID
     */
    public BigDecimal getCustSiteId() {
        return (BigDecimal) getAttributeInternal(CUSTSITEID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUST_SITE_ID using the alias name CustSiteId.
     * @param value value to set the CUST_SITE_ID
     */
    public void setCustSiteId(BigDecimal value) {
        setAttributeInternal(CUSTSITEID, value);
    }

    /**
     * Gets the attribute value for CUST_CONTACT_ID using the alias name CustContactId.
     * @return the CUST_CONTACT_ID
     */
    public BigDecimal getCustContactId() {
        return (BigDecimal) getAttributeInternal(CUSTCONTACTID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUST_CONTACT_ID using the alias name CustContactId.
     * @param value value to set the CUST_CONTACT_ID
     */
    public void setCustContactId(BigDecimal value) {
        setAttributeInternal(CUSTCONTACTID, value);
    }

    /**
     * Gets the attribute value for CUST_NAME using the alias name CustName.
     * @return the CUST_NAME
     */
    public String getCustName() {
        return (String) getAttributeInternal(CUSTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for CUST_NAME using the alias name CustName.
     * @param value value to set the CUST_NAME
     */
    public void setCustName(String value) {
        setAttributeInternal(CUSTNAME, value);
    }

    /**
     * Gets the attribute value for TRN_NUMBER using the alias name TrnNumber.
     * @return the TRN_NUMBER
     */
    public BigDecimal getTrnNumber() {
        return (BigDecimal) getAttributeInternal(TRNNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for TRN_NUMBER using the alias name TrnNumber.
     * @param value value to set the TRN_NUMBER
     */
    public void setTrnNumber(BigDecimal value) {
        setAttributeInternal(TRNNUMBER, value);
    }

    /**
     * Gets the attribute value for CUST_CATEGORY using the alias name CustCategory.
     * @return the CUST_CATEGORY
     */
    public String getCustCategory() {
        return (String) getAttributeInternal(CUSTCATEGORY);
    }

    /**
     * Sets <code>value</code> as attribute value for CUST_CATEGORY using the alias name CustCategory.
     * @param value value to set the CUST_CATEGORY
     */
    public void setCustCategory(String value) {
        setAttributeInternal(CUSTCATEGORY, value);
    }

    /**
     * Gets the attribute value for CUST_ACC_NAME using the alias name CustAccName.
     * @return the CUST_ACC_NAME
     */
    public String getCustAccName() {
        return (String) getAttributeInternal(CUSTACCNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for CUST_ACC_NAME using the alias name CustAccName.
     * @param value value to set the CUST_ACC_NAME
     */
    public void setCustAccName(String value) {
        setAttributeInternal(CUSTACCNAME, value);
    }

    /**
     * Gets the attribute value for SHIP_TO_ADDR using the alias name ShipToAddr.
     * @return the SHIP_TO_ADDR
     */
    public String getShipToAddr() {
        return (String) getAttributeInternal(SHIPTOADDR);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIP_TO_ADDR using the alias name ShipToAddr.
     * @param value value to set the SHIP_TO_ADDR
     */
    public void setShipToAddr(String value) {
        setAttributeInternal(SHIPTOADDR, value);
    }

    /**
     * Gets the attribute value for BILL_TO_ADDR using the alias name BillToAddr.
     * @return the BILL_TO_ADDR
     */
    public String getBillToAddr() {
        return (String) getAttributeInternal(BILLTOADDR);
    }

    /**
     * Sets <code>value</code> as attribute value for BILL_TO_ADDR using the alias name BillToAddr.
     * @param value value to set the BILL_TO_ADDR
     */
    public void setBillToAddr(String value) {
        setAttributeInternal(BILLTOADDR, value);
    }

    /**
     * Gets the attribute value for RELIGION using the alias name Religion.
     * @return the RELIGION
     */
    public String getReligion() {
        return (String) getAttributeInternal(RELIGION);
    }

    /**
     * Sets <code>value</code> as attribute value for RELIGION using the alias name Religion.
     * @param value value to set the RELIGION
     */
    public void setReligion(String value) {
        setAttributeInternal(RELIGION, value);
    }

    /**
     * Gets the attribute value for VISA_TYPE using the alias name VisaType.
     * @return the VISA_TYPE
     */
    public String getVisaType() {
        return (String) getAttributeInternal(VISATYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for VISA_TYPE using the alias name VisaType.
     * @param value value to set the VISA_TYPE
     */
    public void setVisaType(String value) {
        setAttributeInternal(VISATYPE, value);
    }

    /**
     * Gets the attribute value for NATIONALITY using the alias name Nationality.
     * @return the NATIONALITY
     */
    public String getNationality() {
        return (String) getAttributeInternal(NATIONALITY);
    }

    /**
     * Sets <code>value</code> as attribute value for NATIONALITY using the alias name Nationality.
     * @param value value to set the NATIONALITY
     */
    public void setNationality(String value) {
        setAttributeInternal(NATIONALITY, value);
    }

    /**
     * Gets the attribute value for CUST_BANK_NAME using the alias name CustBankName.
     * @return the CUST_BANK_NAME
     */
    public String getCustBankName() {
        return (String) getAttributeInternal(CUSTBANKNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for CUST_BANK_NAME using the alias name CustBankName.
     * @param value value to set the CUST_BANK_NAME
     */
    public void setCustBankName(String value) {
        setAttributeInternal(CUSTBANKNAME, value);
    }

    /**
     * Gets the attribute value for CUST_BRANCH_NAME using the alias name CustBranchName.
     * @return the CUST_BRANCH_NAME
     */
    public String getCustBranchName() {
        return (String) getAttributeInternal(CUSTBRANCHNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for CUST_BRANCH_NAME using the alias name CustBranchName.
     * @param value value to set the CUST_BRANCH_NAME
     */
    public void setCustBranchName(String value) {
        setAttributeInternal(CUSTBRANCHNAME, value);
    }

    /**
     * Gets the attribute value for CUST_BANK_ACC_NUMBER using the alias name CustBankAccNumber.
     * @return the CUST_BANK_ACC_NUMBER
     */
    public String getCustBankAccNumber() {
        return (String) getAttributeInternal(CUSTBANKACCNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for CUST_BANK_ACC_NUMBER using the alias name CustBankAccNumber.
     * @param value value to set the CUST_BANK_ACC_NUMBER
     */
    public void setCustBankAccNumber(String value) {
        setAttributeInternal(CUSTBANKACCNUMBER, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @return the ATTRIBUTE_CATEGORY
     */
    public String getAttributeCategory() {
        return (String) getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @param value value to set the ATTRIBUTE_CATEGORY
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @return the ATTRIBUTE11
     */
    public String getAttribute11() {
        return (String) getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @param value value to set the ATTRIBUTE11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @return the ATTRIBUTE12
     */
    public String getAttribute12() {
        return (String) getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @param value value to set the ATTRIBUTE12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @return the ATTRIBUTE13
     */
    public String getAttribute13() {
        return (String) getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @param value value to set the ATTRIBUTE13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @return the ATTRIBUTE14
     */
    public String getAttribute14() {
        return (String) getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @param value value to set the ATTRIBUTE14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @return the ATTRIBUTE15
     */
    public String getAttribute15() {
        return (String) getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @param value value to set the ATTRIBUTE15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE16 using the alias name Attribute16.
     * @return the ATTRIBUTE16
     */
    public String getAttribute16() {
        return (String) getAttributeInternal(ATTRIBUTE16);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE16 using the alias name Attribute16.
     * @param value value to set the ATTRIBUTE16
     */
    public void setAttribute16(String value) {
        setAttributeInternal(ATTRIBUTE16, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE17 using the alias name Attribute17.
     * @return the ATTRIBUTE17
     */
    public String getAttribute17() {
        return (String) getAttributeInternal(ATTRIBUTE17);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE17 using the alias name Attribute17.
     * @param value value to set the ATTRIBUTE17
     */
    public void setAttribute17(String value) {
        setAttributeInternal(ATTRIBUTE17, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE18 using the alias name Attribute18.
     * @return the ATTRIBUTE18
     */
    public String getAttribute18() {
        return (String) getAttributeInternal(ATTRIBUTE18);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE18 using the alias name Attribute18.
     * @param value value to set the ATTRIBUTE18
     */
    public void setAttribute18(String value) {
        setAttributeInternal(ATTRIBUTE18, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE19 using the alias name Attribute19.
     * @return the ATTRIBUTE19
     */
    public String getAttribute19() {
        return (String) getAttributeInternal(ATTRIBUTE19);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE19 using the alias name Attribute19.
     * @param value value to set the ATTRIBUTE19
     */
    public void setAttribute19(String value) {
        setAttributeInternal(ATTRIBUTE19, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE20 using the alias name Attribute20.
     * @return the ATTRIBUTE20
     */
    public String getAttribute20() {
        return (String) getAttributeInternal(ATTRIBUTE20);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE20 using the alias name Attribute20.
     * @param value value to set the ATTRIBUTE20
     */
    public void setAttribute20(String value) {
        setAttributeInternal(ATTRIBUTE20, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for ROWID using the alias name RowID.
     * @return the ROWID
     */
    public String getRowID() {
        return (String) getAttributeInternal(ROWID);
    }

    /**
     * Sets <code>value</code> as attribute value for ROWID using the alias name RowID.
     * @param value value to set the ROWID
     */
    public void setRowID(String value) {
        setAttributeInternal(ROWID, value);
    }

    /**
     * Gets the attribute value for CUSTOMER_NAME_AR using the alias name CustomerNameAr.
     * @return the CUSTOMER_NAME_AR
     */
    public String getCustomerNameAr() {
        return (String) getAttributeInternal(CUSTOMERNAMEAR);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMER_NAME_AR using the alias name CustomerNameAr.
     * @param value value to set the CUSTOMER_NAME_AR
     */
    public void setCustomerNameAr(String value) {
        setAttributeInternal(CUSTOMERNAMEAR, value);
    }

    /**
     * Gets the attribute value for CUSTOMER_NUMBER_AR using the alias name CustomerNumberAr.
     * @return the CUSTOMER_NUMBER_AR
     */
    public String getCustomerNumberAr() {
        return (String) getAttributeInternal(CUSTOMERNUMBERAR);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMER_NUMBER_AR using the alias name CustomerNumberAr.
     * @param value value to set the CUSTOMER_NUMBER_AR
     */
    public void setCustomerNumberAr(String value) {
        setAttributeInternal(CUSTOMERNUMBERAR, value);
    }

    /**
     * Gets the attribute value for CUST_ID_AR using the alias name CustIdAr.
     * @return the CUST_ID_AR
     */
    public BigDecimal getCustIdAr() {
        return (BigDecimal) getAttributeInternal(CUSTIDAR);
    }

    /**
     * Sets <code>value</code> as attribute value for CUST_ID_AR using the alias name CustIdAr.
     * @param value value to set the CUST_ID_AR
     */
    public void setCustIdAr(BigDecimal value) {
        setAttributeInternal(CUSTIDAR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_CustomerNo.
     * @return the Trans_CustomerNo
     */
    public String getTrans_CustomerNo() {
        return (String) getAttributeInternal(TRANS_CUSTOMERNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_CustomerNo.
     * @param value value to set the  Trans_CustomerNo
     */
    public void setTrans_CustomerNo(String value) {
        setAttributeInternal(TRANS_CUSTOMERNO, value);
    }

    /**
     * Gets the attribute value for NATIONALITY_TRANS using the alias name NationalityTrans.
     * @return the NATIONALITY_TRANS
     */
    public String getNationalityTrans() {
        String currcode = null;
               String Name = null;
//            if (getNationality() != null) {
//                currcode = getNationality();
//                            ViewObject vo = getLookup_View_ROVO1().getViewObject();   
//                            ViewCriteria vc = vo.createViewCriteria();
//                            ViewCriteriaRow vcRow = vc.createViewCriteriaRow();
//                            vcRow.setAttribute("LookupValueName",currcode);
//                            vc.addRow(vcRow);
//                            vo.applyViewCriteria(vc);
//                            vo.executeQuery();
//                            if (vo.first() != null) {
//                                RowSetIterator voRSI = vo.createRowSetIterator(null);
//                                while (voRSI.hasNext()) {
//                                    Row row = voRSI.next();
//                                Name = row.getAttribute("LookupValueNameDisp").toString();
//                                }
//                            }
//                                return Name;
               //Check if DepartmentId is not null then get DepartmentName for that Id
               if (getNationality() != null) {
                   currcode = getNationality();
                   //getDepartmentsVO1 is ViewAccessor of LOV ViewObject
                   Row[] deptRows;
                   deptRows =
                           getLookup_View_ROVO1().getFilteredRows("LookupValueName",
                                                                  currcode);
                   if (deptRows.length > 0) {
                       Name =
        deptRows[0].getAttribute("LookupValueNameDisp").toString();
                   }
                   return Name;

               } else {
                   return (String) getAttributeInternal(NATIONALITYTRANS);
               }   
    }

    /**
     * Sets <code>value</code> as attribute value for NATIONALITY_TRANS using the alias name NationalityTrans.
     * @param value value to set the NATIONALITY_TRANS
     */
    public void setNationalityTrans(String value) {
        setAttributeInternal(NATIONALITYTRANS, value);
    }


    /**
     * Gets the attribute value for the calculated attribute Trans_CustIdAr.
     * @return the Trans_CustIdAr
     */
    public String getTrans_CustIdAr() {
        Number custId = null;
                        String custName = null;
//            if (getCustIdAr() != null) {
//                custId = getCustIdAr();
//                                ViewObject vo = getGetCustomerDetailsROVO2().getViewObject();
//                                    
//                                ViewCriteria vc = vo.createViewCriteria();
//                                ViewCriteriaRow vcRow = vc.createViewCriteriaRow();
//                                vcRow.setAttribute("CustId",custId);
//                                vc.addRow(vcRow);
//                                vo.applyViewCriteria(vc);
//                                vo.executeQuery();
//                                if (vo.first() != null) {
//                                    custName = vo.first().getAttribute("CustomerName").toString();
//                                }
//                                    return custName;
                        //Check if DepartmentId is not null then get DepartmentName for that Id
                        if (getCustIdAr() != null) {
                            custId = getCustIdAr();
                            //getDepartmentsVO1 is ViewAccessor of LOV ViewObject
                            Row[] deptRows;
                            deptRows = getGetCustomerDetailsROVO2().getFilteredRows("CustId", custId);
                            if (deptRows.length > 0) {
                                custName = deptRows[0].getAttribute("CustomerName").toString();
                            }
                            return custName;

                        } else {
                        
                        
                    return (String) getAttributeInternal(TRANS_CUSTIDAR);
                }

    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_CustIdAr.
     * @param value value to set the  Trans_CustIdAr
     */
    public void setTrans_CustIdAr(String value) {
        setAttributeInternal(TRANS_CUSTIDAR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MobileNoTrans.
     * @return the MobileNoTrans
     */
    public String getMobileNoTrans() {
        String siteNo = null;
                        String mobileNo = null;
//                        if (getShipToAddr() != null) {
//                            siteNo = getShipToAddr();
//                            Row[] deptRows;
//                            deptRows = getgetCustomerSiteDetailsROVO2().getFilteredRows("SiteNumber", siteNo);
//                            if (deptRows.length > 0) {
//                                mobileNo = deptRows[0].getAttribute("MobileNo")== null ? "" : deptRows[0].getAttribute("MobileNo").toString();
//                            }
//                            return mobileNo;
//
//                        } else {
        return (String) getAttributeInternal(MOBILENOTRANS);
//                        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MobileNoTrans.
     * @param value value to set the  MobileNoTrans
     */
    public void setMobileNoTrans(String value) {
        setAttributeInternal(MOBILENOTRANS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PhoneNoTrans.
     * @return the PhoneNoTrans
     */
    public String getPhoneNoTrans() {
        String siteNo = null;
                        String phoneNo = null;
//                        if (getShipToAddr() != null) {
//                            siteNo = getShipToAddr();
//                            Row[] deptRows;
//                            deptRows = getgetCustomerSiteDetailsROVO2().getFilteredRows("SiteNumber", siteNo);
//                            if (deptRows.length > 0) {
//                                phoneNo = deptRows[0].getAttribute("PhoneNo") == null ? "" : deptRows[0].getAttribute("PhoneNo").toString();
//                            }
//                            return phoneNo;
//
//                        } else {
        return (String) getAttributeInternal(PHONENOTRANS);
//                        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PhoneNoTrans.
     * @param value value to set the  PhoneNoTrans
     */
    public void setPhoneNoTrans(String value) {
        setAttributeInternal(PHONENOTRANS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EmailIdTrans.
     * @return the EmailIdTrans
     */
    public String getEmailIdTrans() {
        String siteNo = null;
                        String emailId = null;
//                        if (getShipToAddr() != null) {
//                            siteNo = getShipToAddr();
//                            Row[] deptRows;
//                            deptRows = getgetCustomerSiteDetailsROVO2().getFilteredRows("SiteNumber", siteNo);
//                            if (deptRows.length > 0) {
//                                emailId = deptRows[0].getAttribute("EmailId") == null ? "" : deptRows[0].getAttribute("EmailId").toString();
//                            }
//                            return emailId;
//
//                        } else {
        return (String) getAttributeInternal(EMAILIDTRANS);
//                        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EmailIdTrans.
     * @param value value to set the  EmailIdTrans
     */
    public void setEmailIdTrans(String value) {
        setAttributeInternal(EMAILIDTRANS, value);
    }

    /**
     * Gets the attribute value for BILL_TO_ADDR using the alias name BillToAddr1.
     * @return the BILL_TO_ADDR
     */
    public String getBillToAddr1() {
        return (String) getAttributeInternal(BILLTOADDR1);
    }

    /**
     * Sets <code>value</code> as attribute value for BILL_TO_ADDR using the alias name BillToAddr1.
     * @param value value to set the BILL_TO_ADDR
     */
    public void setBillToAddr1(String value) {
        setAttributeInternal(BILLTOADDR1, value);
    }

    /**
     * Gets the attribute value for SHIP_TO_ADDR using the alias name ShipToAddr1.
     * @return the SHIP_TO_ADDR
     */
    public String getShipToAddr1() {
        return (String) getAttributeInternal(SHIPTOADDR1);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIP_TO_ADDR using the alias name ShipToAddr1.
     * @param value value to set the SHIP_TO_ADDR
     */
    public void setShipToAddr1(String value) {
        setAttributeInternal(SHIPTOADDR1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MobileNo.
     * @return the MobileNo
     */
    public String getMobileNo() {
        return (String) getAttributeInternal(MOBILENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MobileNo.
     * @param value value to set the  MobileNo
     */
    public void setMobileNo(String value) {
        setAttributeInternal(MOBILENO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PhoneNo.
     * @return the PhoneNo
     */
    public String getPhoneNo() {
        return (String) getAttributeInternal(PHONENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PhoneNo.
     * @param value value to set the  PhoneNo
     */
    public void setPhoneNo(String value) {
        setAttributeInternal(PHONENO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EmailId.
     * @return the EmailId
     */
    public String getEmailId() {
        return (String) getAttributeInternal(EMAILID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EmailId.
     * @param value value to set the  EmailId
     */
    public void setEmailId(String value) {
        setAttributeInternal(EMAILID, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Lookup_View_ROVO1.
     */
    public RowSet getLookup_View_ROVO1() {
        return (RowSet)getAttributeInternal(LOOKUP_VIEW_ROVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CustomerTypeStaticROVO1.
     */
    public RowSet getCustomerTypeStaticROVO1() {
        return (RowSet)getAttributeInternal(CUSTOMERTYPESTATICROVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Lookup_View_VisaType.
     */
    public RowSet getLookup_View_VisaType() {
        return (RowSet)getAttributeInternal(LOOKUP_VIEW_VISATYPE);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Lookup_View_Res.
     */
    public RowSet getLookup_View_Res() {
        return (RowSet)getAttributeInternal(LOOKUP_VIEW_RES);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GetCustomerDetailsROVO1.
     */
    public RowSet getGetCustomerDetailsROVO1() {
        return (RowSet)getAttributeInternal(GETCUSTOMERDETAILSROVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GetCustomerDetailsROVO2.
     */
    public RowSet getGetCustomerDetailsROVO2() {
        return (RowSet)getAttributeInternal(GETCUSTOMERDETAILSROVO2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GetCustomerDetailsROVO3.
     */
    public RowSet getGetCustomerDetailsROVO3() {
        return (RowSet)getAttributeInternal(GETCUSTOMERDETAILSROVO3);
    }

    /**
     * Gets the view accessor <code>RowSet</code> getCustomerSiteDetailsROVO1.
     */
    public RowSet getgetCustomerSiteDetailsROVO1() {
        return (RowSet)getAttributeInternal(GETCUSTOMERSITEDETAILSROVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> getCustomerSiteDetailsROVO2.
     */
    public RowSet getgetCustomerSiteDetailsROVO2() {
        return (RowSet)getAttributeInternal(GETCUSTOMERSITEDETAILSROVO2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> getCustomerSiteDetailsROVO3.
     */
    public RowSet getgetCustomerSiteDetailsROVO3() {
        return (RowSet)getAttributeInternal(GETCUSTOMERSITEDETAILSROVO3);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
