package model.AM.client;

import model.AM.common.UserAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 24 12:26:36 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UserAMClient extends ApplicationModuleImpl implements UserAM {
    /**
     * This is the default constructor (do not remove).
     */
    public UserAMClient() {
    }

    public void prepareMenu(String userRole) {
        Object _ret =
            this.riInvokeExportedMethod(this,"prepareMenu",new String [] {"java.lang.String"},new Object[] {userRole});
        return;
    }

    public String CheckUserNaname(String UserName) {
        Object _ret =
            this.riInvokeExportedMethod(this,"CheckUserNaname",new String [] {"java.lang.String"},new Object[] {UserName});
        return (String)_ret;
    }
}
