package model.AM.client;

import model.AM.common.Booking_AM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 06 11:25:03 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Booking_AMClient extends ApplicationModuleImpl implements Booking_AM {
    /**
     * This is the default constructor (do not remove).
     */
    public Booking_AMClient() {
    }


    public String getSequenceNumber() {
        Object _ret =
            this.riInvokeExportedMethod(this,"getSequenceNumber",null,null);
        return (String)_ret;
    }

    public String autoRecomRC(String bookingNo, String userId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"autoRecomRC",new String [] {"java.lang.String","java.lang.String"},new Object[] {bookingNo, userId});
        return (String)_ret;
    }

    public String InvokeLeaseNumber(String b_unitid) {
        Object _ret =
            this.riInvokeExportedMethod(this,"InvokeLeaseNumber",new String [] {"java.lang.String"},new Object[] {b_unitid});
        return (String)_ret;
    }

    public String CreateMilestone() {
        Object _ret =
            this.riInvokeExportedMethod(this,"CreateMilestone",null,null);
        return (String)_ret;
    }

    public String CreateBookingDetails() {
        Object _ret =
            this.riInvokeExportedMethod(this,"CreateBookingDetails",null,null);
        return (String)_ret;
    }

    public String CreateBooking() {
        Object _ret = this.riInvokeExportedMethod(this,"CreateBooking",null,null);
        return (String)_ret;
    }

    public String refresh_update_bk(String bookingId, String offerId,
                                    String userId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"refresh_update_bk",new String [] {"java.lang.String","java.lang.String","java.lang.String"},new Object[] {bookingId, offerId, userId});
        return (String)_ret;
    }

    public String directToDraft(String rcId, String userId, String funcId,
                                String reason) {
        Object _ret =
            this.riInvokeExportedMethod(this,"directToDraft",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {rcId, userId, funcId, reason});
        return (String)_ret;
    }

    public String submitBkForAppr(String bookingId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"submitBkForAppr",new String [] {"java.lang.String"},new Object[] {bookingId});
        return (String)_ret;
    }

    public String responseBkForAppr(String bookingId, String reason,
                                    String apr_rej) {
        Object _ret =
            this.riInvokeExportedMethod(this,"responseBkForAppr",new String [] {"java.lang.String","java.lang.String","java.lang.String"},new Object[] {bookingId, reason, apr_rej});
        return (String)_ret;
    }

    public String getCashRcptIdRspnse(String pReceiptNo, String pCshRcptId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getCashRcptIdRspnse",new String [] {"java.lang.String","java.lang.String"},new Object[] {pReceiptNo, pCshRcptId});
        return (String)_ret;
    }
}
